//! The Fish Setup screen's text tables, copied from the executable's data.

/// `PTR_s_Philadelphia__Pa__005e0414` (@ 005e0414): the special fish's hometowns.
pub static PTR_s_Philadelphia__Pa__005e0414: [&[u8]; 6] = [
    b"Philadelphia, Pa.",
    b"Vienna, Austria",
    b"Biloxi, Miss.",
    b"Rensselaer, Ind.",
    b"Los Angeles, Calif.",
    b"North Pole",
];

/// `PTR_s_Virtual_Tank_005e0430` (@ 005e0430): hometowns (index 0 is "Virtual Tank").
pub static PTR_s_Virtual_Tank_005e0430: [&[u8]; 375] = [
    b"Virtual Tank",
    b"Abilene, Texas",
    b"Adak, Alaska",
    b"Canton, Ohio",
    b"Alamogordo, N.M.",
    b"Alamosa, Colo.",
    b"Albany, N.Y.",
    b"Albuquerque, N.M.",
    b"Alexandria, La.",
    b"Allentown, Pa.",
    b"Alpena, Mich.",
    b"Altus, Okla",
    b"Amarillo, Texas",
    b"Anchorage, Alaska",
    b"Apalachicola, Fla.",
    b"Asheville, N.C.",
    b"Aspen, Colo.",
    b"Astoria, Ore.",
    b"Athens, Ga.",
    b"Atlanta, Ga.",
    b"Augusta, Ga.",
    b"Austin, Texas",
    b"Bakersfield, Calif.",
    b"Baltimore, Md.",
    b"Bar Harbor, Maine",
    b"Barrow, Alaska",
    b"Baton Rouge, La.",
    b"Beckley, W.Va.",
    b"Beeville, Texas",
    b"Billings, Mont.",
    b"Biloxi, Miss.",
    b"Binghamton, N.Y.",
    b"Birmingham, Ala.",
    b"Bishop, Calif.",
    b"Bismarck, N.D.",
    b"Boston, Mass.",
    b"Bridgeport, Conn.",
    b"Brownsville, Texas",
    b"Brunswick, Maine",
    b"Buffalo, N.Y.",
    b"Burlington, Vt.",
    b"Cape Hatteras, N.C.",
    b"Caribou, Maine",
    b"Casper, Wyo.",
    b"Charleston, S.C.",
    b"Charleston, W.Va.",
    b"Charlotte, N.C.",
    b"Chattanooga, Tenn.",
    b"Cheyenne, Wyo.",
    b"Chicago, Ill.",
    b"Cincinnati, Ohio",
    b"Clayton, N.M.",
    b"Cleveland, Ohio",
    b"Clovis, N.M.",
    b"Cocoa Beach, Fla.",
    b"Colorado Springs, Colo.",
    b"Columbia, Mo.",
    b"Columbia, S.C.",
    b"Columbus, Ga.",
    b"Columbus, Miss.",
    b"Columbus, Ohio",
    b"Concord, N.H.",
    b"Concordia, Kan.",
    b"Corpus Christi, Texas",
    b"Covington, Ky.",
    b"Crested Butte, Colo.",
    b"Daggett, Calif.",
    b"Dallas, Texas",
    b"Davenport, Iowa",
    b"Dayton, Ohio",
    b"Daytona Beach, Fla.",
    b"Denver, Colo.",
    b"Del Rio, Texas",
    b"Des Moines, Iowa",
    b"Detroit, Mich.",
    b"Dodge City, Kan.",
    b"Dover, Del.",
    b"Dubuque, Iowa",
    b"Duluth, Minn.",
    b"Elkins, W.Va.",
    b"Elko, Nev.",
    b"El Paso, Texas",
    b"Ely, Nev.",
    b"Enid, Okla.",
    b"Erie, Pa.",
    b"Eugene, Ore.",
    b"Eureka, Calif.",
    b"Evansville, Ind.",
    b"Fairbanks, Alaska",
    b"Fallon, Nev.",
    b"Fargo, N.D.",
    b"Fayetteville, N.C.",
    b"Flagstaff, Ariz.",
    b"Flint, Mich.",
    b"Fort Myers, Fla.",
    b"Fort Smith, Ark.",
    b"Fort Wayne, Ind.",
    b"Fresno, Calif.",
    b"Gainesville, Fla.",
    b"Galveston, Texas",
    b"Gatlinburg, Tenn.",
    b"Gila Bend, Ariz.",
    b"Glasgow, Mont.",
    b"Glenview, Ill.",
    b"Goldsboro, N.C.",
    b"Goodland, Kan.",
    b"Grand Forks, N.D.",
    b"Grand Island, Neb.",
    b"Grand Junction, Colo.",
    b"Grand Rapids, Mich.",
    b"Great Falls, Mont.",
    b"Green Bay, Wis.",
    b"Greensboro, N.C.",
    b"Greenville, S.C.",
    b"Gulfport, Miss.",
    b"Harrisburg, Pa.",
    b"Hartford, Conn.",
    b"Havre, Mont.",
    b"Helena, Mont.",
    b"Hilo, Hawaii",
    b"Hondo, Texas",
    b"Honolulu, Hawaii",
    b"Houghton Lake, Mich.",
    b"Houston, Texas",
    b"Huntington, W.Va.",
    b"Huntsville, Ala.",
    b"Huron, S.D.",
    b"Indianapolis, Ind.",
    b"Long Island, N.Y.",
    b"Jackson, Ky.",
    b"Jackson, Miss.",
    b"Jacksonville, Fla.",
    b"Jacksonville, N.C.",
    b"Juneau, Alaska",
    b"Kahului, Hawaii",
    b"Kalispell, Mont.",
    b"Kansas City, Kan.",
    b"Kansas City, Mo.",
    b"Key West, Fla.",
    b"Killeen, Texas",
    b"Kingsville, Texas",
    b"Klamath Falls, Ore.",
    b"Knoxville, Tenn.",
    b"La Crosse, Wis.",
    b"Lake Charles, La.",
    b"Lake Havasu, Ariz.",
    b"Lakehurst, N.J.",
    b"Lake Tahoe",
    b"Lander, Wyo.",
    b"Lansing, Mich.",
    b"Las Vegas, Nev.",
    b"Lawton, Okla.",
    b"Lemoore, Calif.",
    b"Rehoboth Beach, Del.",
    b"Lewiston, Idaho",
    b"Lexington, Ky.",
    b"Lexington Park, Md.",
    b"Lihue, Hawaii",
    b"Lincoln, Neb.",
    b"Little Rock, Ark.",
    b"Long Beach, Calif.",
    b"Los Angeles, Calif.",
    b"Louisville, Ky.",
    b"Lubbock, Texas",
    b"Lynchburg, Va.",
    b"Macon, Ga.",
    b"Madison, Wis.",
    b"Mansfield, Ohio",
    b"Marquette, Mich.",
    b"Mascoutah, Ill.",
    b"Medford, Ore.",
    b"Melbourne, Fla.",
    b"Memphis, Tenn.",
    b"Meridian, Miss.",
    b"Miami, Fla.",
    b"Miles City, Mont.",
    b"Milford, Utah",
    b"Milwaukee, Wis.",
    b"St. Paul, Minn.",
    b"Minneapolis",
    b"Minot, N.D.",
    b"Missoula, Mont.",
    b"Mobile, Ala.",
    b"Moline, Ill.",
    b"Monterey, Calif.",
    b"Montgomery, Ala.",
    b"Moses Lake, Wash.",
    b"Muskegon, Mich.",
    b"Myrtle Beach, S.C.",
    b"Nantucket, Mass.",
    b"Nashville, Tenn.",
    b"New Bern, N.C.",
    b"New Orleans, La.",
    b"Newport, R.I.",
    b"New York, N.Y.",
    b"Nome, Alaska",
    b"Norfolk, Neb.",
    b"Norfolk, Va.",
    b"North Platte, Neb.",
    b"Oakland, Calif.",
    b"Ocean City, Md.",
    b"Oceanside, Calif.",
    b"Ogden, Utah",
    b"Oklahoma City, Okla.",
    b"Orlando, Fla.",
    b"Olympia, Wash.",
    b"Omaha, Neb.",
    b"Ontario, Calif.",
    b"Oxnard, Calif.",
    b"Paducah, Ky.",
    b"Palm Springs, Calif.",
    b"Panama City, Fla.",
    b"Parkersburg, W.Va.",
    b"Pendleton, Ore.",
    b"Pensacola, Fla.",
    b"Peoria, Ill.",
    b"Peru, Ind.",
    b"Philadelphia, Pa.",
    b"Phoenix, Ariz.",
    b"Pittsburgh, Pa.",
    b"Pocatello, Idaho",
    b"Port Angeles, Wash.",
    b"Portland, Maine",
    b"Portland, Ore.",
    b"Portsmouth, N.H.",
    b"Providence, R.I.",
    b"Cape Cod, Mass.",
    b"Pueblo, Colo.",
    b"Quantico, Va.",
    b"Quillayute, Wash.",
    b"Raleigh, N.C.",
    b"Rapid City, S.D.",
    b"Red Bluff, Calif.",
    b"Redding, Calif.",
    b"Richmond, Va.",
    b"Ridgecrest, Calif.",
    b"Roanoke, Va.",
    b"Rochester, Minn.",
    b"Rochester, N.Y.",
    b"Rockford, Ill.",
    b"Utica, N.Y.",
    b"Roswell, N.M.",
    b"Sacramento, Calif.",
    b"St. Cloud, Minn.",
    b"St. George, Utah",
    b"St. Joseph, Mo.",
    b"St. Louis, Mo.",
    b"St. Robert, Mo.",
    b"Salt Lake City, Utah",
    b"Salem, Ore.",
    b"San Angelo, Texas",
    b"San Antonio, Texas",
    b"San Diego, Calif.",
    b"San Francisco, Calif.",
    b"Santa Barbara, Calif.",
    b"Santa Maria, Calif.",
    b"Savannah, Ga.",
    b"Scottsbluff, Neb.",
    b"Seattle, Wash.",
    b"Tacoma, Wash.",
    b"Sheridan, Wyo.",
    b"Shreveport, La.",
    b"Sioux City, Iowa",
    b"Sioux Falls, S.D.",
    b"South Bend, Ind.",
    b"Spokane, Wash.",
    b"Springfield, Ill.",
    b"Springfield, Mass.",
    b"Springfield, Mo.",
    b"Sterling, Va.",
    b"Stockbridge, Mass.",
    b"Stockton, Calif.",
    b"Sumter, S.C.",
    b"Sun Valley, Idaho",
    b"Syracuse, N.Y.",
    b"Tallahassee, Fla.",
    b"Tampa, Fla.",
    b"St. Petersburg, Fla.",
    b"Taos, N.M.",
    b"Toledo, Ohio",
    b"Topeka, Kan.",
    b"Tucson, Ariz.",
    b"Tupelo, Miss.",
    b"Valdosta, Ga.",
    b"Valentine, Neb.",
    b"Vero Beach, Fla.",
    b"Victoria, Texas",
    b"Virginia Beach, Va.",
    b"Walla Walla, Wash.",
    b"Waco, Texas",
    b"Washington, D.C.",
    b"Waterloo, Iowa",
    b"Watertown, N.Y.",
    b"Wendover, Utah",
    b"West Palm Beach, Fla.",
    b"Whidbey Island, Wash.",
    b"Wichita, Kan.",
    b"Wichita Falls, Texas",
    b"Williamsport, Pa.",
    b"Williston, N.D.",
    b"Scranton, Pa.",
    b"Wilmington, Del.",
    b"Wilmington, N.C.",
    b"Winnemucca, Nev.",
    b"Winslow, Ariz.",
    b"Worcester, Mass.",
    b"Yakima, Wash.",
    b"Youngstown, Ohio",
    b"Yuma, Ariz.",
    b"Muncie, Ind",
    b"McLean, Va.",
    b"Issaquah, Wash.",
    b"Pasadena, Calif.",
    b"Walnut Creek, Calif.",
    b"Moscow, Russia",
    b"London, England",
    b"Berlin, Germany",
    b"Madrid, Spain",
    b"Rome, Italy",
    b"Kiev, Ukraine",
    b"Paris, France",
    b"Budapest, Hungary",
    b"Hamburg, Germany",
    b"Warsaw, Poland",
    b"Wembley Park, England",
    b"Kilburn, England",
    b"Milan, Italy",
    b"Barcelona, Spain",
    b"Munich, Germany",
    b"Naples, Italy",
    b"Florence, Italy",
    b"Riga, Latvia",
    b"Leeds, England",
    b"Staines, Westside",
    b"Omsk, Russia",
    b"Tooting, England",
    b"North Pole, Alaska",
    b"Why, Ariz.",
    b"Lorida, Fla.",
    b"Experiment, Ga.",
    b"Normal, Ill.",
    b"Dwarf, Ky.",
    b"Hippo, Ky.",
    b"Humptulips, Wash.",
    b"Walla Walla, Wash.",
    b"Bigfoot, Texas",
    b"Happy, Texas",
    b"Bird-in-Hand, Pa.",
    b"Businessburg, Ohio",
    b"Watford, England",
    b"Loch Ness, Scotland",
    b"Lake Titicaca, Peru",
    b"Puddledock, England",
    b"Little Snoring, U.K.",
    b"Yelling, U.K.",
    b"Crackpot, U.K.",
    b"Great Snoring, U.K.",
    b"High Ham, U.K.",
    b"Giggleswick, U.K.",
    b"Shiner, Texas",
    b"Why, Ariz.",
    b"Hasty, Colo.",
    b"Protection, Kan.",
    b"Moon, Ky.",
    b"Trout, La.",
    b"Weed, N.M.",
    b"Hopton Wafers, U.K.",
    b"Abu Dhabi",
    b"Middle Wallop, U.K.",
    b"Tokyo, Japan",
    b"Easter Island",
    b"Bermuda Triangle",
    b"Mars",
    b"The White House, D.C.",
    b"Wapping, U.K.",
];

/// `PTR_s_Knitting_005dfee8` (@ 005dfee8): hobbies.
pub static PTR_s_Knitting_005dfee8: [&[u8]; 331] = [
    b"Knitting",
    b"Painting",
    b"Woodworking",
    b"Antiques",
    b"Comic books",
    b"Dumpster Diving",
    b"Records",
    b"Collecting Stamps",
    b"Trading cards",
    b"Smooth Jazz",
    b"Board Games",
    b"Card Games",
    b"Historical Reenactment",
    b"Rafting",
    b"Photography",
    b"Baseball",
    b"Bowling",
    b"Curling",
    b"Live Action Role-playing",
    b"Mountain Biking",
    b"Hang Gliding",
    b"Flying Ultralites",
    b"Digeridooing",
    b"Lottery Scratch-offs",
    b"Samurai Swords",
    b"Muscle Cars",
    b"Mushroom Hunting",
    b"Flossing",
    b"Whiffleball",
    b"Stargazing",
    b"Tie-dying",
    b"Kitchen Remodeling",
    b"Mastiff Breeding",
    b"Ornithology",
    b"Mancala",
    b"Backgammon",
    b"Techno",
    b"Corporate Law",
    b"The Occult",
    b"Videogames",
    b"Gangsta Rap",
    b"Poetry",
    b"Wine Collecting",
    b"Drag Racing",
    b"Euchre",
    b"Hoe-downs",
    b"Jogging",
    b"Breakdancing",
    b"Fashion",
    b"Swimming",
    b"Line Dancing",
    b"Mountaineering",
    b"Tennis",
    b"Staring",
    b"Skiing",
    b"Algebra",
    b"Golf",
    b"Power Walking",
    b"High Explosives",
    b"Blogging",
    b"Pina Coladas",
    b"WWII Memorabilia",
    b"Online Chat",
    b"Fundraising",
    b"Yoga",
    b"Coffee",
    b"Fresh Fruit",
    b"Salsa Dancing",
    b"Improv Comedy",
    b"Musicals",
    b"Wine Tasting",
    b"Weekend Getaways",
    b"Bejeweled",
    b"Zuma",
    b"Bookworm",
    b"Particle Physics",
    b"Journalism",
    b"Tearjerkers",
    b"Foreign Cinema",
    b"Spaceships",
    b"Nanotechnology",
    b"Leather Pants",
    b"Country Music",
    b"Grunge",
    b"Styling Hair",
    b"Ham Radio",
    b"Fire Eating",
    b"Window Tinting",
    b"Bobsledding",
    b"Glass Etching",
    b"Poppies",
    b"Glass Blowing",
    b"Pottery",
    b"Church Choir",
    b"Spooning",
    b"Gorgonzola",
    b"Jam Bands",
    b"Aggressive Skating",
    b"Fire Walking",
    b"20 Inch Rims",
    b"Tricked Out Rides",
    b"Poll Volunteering",
    b"Indie Films",
    b"Hair Bands",
    b"Digital Cable",
    b"HDTV",
    b"Spelling Bees",
    b"Combines",
    b"Food Fights",
    b"Beans",
    b"Extreme Sports",
    b"Riddles",
    b"Knock-Knock Jokes",
    b"Trampolines",
    b"Low Carbin'",
    b"Broadway Show Tunes",
    b"The Lambada",
    b"Car Repair",
    b"Garage Sales",
    b"Rubber Bands",
    b"Number 2 Pencils",
    b"Skim Milk",
    b"Avoiding Sharks",
    b"Collecting Tea Bags",
    b"Tap Dancing",
    b"Vaudeville",
    b"Denver Omelets",
    b"Basket Weaving",
    b"Kung Fu Movies",
    b"Debating",
    b"Bargain Hunting",
    b"Avoiding Hooks",
    b"Train spotting",
    b"Hot-tubbing",
    b"Hide and Seek",
    b"Local Politics",
    b"General Insanity",
    b"Antique Weapon Collecting",
    b"Finger Painting",
    b"Underwater Cartography",
    b"Seismology",
    b"Antique Car Restoration",
    b"Blenders",
    b"Skydiving",
    b"Paintball",
    b"Long Walks in the Park",
    b"Sushi",
    b"Company Picnics",
    b"Filling Out Forms",
    b"Meteorology",
    b"Baking Cookies",
    b"Billiards",
    b"Soy Sauce",
    b"Bubbles",
    b"Trampolines",
    b"Pirates",
    b"Ninjas",
    b"Robots",
    b"Candy",
    b"Camping",
    b"Foreign Languages",
    b"Clipping Coupons",
    b"Swashbuckling",
    b"Lumberjacks",
    b"Entomology",
    b"Weed Whacking",
    b"Power Washers",
    b"Working Out",
    b"The Pacific Northwest",
    b"Thrift Stores",
    b"Monorails",
    b"Recycling",
    b"Beta Testing",
    b"Fondue Parties",
    b"Ladies Nights",
    b"Infomercials",
    b"Hippies",
    b"Practical Jokes",
    b"College Parties",
    b"Soccer Hooligans",
    b"Yakisoba",
    b"Welding",
    b"Ice Sculpting",
    b"Vibraphones",
    b"Anime",
    b"MP3 Players",
    b"Fingerless Gloves",
    b"Fireside Chats",
    b"Horseback Riding",
    b"Working with Animals",
    b"Whittling",
    b"Oil Painting",
    b"Macrame",
    b"Sun Tanning",
    b"Wakeboarding",
    b"World Music",
    b"Travel",
    b"Horse Racing",
    b"Sports Books",
    b"Hockey",
    b"Violin",
    b"Crochet",
    b"Sewing",
    b"Spelunking",
    b"Lizards",
    b"Street Fighting",
    b"Jigsaws",
    b"Jujitsu",
    b"Lard",
    b"Pumping Iron",
    b"Body Massage",
    b"Stuffed Animals",
    b"Stickers",
    b"Glitter Glue",
    b"Hot Dogs",
    b"Pancakes",
    b"Pork Chops",
    b"Muffins",
    b"Fencing",
    b"Dental Visits",
    b"Fireworks",
    b"Skipping",
    b"Glubbing",
    b"Beekeeping",
    b"Haggis",
    b"Cheese Sculpture",
    b"Shampoo",
    b"Cubicles",
    b"Bits of String",
    b"Wood",
    b"Telling Jokes",
    b"Making Toast",
    b"Counting to 10",
    b"Pillow Fights",
    b"Chili Cheese Omelets",
    b"Kung Fu",
    b"Karate",
    b"Boxing",
    b"Phone Phreaking",
    b"Hacking",
    b"Chemistry",
    b"Karaoke",
    b"Heavy Metal",
    b"Ballet",
    b"Casual Fridays",
    b"Bejeweled 2",
    b"The Stock Market",
    b"Telecommuting",
    b"Buddhism",
    b"Vegan Cuisine",
    b"TV Dinners",
    b"Romantic Comedies",
    b"Hearts",
    b"Spades",
    b"Yogic Flying",
    b"Beach Workouts",
    b"Collecting Shells",
    b"Quantum Physics",
    b"Pickling Vegetables",
    b"Double Dipping",
    b"Ichthyology",
    b"Doomsday Cults",
    b"80s Arcade Games",
    b"True Crime Novels",
    b"New Wave Music",
    b"Bingo",
    b"Breeding Pugs",
    b"Dog Shows",
    b"Flossing",
    b"Moonlighting",
    b"Asian Culture",
    b"The GOP",
    b"Libertarians",
    b"Tai Chi",
    b"Lip Balm",
    b"Smoking Cigars",
    b"Reality TV",
    b"Haikus",
    b"Lumbar Support",
    b"Community Theater",
    b"Organ Music",
    b"Online Auctions",
    b"Chili Cook-offs",
    b"MMORPGs",
    b"Fighting Terrorism",
    b"Reggae",
    b"Hog Roasts",
    b"Tooth Necklaces",
    b"Making Omelets",
    b"Greasy Spoon Fare",
    b"Port Hopping",
    b"Raking Gravel",
    b"Making Jerky",
    b"Smoking Bacon",
    b"Grilling Veggies",
    b"Bar Crawling",
    b"Wine Tasting",
    b"Picketing",
    b"Renaissance Faires",
    b"Yachting",
    b"Shopping for shoes",
    b"Norse Mythology",
    b"Strategy Gaming",
    b"Glockenspiels",
    b"Stock Car Racing",
    b"Old Game Shows",
    b"Tetherball",
    b"Four Square",
    b"Sleight of Hand",
    b"Mandarin Cooking",
    b"Hospital Corners",
    b"Truffle Hunting",
    b"Paintball",
    b"Daytime TV",
    b"Old 45s",
    b"Haunted Houses",
    b"Fixing Flats",
    b"Public Transit",
    b"GPS Games",
    b"Hiking Rainier",
    b"Cancer Research",
    b"Woodburning Stoves",
    b"Chimney Sweeping",
    b"Telemarketers",
    b"Moonlit Walks",
    b"Value Menus",
    b"Combo Meals",
    b"Keeping it Real",
    b"Clicking Like Crazy",
    b"Bling Bling",
    b"Romance Novels",
];
