// @generated by tools/gen_res.py from the Extract*Resources functions in winfish.sqlite.
// Do not edit by hand.

use crate::sexy::prelude::*;
use crate::sexy::resource_manager::{get_font, get_image, get_sound};

/// port: 00506ea0 FUN_00506ea0
/// `Extract...Resources(ResourceManager*)`: binds 14 resource globals. A missing
/// resource makes the original throw `ResourceManagerException`, which it catches and
/// returns false; here the lookup returns false the same way.
pub fn FUN_00506ea0(g: &mut G) -> bool {
    g.globals.DAT_005e8f17 = true;
    g.res.DAT_005e8cf0 = get_font(g, "FONT_JUNGLEFEVER10OUTLINE");
    if g.res.DAT_005e8cf0 == NULL {
        return false;
    }
    g.res.DAT_005e8e40 = get_font(g, "FONT_JUNGLEFEVER17OUTLINE");
    if g.res.DAT_005e8e40 == NULL {
        return false;
    }
    g.res.DAT_005e8d80 = get_image(g, "IMAGE_BLANK");
    if g.res.DAT_005e8d80 == NULL {
        return false;
    }
    g.res.DAT_005e8a80 = get_image(g, "IMAGE_CURSOR_DRAGGING");
    if g.res.DAT_005e8a80 == NULL {
        return false;
    }
    g.res.DAT_005e8e20 = get_image(g, "IMAGE_CURSOR_HAND");
    if g.res.DAT_005e8e20 == NULL {
        return false;
    }
    g.res.DAT_005e8a4c = get_image(g, "IMAGE_CURSOR_POINTER");
    if g.res.DAT_005e8a4c == NULL {
        return false;
    }
    g.res.DAT_005e8b50 = get_image(g, "IMAGE_CURSOR_TEXT");
    if g.res.DAT_005e8b50 == NULL {
        return false;
    }
    g.res.DAT_005e8b00 = get_image(g, "IMAGE_LOADERBAR");
    if g.res.DAT_005e8b00 == NULL {
        return false;
    }
    g.res.DAT_005e8f10 = get_image(g, "IMAGE_LOADERBARLOADING");
    if g.res.DAT_005e8f10 == NULL {
        return false;
    }
    g.res.DAT_005e8c30 = get_image(g, "IMAGE_LOADERBAROVER");
    if g.res.DAT_005e8c30 == NULL {
        return false;
    }
    g.res.DAT_005e8d6c = get_image(g, "IMAGE_LOADERPLAY");
    if g.res.DAT_005e8d6c == NULL {
        return false;
    }
    g.res.DAT_005e8bec = get_image(g, "IMAGE_TITLEPAGE");
    if g.res.DAT_005e8bec == NULL {
        return false;
    }
    g.res.DAT_005e8e80 = get_image(g, "IMAGE_TITLEPAGEMASK");
    if g.res.DAT_005e8e80 == NULL {
        return false;
    }
    g.res.DAT_005e8c40 = get_sound(g, "SOUND_BUTTONCLICK");
    if g.res.DAT_005e8c40 == -1 {
        return false;
    }
    true
}

/// port: 005073e0 FUN_005073e0
/// `Extract...Resources(ResourceManager*)`: binds 296 resource globals. A missing
/// resource makes the original throw `ResourceManagerException`, which it catches and
/// returns false; here the lookup returns false the same way.
pub fn FUN_005073e0(g: &mut G) -> bool {
    g.globals.DAT_005e8f17 = true;
    g.res.DAT_005e8a64 = get_image(g, "IMAGE_AA_BEAM");
    if g.res.DAT_005e8a64 == NULL {
        return false;
    }
    g.res.DAT_005e8b90 = get_image(g, "IMAGE_AA_BOTTOM");
    if g.res.DAT_005e8b90 == NULL {
        return false;
    }
    g.res.DAT_005e8d90 = get_image(g, "IMAGE_AA_GLOW");
    if g.res.DAT_005e8d90 == NULL {
        return false;
    }
    g.res.DAT_005e8c68 = get_image(g, "IMAGE_AA_STORE");
    if g.res.DAT_005e8c68 == NULL {
        return false;
    }
    g.res.DAT_005e8cfc = get_image(g, "IMAGE_AA_TOP1");
    if g.res.DAT_005e8cfc == NULL {
        return false;
    }
    g.res.DAT_005e8b8c = get_image(g, "IMAGE_AA_TOP2");
    if g.res.DAT_005e8b8c == NULL {
        return false;
    }
    g.res.DAT_005e8de8 = get_image(g, "IMAGE_AMP");
    if g.res.DAT_005e8de8 == NULL {
        return false;
    }
    g.res.DAT_005e8ce8 = get_image(g, "IMAGE_AMPCHARGE");
    if g.res.DAT_005e8ce8 == NULL {
        return false;
    }
    g.res.DAT_005e8e8c = get_image(g, "IMAGE_ANGIE");
    if g.res.DAT_005e8e8c == NULL {
        return false;
    }
    g.res.DAT_005e8b70 = get_image(g, "IMAGE_AQUARIUM1");
    if g.res.DAT_005e8b70 == NULL {
        return false;
    }
    g.res.DAT_005e8c04 = get_image(g, "IMAGE_AQUARIUM2");
    if g.res.DAT_005e8c04 == NULL {
        return false;
    }
    g.res.DAT_005e8d50 = get_image(g, "IMAGE_AQUARIUM3");
    if g.res.DAT_005e8d50 == NULL {
        return false;
    }
    g.res.DAT_005e8adc = get_image(g, "IMAGE_AQUARIUM4");
    if g.res.DAT_005e8adc == NULL {
        return false;
    }
    g.res.DAT_005e8be8 = get_image(g, "IMAGE_AQUARIUM5");
    if g.res.DAT_005e8be8 == NULL {
        return false;
    }
    g.res.DAT_005e8db8 = get_image(g, "IMAGE_AQUARIUM6");
    if g.res.DAT_005e8db8 == NULL {
        return false;
    }
    g.res.DAT_005e8ee8 = get_image(g, "IMAGE_BALLS");
    if g.res.DAT_005e8ee8 == NULL {
        return false;
    }
    g.res.DAT_005e8cec = get_image(g, "IMAGE_BALROG");
    if g.res.DAT_005e8cec == NULL {
        return false;
    }
    g.res.DAT_005e8cf8 = get_image(g, "IMAGE_BATTLETANKBUTTON");
    if g.res.DAT_005e8cf8 == NULL {
        return false;
    }
    g.res.DAT_005e8e00 = get_image(g, "IMAGE_BATTLETANKBUTTOND");
    if g.res.DAT_005e8e00 == NULL {
        return false;
    }
    g.res.DAT_005e8f00 = get_image(g, "IMAGE_BILATERUS");
    if g.res.DAT_005e8f00 == NULL {
        return false;
    }
    g.res.DAT_005e8a14 = get_image(g, "IMAGE_BLIP");
    if g.res.DAT_005e8a14 == NULL {
        return false;
    }
    g.res.DAT_005e8b18 = get_image(g, "IMAGE_BOLT");
    if g.res.DAT_005e8b18 == NULL {
        return false;
    }
    g.res.DAT_005e8bb8 = get_image(g, "IMAGE_BONUS1");
    if g.res.DAT_005e8bb8 == NULL {
        return false;
    }
    g.res.DAT_005e8ab0 = get_image(g, "IMAGE_BONUS2");
    if g.res.DAT_005e8ab0 == NULL {
        return false;
    }
    g.res.DAT_005e8dd8 = get_image(g, "IMAGE_BONUS3");
    if g.res.DAT_005e8dd8 == NULL {
        return false;
    }
    g.res.DAT_005e8ea0 = get_image(g, "IMAGE_BONUSAWARD");
    if g.res.DAT_005e8ea0 == NULL {
        return false;
    }
    g.res.DAT_005e8dd4 = get_image(g, "IMAGE_BONUSAWARD2");
    if g.res.DAT_005e8dd4 == NULL {
        return false;
    }
    g.res.DAT_005e8cc4 = get_image(g, "IMAGE_BONUSBUCKET");
    if g.res.DAT_005e8cc4 == NULL {
        return false;
    }
    g.res.DAT_005e8a04 = get_image(g, "IMAGE_BONUSBUTTONOVERLAY");
    if g.res.DAT_005e8a04 == NULL {
        return false;
    }
    g.res.DAT_005e8cb8 = get_image(g, "IMAGE_BOSS");
    if g.res.DAT_005e8cb8 == NULL {
        return false;
    }
    g.res.DAT_005e8d4c = get_image(g, "IMAGE_BREEDER");
    if g.res.DAT_005e8d4c == NULL {
        return false;
    }
    g.res.DAT_005e8b4c = get_image(g, "IMAGE_BRINKLEY");
    if g.res.DAT_005e8b4c == NULL {
        return false;
    }
    g.res.DAT_005e8c84 = get_image(g, "IMAGE_BUBBLES");
    if g.res.DAT_005e8c84 == NULL {
        return false;
    }
    g.res.DAT_005e8d70 = get_image(g, "IMAGE_BUBBULATOR");
    if g.res.DAT_005e8d70 == NULL {
        return false;
    }
    g.res.DAT_005e8c80 = get_image(g, "IMAGE_BUBBULATOR_STORE");
    if g.res.DAT_005e8c80 == NULL {
        return false;
    }
    g.res.DAT_005e8d28 = get_image(g, "IMAGE_CENTERBUTTON");
    if g.res.DAT_005e8d28 == NULL {
        return false;
    }
    g.res.DAT_005e8c64 = get_image(g, "IMAGE_CHECKED");
    if g.res.DAT_005e8c64 == NULL {
        return false;
    }
    g.res.DAT_005e8b64 = get_image(g, "IMAGE_CHICKEN");
    if g.res.DAT_005e8b64 == NULL {
        return false;
    }
    g.res.DAT_005e8a34 = get_image(g, "IMAGE_CHOMP");
    if g.res.DAT_005e8a34 == NULL {
        return false;
    }
    g.res.DAT_005e8bd0 = get_image(g, "IMAGE_CLYDE");
    if g.res.DAT_005e8bd0 == NULL {
        return false;
    }
    g.res.DAT_005e8e1c = get_image(g, "IMAGE_CROSSHAIR");
    if g.res.DAT_005e8e1c == NULL {
        return false;
    }
    g.res.DAT_005e8ec8 = get_image(g, "IMAGE_DESTRUCTOR");
    if g.res.DAT_005e8ec8 == NULL {
        return false;
    }
    g.res.DAT_005e8cac = get_image(g, "IMAGE_EGGBRINKLEY");
    if g.res.DAT_005e8cac == NULL {
        return false;
    }
    g.res.DAT_005e8c74 = get_image(g, "IMAGE_EGGCRACK1");
    if g.res.DAT_005e8c74 == NULL {
        return false;
    }
    g.res.DAT_005e8ca8 = get_image(g, "IMAGE_EGGCRACK2");
    if g.res.DAT_005e8ca8 == NULL {
        return false;
    }
    g.res.DAT_005e8ee4 = get_image(g, "IMAGE_EGGNOSTRADAMUS");
    if g.res.DAT_005e8ee4 == NULL {
        return false;
    }
    g.res.DAT_005e8c00 = get_image(g, "IMAGE_EGGPIECES");
    if g.res.DAT_005e8c00 == NULL {
        return false;
    }
    g.res.DAT_005e8a24 = get_image(g, "IMAGE_EGGSHARDS");
    if g.res.DAT_005e8a24 == NULL {
        return false;
    }
    g.res.DAT_005e8d68 = get_image(g, "IMAGE_EGGSTANLEY");
    if g.res.DAT_005e8d68 == NULL {
        return false;
    }
    g.res.DAT_005e8db0 = get_image(g, "IMAGE_EGGWALTER");
    if g.res.DAT_005e8db0 == NULL {
        return false;
    }
    g.res.DAT_005e8a44 = get_image(g, "IMAGE_ENERGYBALL");
    if g.res.DAT_005e8a44 == NULL {
        return false;
    }
    g.res.DAT_005e8d40 = get_image(g, "IMAGE_EXPLOSION");
    if g.res.DAT_005e8d40 == NULL {
        return false;
    }
    g.res.DAT_005e8ef0 = get_image(g, "IMAGE_EXPLOSIONSMALL");
    if g.res.DAT_005e8ef0 == NULL {
        return false;
    }
    g.res.DAT_005e8df4 = get_image(g, "IMAGE_EXPLOSIONTINY");
    if g.res.DAT_005e8df4 == NULL {
        return false;
    }
    g.res.DAT_005e8ed8 = get_image(g, "IMAGE_FATBUTTON");
    if g.res.DAT_005e8ed8 == NULL {
        return false;
    }
    g.res.DAT_005e8c58 = get_image(g, "IMAGE_FISHBOX");
    if g.res.DAT_005e8c58 == NULL {
        return false;
    }
    g.res.DAT_005e8e7c = get_image(g, "IMAGE_FISHBOXBUTTON");
    if g.res.DAT_005e8e7c == NULL {
        return false;
    }
    g.res.DAT_005e8aa0 = get_image(g, "IMAGE_FOOD");
    if g.res.DAT_005e8aa0 == NULL {
        return false;
    }
    g.res.DAT_005e8bfc = get_image(g, "IMAGE_GASH");
    if g.res.DAT_005e8bfc == NULL {
        return false;
    }
    g.res.DAT_005e8da8 = get_image(g, "IMAGE_GEKKO");
    if g.res.DAT_005e8da8 == NULL {
        return false;
    }
    g.res.DAT_005e8c98 = get_image(g, "IMAGE_GRUBBER");
    if g.res.DAT_005e8c98 == NULL {
        return false;
    }
    g.res.DAT_005e8cb4 = get_image(g, "IMAGE_GUMBO");
    if g.res.DAT_005e8cb4 == NULL {
        return false;
    }
    g.res.DAT_005e8bcc = get_image(g, "IMAGE_GUMBOLIGHT");
    if g.res.DAT_005e8bcc == NULL {
        return false;
    }
    g.res.DAT_005e8ae4 = get_image(g, "IMAGE_GUS");
    if g.res.DAT_005e8ae4 == NULL {
        return false;
    }
    g.res.DAT_005e8c7c = get_image(g, "IMAGE_HALO");
    if g.res.DAT_005e8c7c == NULL {
        return false;
    }
    g.res.DAT_005e8a78 = get_image(g, "IMAGE_HATCHANIMATION");
    if g.res.DAT_005e8a78 == NULL {
        return false;
    }
    g.res.DAT_005e8bf4 = get_image(g, "IMAGE_HATCHREFLECTION");
    if g.res.DAT_005e8bf4 == NULL {
        return false;
    }
    g.res.DAT_005e8ab4 = get_image(g, "IMAGE_HATCHSCREEN");
    if g.res.DAT_005e8ab4 == NULL {
        return false;
    }
    g.res.DAT_005e8e3c = get_image(g, "IMAGE_HEALTHBAR");
    if g.res.DAT_005e8e3c == NULL {
        return false;
    }
    g.res.DAT_005e8eb8 = get_image(g, "IMAGE_HEALTHBARTUBE");
    if g.res.DAT_005e8eb8 == NULL {
        return false;
    }
    g.res.DAT_005e8ca4 = get_image(g, "IMAGE_HELPALIEN");
    if g.res.DAT_005e8ca4 == NULL {
        return false;
    }
    g.res.DAT_005e8a6c = get_image(g, "IMAGE_HELPARROW");
    if g.res.DAT_005e8a6c == NULL {
        return false;
    }
    g.res.DAT_005e8b34 = get_image(g, "IMAGE_HELPPETCHOOSE");
    if g.res.DAT_005e8b34 == NULL {
        return false;
    }
    g.res.DAT_005e8a1c = get_image(g, "IMAGE_HELPSCREENSAVER");
    if g.res.DAT_005e8a1c == NULL {
        return false;
    }
    g.res.DAT_005e8b74 = get_image(g, "IMAGE_HELPSHELL");
    if g.res.DAT_005e8b74 == NULL {
        return false;
    }
    g.res.DAT_005e8a58 = get_image(g, "IMAGE_HORZCREASE");
    if g.res.DAT_005e8a58 == NULL {
        return false;
    }
    g.res.DAT_005e8dc4 = get_image(g, "IMAGE_HUNGRYBREEDER");
    if g.res.DAT_005e8dc4 == NULL {
        return false;
    }
    g.res.DAT_005e8ecc = get_image(g, "IMAGE_HUNGRYEAT");
    if g.res.DAT_005e8ecc == NULL {
        return false;
    }
    g.res.DAT_005e8e48 = get_image(g, "IMAGE_HUNGRYSWIM");
    if g.res.DAT_005e8e48 == NULL {
        return false;
    }
    g.res.DAT_005e8e88 = get_image(g, "IMAGE_HUNGRYTURN");
    if g.res.DAT_005e8e88 == NULL {
        return false;
    }
    g.res.DAT_005e8e0c = get_image(g, "IMAGE_ICECREAM");
    if g.res.DAT_005e8e0c == NULL {
        return false;
    }
    g.res.DAT_005e8aec = get_image(g, "IMAGE_ITCHY");
    if g.res.DAT_005e8aec == NULL {
        return false;
    }
    g.res.DAT_005e8e34 = get_image(g, "IMAGE_LASERS");
    if g.res.DAT_005e8e34 == NULL {
        return false;
    }
    g.res.DAT_005e8a10 = get_image(g, "IMAGE_LASERUPGRADES");
    if g.res.DAT_005e8a10 == NULL {
        return false;
    }
    g.res.DAT_005e8ad8 = get_image(g, "IMAGE_LEFTBUTTON");
    if g.res.DAT_005e8ad8 == NULL {
        return false;
    }
    g.res.DAT_005e8c1c = get_image(g, "IMAGE_MAINBUTTON");
    if g.res.DAT_005e8c1c == NULL {
        return false;
    }
    g.res.DAT_005e8b10 = get_image(g, "IMAGE_MENUBAR");
    if g.res.DAT_005e8b10 == NULL {
        return false;
    }
    g.res.DAT_005e8d64 = get_image(g, "IMAGE_MENUBTND");
    if g.res.DAT_005e8d64 == NULL {
        return false;
    }
    g.res.DAT_005e8eb4 = get_image(g, "IMAGE_MENUBTND2");
    if g.res.DAT_005e8eb4 == NULL {
        return false;
    }
    g.res.DAT_005e8e74 = get_image(g, "IMAGE_MENUBTNO");
    if g.res.DAT_005e8e74 == NULL {
        return false;
    }
    g.res.DAT_005e8c60 = get_image(g, "IMAGE_MENUBTNU");
    if g.res.DAT_005e8c60 == NULL {
        return false;
    }
    g.res.DAT_005e8e2c = get_image(g, "IMAGE_MENUBUTTONREFLECTION");
    if g.res.DAT_005e8e2c == NULL {
        return false;
    }
    g.res.DAT_005e8b08 = get_image(g, "IMAGE_MERYL");
    if g.res.DAT_005e8b08 == NULL {
        return false;
    }
    g.res.DAT_005e8ad4 = get_image(g, "IMAGE_MERYLBLINK");
    if g.res.DAT_005e8ad4 == NULL {
        return false;
    }
    g.res.DAT_005e8ddc = get_image(g, "IMAGE_MERYLLIPS");
    if g.res.DAT_005e8ddc == NULL {
        return false;
    }
    g.res.DAT_005e8a40 = get_image(g, "IMAGE_MERYLTAIL");
    if g.res.DAT_005e8a40 == NULL {
        return false;
    }
    g.res.DAT_005e8b88 = get_image(g, "IMAGE_MIDDLEBUTTON");
    if g.res.DAT_005e8b88 == NULL {
        return false;
    }
    g.res.DAT_005e8e9c = get_image(g, "IMAGE_MIDDLEBUTTOND");
    if g.res.DAT_005e8e9c == NULL {
        return false;
    }
    g.res.DAT_005e8c0c = get_image(g, "IMAGE_MINISYLV");
    if g.res.DAT_005e8c0c == NULL {
        return false;
    }
    g.res.DAT_005e8bc4 = get_image(g, "IMAGE_MISCITEMS");
    if g.res.DAT_005e8bc4 == NULL {
        return false;
    }
    g.res.DAT_005e8a2c = get_image(g, "IMAGE_MISSILE");
    if g.res.DAT_005e8a2c == NULL {
        return false;
    }
    g.res.DAT_005e8e60 = get_image(g, "IMAGE_MONEY");
    if g.res.DAT_005e8e60 == NULL {
        return false;
    }
    g.res.DAT_005e8d88 = get_image(g, "IMAGE_MONEYBAG");
    if g.res.DAT_005e8d88 == NULL {
        return false;
    }
    g.res.DAT_005e8e70 = get_image(g, "IMAGE_MONEYFLASH");
    if g.res.DAT_005e8e70 == NULL {
        return false;
    }
    g.res.DAT_005e8e44 = get_image(g, "IMAGE_NIKO");
    if g.res.DAT_005e8e44 == NULL {
        return false;
    }
    g.res.DAT_005e8aac = get_image(g, "IMAGE_NIKOTOWER");
    if g.res.DAT_005e8aac == NULL {
        return false;
    }
    g.res.DAT_005e8a08 = get_image(g, "IMAGE_NIMBUS");
    if g.res.DAT_005e8a08 == NULL {
        return false;
    }
    g.res.DAT_005e8ed4 = get_image(g, "IMAGE_NOSTRADAMUS");
    if g.res.DAT_005e8ed4 == NULL {
        return false;
    }
    g.res.DAT_005e8c94 = get_image(g, "IMAGE_OPTIONSBUTTON");
    if g.res.DAT_005e8c94 == NULL {
        return false;
    }
    g.res.DAT_005e8a20 = get_image(g, "IMAGE_OPTIONSBUTTOND");
    if g.res.DAT_005e8a20 == NULL {
        return false;
    }
    g.res.DAT_005e8c50 = get_image(g, "IMAGE_PEANUT");
    if g.res.DAT_005e8c50 == NULL {
        return false;
    }
    g.res.DAT_005e8bd8 = get_image(g, "IMAGE_PEARL");
    if g.res.DAT_005e8bd8 == NULL {
        return false;
    }
    g.res.DAT_005e8a48 = get_image(g, "IMAGE_PETBTNO");
    if g.res.DAT_005e8a48 == NULL {
        return false;
    }
    g.res.DAT_005e8b84 = get_image(g, "IMAGE_PETBTNU");
    if g.res.DAT_005e8b84 == NULL {
        return false;
    }
    g.res.DAT_005e8e78 = get_image(g, "IMAGE_PETBUTTON");
    if g.res.DAT_005e8e78 == NULL {
        return false;
    }
    g.res.DAT_005e8e4c = get_image(g, "IMAGE_PETBUTTONHOLE");
    if g.res.DAT_005e8e4c == NULL {
        return false;
    }
    g.res.DAT_005e8a38 = get_image(g, "IMAGE_PETBUTTONREFLECT");
    if g.res.DAT_005e8a38 == NULL {
        return false;
    }
    g.res.DAT_005e8a88 = get_image(g, "IMAGE_PETBUTTONRING");
    if g.res.DAT_005e8a88 == NULL {
        return false;
    }
    g.res.DAT_005e8e38 = get_image(g, "IMAGE_PETLIMITEGG");
    if g.res.DAT_005e8e38 == NULL {
        return false;
    }
    g.res.DAT_005e8d0c = get_image(g, "IMAGE_PIZZA");
    if g.res.DAT_005e8d0c == NULL {
        return false;
    }
    g.res.DAT_005e8ca0 = get_image(g, "IMAGE_PREGO");
    if g.res.DAT_005e8ca0 == NULL {
        return false;
    }
    g.res.DAT_005e8d60 = get_image(g, "IMAGE_PRESTO");
    if g.res.DAT_005e8d60 == NULL {
        return false;
    }
    g.res.DAT_005e8c4c = get_image(g, "IMAGE_PSYCHOSQUID");
    if g.res.DAT_005e8c4c == NULL {
        return false;
    }
    g.res.DAT_005e8a98 = get_image(g, "IMAGE_RHUBARB");
    if g.res.DAT_005e8a98 == NULL {
        return false;
    }
    g.res.DAT_005e8dec = get_image(g, "IMAGE_RIGHTBUTTON");
    if g.res.DAT_005e8dec == NULL {
        return false;
    }
    g.res.DAT_005e8b60 = get_image(g, "IMAGE_RUFUS");
    if g.res.DAT_005e8b60 == NULL {
        return false;
    }
    g.res.DAT_005e8dfc = get_image(g, "IMAGE_SCL_AMP");
    if g.res.DAT_005e8dfc == NULL {
        return false;
    }
    g.res.DAT_005e8d30 = get_image(g, "IMAGE_SCL_ANGIE");
    if g.res.DAT_005e8d30 == NULL {
        return false;
    }
    g.res.DAT_005e8ccc = get_image(g, "IMAGE_SCL_BLIP");
    if g.res.DAT_005e8ccc == NULL {
        return false;
    }
    g.res.DAT_005e8c90 = get_image(g, "IMAGE_SCL_BREEDER");
    if g.res.DAT_005e8c90 == NULL {
        return false;
    }
    g.res.DAT_005e8ae0 = get_image(g, "IMAGE_SCL_BRINKLEY");
    if g.res.DAT_005e8ae0 == NULL {
        return false;
    }
    g.res.DAT_005e8b2c = get_image(g, "IMAGE_SCL_CLYDE");
    if g.res.DAT_005e8b2c == NULL {
        return false;
    }
    g.res.DAT_005e8b7c = get_image(g, "IMAGE_SCL_GASH");
    if g.res.DAT_005e8b7c == NULL {
        return false;
    }
    g.res.DAT_005e8ce0 = get_image(g, "IMAGE_SCL_GEKKO");
    if g.res.DAT_005e8ce0 == NULL {
        return false;
    }
    g.res.DAT_005e8bac = get_image(g, "IMAGE_SCL_GRUBBER");
    if g.res.DAT_005e8bac == NULL {
        return false;
    }
    g.res.DAT_005e8b94 = get_image(g, "IMAGE_SCL_GUMBO");
    if g.res.DAT_005e8b94 == NULL {
        return false;
    }
    g.res.DAT_005e8cb0 = get_image(g, "IMAGE_SCL_ITCHY");
    if g.res.DAT_005e8cb0 == NULL {
        return false;
    }
    g.res.DAT_005e8bf0 = get_image(g, "IMAGE_SCL_MERYL");
    if g.res.DAT_005e8bf0 == NULL {
        return false;
    }
    g.res.DAT_005e8ed0 = get_image(g, "IMAGE_SCL_NIKO");
    if g.res.DAT_005e8ed0 == NULL {
        return false;
    }
    g.res.DAT_005e8d24 = get_image(g, "IMAGE_SCL_NIMBUS");
    if g.res.DAT_005e8d24 == NULL {
        return false;
    }
    g.res.DAT_005e8afc = get_image(g, "IMAGE_SCL_NOSTRADAMUS");
    if g.res.DAT_005e8afc == NULL {
        return false;
    }
    g.res.DAT_005e8b80 = get_image(g, "IMAGE_SCL_OSCAR");
    if g.res.DAT_005e8b80 == NULL {
        return false;
    }
    g.res.DAT_005e8ee0 = get_image(g, "IMAGE_SCL_PREGO");
    if g.res.DAT_005e8ee0 == NULL {
        return false;
    }
    g.res.DAT_005e8c88 = get_image(g, "IMAGE_SCL_PRESTO");
    if g.res.DAT_005e8c88 == NULL {
        return false;
    }
    g.res.DAT_005e8cdc = get_image(g, "IMAGE_SCL_RHUBARB");
    if g.res.DAT_005e8cdc == NULL {
        return false;
    }
    g.res.DAT_005e8eb0 = get_image(g, "IMAGE_SCL_RUFUS");
    if g.res.DAT_005e8eb0 == NULL {
        return false;
    }
    g.res.DAT_005e8db4 = get_image(g, "IMAGE_SCL_SEYMOUR");
    if g.res.DAT_005e8db4 == NULL {
        return false;
    }
    g.res.DAT_005e8dcc = get_image(g, "IMAGE_SCL_SHRAPNEL");
    if g.res.DAT_005e8dcc == NULL {
        return false;
    }
    g.res.DAT_005e8abc = get_image(g, "IMAGE_SCL_STANLEY");
    if g.res.DAT_005e8abc == NULL {
        return false;
    }
    g.res.DAT_005e8ac0 = get_image(g, "IMAGE_SCL_STARCATCHER");
    if g.res.DAT_005e8ac0 == NULL {
        return false;
    }
    g.res.DAT_005e8a84 = get_image(g, "IMAGE_SCL_STINKY");
    if g.res.DAT_005e8a84 == NULL {
        return false;
    }
    g.res.DAT_005e8dc8 = get_image(g, "IMAGE_SCL_ULTRA");
    if g.res.DAT_005e8dc8 == NULL {
        return false;
    }
    g.res.DAT_005e8ac8 = get_image(g, "IMAGE_SCL_VERT");
    if g.res.DAT_005e8ac8 == NULL {
        return false;
    }
    g.res.DAT_005e8a0c = get_image(g, "IMAGE_SCL_WADSWORTH");
    if g.res.DAT_005e8a0c == NULL {
        return false;
    }
    g.res.DAT_005e8a54 = get_image(g, "IMAGE_SCL_WALTER");
    if g.res.DAT_005e8a54 == NULL {
        return false;
    }
    g.res.DAT_005e8d20 = get_image(g, "IMAGE_SCL_ZORF");
    if g.res.DAT_005e8d20 == NULL {
        return false;
    }
    g.res.DAT_005e8c70 = get_image(g, "IMAGE_SCREENBACK");
    if g.res.DAT_005e8c70 == NULL {
        return false;
    }
    g.res.DAT_005e8d3c = get_image(g, "IMAGE_SCREENTITLE");
    if g.res.DAT_005e8d3c == NULL {
        return false;
    }
    g.res.DAT_005e8e6c = get_image(g, "IMAGE_SCREENTITLEHOLE");
    if g.res.DAT_005e8e6c == NULL {
        return false;
    }
    g.res.DAT_005e8ba8 = get_image(g, "IMAGE_SELECTORSCREEN");
    if g.res.DAT_005e8ba8 == NULL {
        return false;
    }
    g.res.DAT_005e8eac = get_image(g, "IMAGE_SELECTORSPEECHBUBBLE");
    if g.res.DAT_005e8eac == NULL {
        return false;
    }
    g.res.DAT_005e8b0c = get_image(g, "IMAGE_SEYMOUR");
    if g.res.DAT_005e8b0c == NULL {
        return false;
    }
    g.res.DAT_005e8da4 = get_image(g, "IMAGE_SHADOW");
    if g.res.DAT_005e8da4 == NULL {
        return false;
    }
    g.res.DAT_005e8d7c = get_image(g, "IMAGE_SHELLS");
    if g.res.DAT_005e8d7c == NULL {
        return false;
    }
    g.res.DAT_005e8c2c = get_image(g, "IMAGE_SHRAPNEL");
    if g.res.DAT_005e8c2c == NULL {
        return false;
    }
    g.res.DAT_005e8b48 = get_image(g, "IMAGE_SIMCARNIVORE");
    if g.res.DAT_005e8b48 == NULL {
        return false;
    }
    g.res.DAT_005e8c24 = get_image(g, "IMAGE_SIMEAT1");
    if g.res.DAT_005e8c24 == NULL {
        return false;
    }
    g.res.DAT_005e8b14 = get_image(g, "IMAGE_SIMEAT2");
    if g.res.DAT_005e8b14 == NULL {
        return false;
    }
    g.res.DAT_005e8bd4 = get_image(g, "IMAGE_SIMEAT3");
    if g.res.DAT_005e8bd4 == NULL {
        return false;
    }
    g.res.DAT_005e8b78 = get_image(g, "IMAGE_SIMSWIM1");
    if g.res.DAT_005e8b78 == NULL {
        return false;
    }
    g.res.DAT_005e8eec = get_image(g, "IMAGE_SIMSWIM2");
    if g.res.DAT_005e8eec == NULL {
        return false;
    }
    g.res.DAT_005e8efc = get_image(g, "IMAGE_SIMSWIM3");
    if g.res.DAT_005e8efc == NULL {
        return false;
    }
    g.res.DAT_005e8e08 = get_image(g, "IMAGE_SIMTURN1");
    if g.res.DAT_005e8e08 == NULL {
        return false;
    }
    g.res.DAT_005e8a00 = get_image(g, "IMAGE_SIMTURN2");
    if g.res.DAT_005e8a00 == NULL {
        return false;
    }
    g.res.DAT_005e8b54 = get_image(g, "IMAGE_SIMTURN3");
    if g.res.DAT_005e8b54 == NULL {
        return false;
    }
    g.res.DAT_005e8be4 = get_image(g, "IMAGE_SLIDERTHUMB");
    if g.res.DAT_005e8be4 == NULL {
        return false;
    }
    g.res.DAT_005e8cc8 = get_image(g, "IMAGE_SLIDERTRACK");
    if g.res.DAT_005e8cc8 == NULL {
        return false;
    }
    g.res.DAT_005e8aa8 = get_image(g, "IMAGE_SMALLDIE");
    if g.res.DAT_005e8aa8 == NULL {
        return false;
    }
    g.res.DAT_005e8ec0 = get_image(g, "IMAGE_SMALLEAT");
    if g.res.DAT_005e8ec0 == NULL {
        return false;
    }
    g.res.DAT_005e8ab8 = get_image(g, "IMAGE_SMALLSWIM");
    if g.res.DAT_005e8ab8 == NULL {
        return false;
    }
    g.res.DAT_005e8d84 = get_image(g, "IMAGE_SMALLTURN");
    if g.res.DAT_005e8d84 == NULL {
        return false;
    }
    g.res.DAT_005e8d58 = get_image(g, "IMAGE_SMOKEMISSILE");
    if g.res.DAT_005e8d58 == NULL {
        return false;
    }
    g.res.DAT_005e8bb0 = get_image(g, "IMAGE_SMOKESMALL");
    if g.res.DAT_005e8bb0 == NULL {
        return false;
    }
    g.res.DAT_005e8a90 = get_image(g, "IMAGE_SMOKETINY");
    if g.res.DAT_005e8a90 == NULL {
        return false;
    }
    g.res.DAT_005e8bb4 = get_image(g, "IMAGE_SPARKLE");
    if g.res.DAT_005e8bb4 == NULL {
        return false;
    }
    g.res.DAT_005e8d04 = get_image(g, "IMAGE_SPARKS");
    if g.res.DAT_005e8d04 == NULL {
        return false;
    }
    g.res.DAT_005e8c18 = get_image(g, "IMAGE_SPEECHBUBBLE");
    if g.res.DAT_005e8c18 == NULL {
        return false;
    }
    g.res.DAT_005e8d00 = get_image(g, "IMAGE_STANLEY");
    if g.res.DAT_005e8d00 == NULL {
        return false;
    }
    g.res.DAT_005e8e04 = get_image(g, "IMAGE_STARCATCHER");
    if g.res.DAT_005e8e04 == NULL {
        return false;
    }
    g.res.DAT_005e8be0 = get_image(g, "IMAGE_STINKY");
    if g.res.DAT_005e8be0 == NULL {
        return false;
    }
    g.res.DAT_005e8a60 = get_image(g, "IMAGE_STOREBACKDROPS");
    if g.res.DAT_005e8a60 == NULL {
        return false;
    }
    g.res.DAT_005e8c5c = get_image(g, "IMAGE_STORELEFTBUTTON");
    if g.res.DAT_005e8c5c == NULL {
        return false;
    }
    g.res.DAT_005e8d18 = get_image(g, "IMAGE_STORELEFTHILIGHT");
    if g.res.DAT_005e8d18 == NULL {
        return false;
    }
    g.res.DAT_005e8b3c = get_image(g, "IMAGE_STORERIGHTBUTTON");
    if g.res.DAT_005e8b3c == NULL {
        return false;
    }
    g.res.DAT_005e8b38 = get_image(g, "IMAGE_STORERIGHTHILIGHT");
    if g.res.DAT_005e8b38 == NULL {
        return false;
    }
    g.res.DAT_005e8cd8 = get_image(g, "IMAGE_STORESCREEN");
    if g.res.DAT_005e8cd8 == NULL {
        return false;
    }
    g.res.DAT_005e8c3c = get_image(g, "IMAGE_STORESHELL");
    if g.res.DAT_005e8c3c == NULL {
        return false;
    }
    g.res.DAT_005e8c78 = get_image(g, "IMAGE_STORETOPBUTTON");
    if g.res.DAT_005e8c78 == NULL {
        return false;
    }
    g.res.DAT_005e8c44 = get_image(g, "IMAGE_STORETOPHILIGHT");
    if g.res.DAT_005e8c44 == NULL {
        return false;
    }
    g.res.DAT_005e8ebc = get_image(g, "IMAGE_SYLV");
    if g.res.DAT_005e8ebc == NULL {
        return false;
    }
    g.res.DAT_005e8c14 = get_image(g, "IMAGE_TANKBACKDROP1");
    if g.res.DAT_005e8c14 == NULL {
        return false;
    }
    g.res.DAT_005e8d48 = get_image(g, "IMAGE_TANKBACKDROP2");
    if g.res.DAT_005e8d48 == NULL {
        return false;
    }
    g.res.DAT_005e8da0 = get_image(g, "IMAGE_TANKBACKDROP3");
    if g.res.DAT_005e8da0 == NULL {
        return false;
    }
    g.res.DAT_005e8a8c = get_image(g, "IMAGE_TANKBACKDROP4");
    if g.res.DAT_005e8a8c == NULL {
        return false;
    }
    g.res.DAT_005e8f08 = get_image(g, "IMAGE_TANKBACKDROP5");
    if g.res.DAT_005e8f08 == NULL {
        return false;
    }
    g.res.DAT_005e8df8 = get_image(g, "IMAGE_TANKBACKDROP6");
    if g.res.DAT_005e8df8 == NULL {
        return false;
    }
    g.res.DAT_005e8ba4 = get_image(g, "IMAGE_TANKCHOOSER");
    if g.res.DAT_005e8ba4 == NULL {
        return false;
    }
    g.res.DAT_005e8ae8 = get_image(g, "IMAGE_TANKLIGHTING");
    if g.res.DAT_005e8ae8 == NULL {
        return false;
    }
    g.res.DAT_005e8bc0 = get_image(g, "IMAGE_TANKMASK1");
    if g.res.DAT_005e8bc0 == NULL {
        return false;
    }
    g.res.DAT_005e8f04 = get_image(g, "IMAGE_TANKMASK2");
    if g.res.DAT_005e8f04 == NULL {
        return false;
    }
    g.res.DAT_005e8a30 = get_image(g, "IMAGE_TANKMASK3");
    if g.res.DAT_005e8a30 == NULL {
        return false;
    }
    g.res.DAT_005e8ad0 = get_image(g, "IMAGE_TANKMASK4");
    if g.res.DAT_005e8ad0 == NULL {
        return false;
    }
    g.res.DAT_005e8af8 = get_image(g, "IMAGE_TANKMASK5");
    if g.res.DAT_005e8af8 == NULL {
        return false;
    }
    g.res.DAT_005e8a74 = get_image(g, "IMAGE_TANKMASK6");
    if g.res.DAT_005e8a74 == NULL {
        return false;
    }
    g.res.DAT_005e8dc0 = get_image(g, "IMAGE_TROPHYBAR");
    if g.res.DAT_005e8dc0 == NULL {
        return false;
    }
    g.res.DAT_005e8e28 = get_image(g, "IMAGE_TROPHYBUTTONS");
    if g.res.DAT_005e8e28 == NULL {
        return false;
    }
    g.res.DAT_005e8cf4 = get_image(g, "IMAGE_ULTRA");
    if g.res.DAT_005e8cf4 == NULL {
        return false;
    }
    g.res.DAT_005e8e58 = get_image(g, "IMAGE_ULYSSES");
    if g.res.DAT_005e8e58 == NULL {
        return false;
    }
    g.res.DAT_005e8d5c = get_image(g, "IMAGE_UNCHECKED");
    if g.res.DAT_005e8d5c == NULL {
        return false;
    }
    g.res.DAT_005e8d38 = get_image(g, "IMAGE_VERT");
    if g.res.DAT_005e8d38 == NULL {
        return false;
    }
    g.res.DAT_005e8cbc = get_image(g, "IMAGE_VERTCREASE");
    if g.res.DAT_005e8cbc == NULL {
        return false;
    }
    g.res.DAT_005e8b30 = get_image(g, "IMAGE_WADSWORTH");
    if g.res.DAT_005e8b30 == NULL {
        return false;
    }
    g.res.DAT_005e8b58 = get_image(g, "IMAGE_WAIT_BAR");
    if g.res.DAT_005e8b58 == NULL {
        return false;
    }
    g.res.DAT_005e8e50 = get_image(g, "IMAGE_WALTER");
    if g.res.DAT_005e8e50 == NULL {
        return false;
    }
    g.res.DAT_005e8c08 = get_image(g, "IMAGE_WARPGLOW");
    if g.res.DAT_005e8c08 == NULL {
        return false;
    }
    g.res.DAT_005e8e5c = get_image(g, "IMAGE_WARPHOLE");
    if g.res.DAT_005e8e5c == NULL {
        return false;
    }
    g.res.DAT_005e8af4 = get_image(g, "IMAGE_WAVE");
    if g.res.DAT_005e8af4 == NULL {
        return false;
    }
    g.res.DAT_005e8a50 = get_image(g, "IMAGE_WAVESIDE");
    if g.res.DAT_005e8a50 == NULL {
        return false;
    }
    g.res.DAT_005e8d98 = get_image(g, "IMAGE_WELCOMEBACK");
    if g.res.DAT_005e8d98 == NULL {
        return false;
    }
    g.res.DAT_005e8ef8 = get_image(g, "IMAGE_WELCOMETO");
    if g.res.DAT_005e8ef8 == NULL {
        return false;
    }
    g.res.DAT_005e8e30 = get_image(g, "IMAGE_ZORF");
    if g.res.DAT_005e8e30 == NULL {
        return false;
    }
    g.res.DAT_005e8b44 = get_image(g, "IMAGE_ZZZ");
    if g.res.DAT_005e8b44 == NULL {
        return false;
    }
    g.res.DAT_005e8c38 = get_sound(g, "SOUND_APPLAUSE");
    if g.res.DAT_005e8c38 == -1 {
        return false;
    }
    g.res.DAT_005e8c28 = get_sound(g, "SOUND_AWOOGA");
    if g.res.DAT_005e8c28 == -1 {
        return false;
    }
    g.res.DAT_005e8dd0 = get_sound(g, "SOUND_BABY");
    if g.res.DAT_005e8dd0 == -1 {
        return false;
    }
    g.res.DAT_005e8e24 = get_sound(g, "SOUND_BONUSCOLLECT");
    if g.res.DAT_005e8e24 == -1 {
        return false;
    }
    g.res.DAT_005e8edc = get_sound(g, "SOUND_BONUSCOUNT");
    if g.res.DAT_005e8edc == -1 {
        return false;
    }
    g.res.DAT_005e8b98 = get_sound(g, "SOUND_BUBBLES");
    if g.res.DAT_005e8b98 == -1 {
        return false;
    }
    g.res.DAT_005e8d14 = get_sound(g, "SOUND_BUY");
    if g.res.DAT_005e8d14 == -1 {
        return false;
    }
    g.res.DAT_005e8f0c = get_sound(g, "SOUND_BUZZER");
    if g.res.DAT_005e8f0c == -1 {
        return false;
    }
    g.res.DAT_005e8ba0 = get_sound(g, "SOUND_CHOMP");
    if g.res.DAT_005e8ba0 == -1 {
        return false;
    }
    g.res.DAT_005e8c8c = get_sound(g, "SOUND_CHOMP2");
    if g.res.DAT_005e8c8c == -1 {
        return false;
    }
    g.res.DAT_005e8d10 = get_sound(g, "SOUND_CROWNED");
    if g.res.DAT_005e8d10 == -1 {
        return false;
    }
    g.res.DAT_005e8d08 = get_sound(g, "SOUND_DIAMOND");
    if g.res.DAT_005e8d08 == -1 {
        return false;
    }
    g.res.DAT_005e8a70 = get_sound(g, "SOUND_DIE");
    if g.res.DAT_005e8a70 == -1 {
        return false;
    }
    g.res.DAT_005e8e14 = get_sound(g, "SOUND_DROPFOOD");
    if g.res.DAT_005e8e14 == -1 {
        return false;
    }
    g.res.DAT_005e8d78 = get_sound(g, "SOUND_EEL1");
    if g.res.DAT_005e8d78 == -1 {
        return false;
    }
    g.res.DAT_005e8ac4 = get_sound(g, "SOUND_EEL2");
    if g.res.DAT_005e8ac4 == -1 {
        return false;
    }
    g.res.DAT_005e8b9c = get_sound(g, "SOUND_EEL3");
    if g.res.DAT_005e8b9c == -1 {
        return false;
    }
    g.res.DAT_005e8c9c = get_sound(g, "SOUND_EVILLAFF");
    if g.res.DAT_005e8c9c == -1 {
        return false;
    }
    g.res.DAT_005e8d54 = get_sound(g, "SOUND_EXPLODE");
    if g.res.DAT_005e8d54 == -1 {
        return false;
    }
    g.res.DAT_005e8b28 = get_sound(g, "SOUND_EXPLOSION1");
    if g.res.DAT_005e8b28 == -1 {
        return false;
    }
    g.res.DAT_005e8e84 = get_sound(g, "SOUND_EXPLOSION4");
    if g.res.DAT_005e8e84 == -1 {
        return false;
    }
    g.res.DAT_005e8e90 = get_sound(g, "SOUND_FART");
    if g.res.DAT_005e8e90 == -1 {
        return false;
    }
    g.res.DAT_005e8ef4 = get_sound(g, "SOUND_FART2");
    if g.res.DAT_005e8ef4 == -1 {
        return false;
    }
    g.res.DAT_005e8af0 = get_sound(g, "SOUND_GROW");
    if g.res.DAT_005e8af0 == -1 {
        return false;
    }
    g.res.DAT_005e8e98 = get_sound(g, "SOUND_GUFFAW");
    if g.res.DAT_005e8e98 == -1 {
        return false;
    }
    g.res.DAT_005e8d44 = get_sound(g, "SOUND_HATCH");
    if g.res.DAT_005e8d44 == -1 {
        return false;
    }
    g.res.DAT_005e8bf8 = get_sound(g, "SOUND_HEAL");
    if g.res.DAT_005e8bf8 == -1 {
        return false;
    }
    g.res.DAT_005e8e68 = get_sound(g, "SOUND_HIT");
    if g.res.DAT_005e8e68 == -1 {
        return false;
    }
    g.res.DAT_005e8bc8 = get_sound(g, "SOUND_INTERFER");
    if g.res.DAT_005e8bc8 == -1 {
        return false;
    }
    g.res.DAT_005e8d94 = get_sound(g, "SOUND_MISSLE");
    if g.res.DAT_005e8d94 == -1 {
        return false;
    }
    g.res.DAT_005e8c34 = get_sound(g, "SOUND_NIKOCLOSE");
    if g.res.DAT_005e8c34 == -1 {
        return false;
    }
    g.res.DAT_005e8b20 = get_sound(g, "SOUND_NIKOOPEN");
    if g.res.DAT_005e8b20 == -1 {
        return false;
    }
    g.res.DAT_005e8e54 = get_sound(g, "SOUND_PEARL");
    if g.res.DAT_005e8e54 == -1 {
        return false;
    }
    g.res.DAT_005e8d74 = get_sound(g, "SOUND_POINTS");
    if g.res.DAT_005e8d74 == -1 {
        return false;
    }
    g.res.DAT_005e8b24 = get_sound(g, "SOUND_POINTS2");
    if g.res.DAT_005e8b24 == -1 {
        return false;
    }
    g.res.DAT_005e8e94 = get_sound(g, "SOUND_POINTS3");
    if g.res.DAT_005e8e94 == -1 {
        return false;
    }
    g.res.DAT_005e8b1c = get_sound(g, "SOUND_POINTS4");
    if g.res.DAT_005e8b1c == -1 {
        return false;
    }
    g.res.DAT_005e8acc = get_sound(g, "SOUND_PRIMALSCREAM");
    if g.res.DAT_005e8acc == -1 {
        return false;
    }
    g.res.DAT_005e8d34 = get_sound(g, "SOUND_PUNCH");
    if g.res.DAT_005e8d34 == -1 {
        return false;
    }
    g.res.DAT_005e8e10 = get_sound(g, "SOUND_RATTLE");
    if g.res.DAT_005e8e10 == -1 {
        return false;
    }
    g.res.DAT_005e8b40 = get_sound(g, "SOUND_RICOCHET");
    if g.res.DAT_005e8b40 == -1 {
        return false;
    }
    g.res.DAT_005e8c6c = get_sound(g, "SOUND_ROAR");
    if g.res.DAT_005e8c6c == -1 {
        return false;
    }
    g.res.DAT_005e8b6c = get_sound(g, "SOUND_ROAR2");
    if g.res.DAT_005e8b6c == -1 {
        return false;
    }
    g.res.DAT_005e89fc = get_sound(g, "SOUND_ROAR3");
    if g.res.DAT_005e89fc == -1 {
        return false;
    }
    g.res.DAT_005e8c48 = get_sound(g, "SOUND_SFX");
    if g.res.DAT_005e8c48 == -1 {
        return false;
    }
    g.res.DAT_005e8c10 = get_sound(g, "SOUND_SING");
    if g.res.DAT_005e8c10 == -1 {
        return false;
    }
    g.res.DAT_005e8de4 = get_sound(g, "SOUND_SLURP");
    if g.res.DAT_005e8de4 == -1 {
        return false;
    }
    g.res.DAT_005e8bdc = get_sound(g, "SOUND_SLURP2");
    if g.res.DAT_005e8bdc == -1 {
        return false;
    }
    g.res.DAT_005e8de0 = get_sound(g, "SOUND_SLURP3");
    if g.res.DAT_005e8de0 == -1 {
        return false;
    }
    g.res.DAT_005e8d8c = get_sound(g, "SOUND_SNEEZE");
    if g.res.DAT_005e8d8c == -1 {
        return false;
    }
    g.res.DAT_005e8a18 = get_sound(g, "SOUND_SONAR");
    if g.res.DAT_005e8a18 == -1 {
        return false;
    }
    g.res.DAT_005e8e64 = get_sound(g, "SOUND_SPLASH");
    if g.res.DAT_005e8e64 == -1 {
        return false;
    }
    g.res.DAT_005e8d2c = get_sound(g, "SOUND_SPLASH2");
    if g.res.DAT_005e8d2c == -1 {
        return false;
    }
    g.res.DAT_005e8cd4 = get_sound(g, "SOUND_SPLASH3");
    if g.res.DAT_005e8cd4 == -1 {
        return false;
    }
    g.res.DAT_005e8ea4 = get_sound(g, "SOUND_SPLASHBIG");
    if g.res.DAT_005e8ea4 == -1 {
        return false;
    }
    g.res.DAT_005e8b68 = get_sound(g, "SOUND_TAPGLASS");
    if g.res.DAT_005e8b68 == -1 {
        return false;
    }
    g.res.DAT_005e8ec4 = get_sound(g, "SOUND_TONE");
    if g.res.DAT_005e8ec4 == -1 {
        return false;
    }
    g.res.DAT_005e8a68 = get_sound(g, "SOUND_TONEHI");
    if g.res.DAT_005e8a68 == -1 {
        return false;
    }
    g.res.DAT_005e8a3c = get_sound(g, "SOUND_TONELO");
    if g.res.DAT_005e8a3c == -1 {
        return false;
    }
    g.res.DAT_005e8a7c = get_sound(g, "SOUND_TONESUPERHI");
    if g.res.DAT_005e8a7c == -1 {
        return false;
    }
    g.res.DAT_005e8df0 = get_sound(g, "SOUND_TREASURE");
    if g.res.DAT_005e8df0 == -1 {
        return false;
    }
    g.res.DAT_005e8a94 = get_sound(g, "SOUND_UNLEASH");
    if g.res.DAT_005e8a94 == -1 {
        return false;
    }
    g.res.DAT_005e8d9c = get_sound(g, "SOUND_ZAP");
    if g.res.DAT_005e8d9c == -1 {
        return false;
    }
    g.res.DAT_005e8b5c = get_sound(g, "SOUND_ZZAM");
    if g.res.DAT_005e8b5c == -1 {
        return false;
    }
    true
}

/// port: 0050e190 FUN_0050e190
/// `Extract...Resources(ResourceManager*)`: binds 16 resource globals. A missing
/// resource makes the original throw `ResourceManagerException`, which it catches and
/// returns false; here the lookup returns false the same way.
pub fn FUN_0050e190(g: &mut G) -> bool {
    g.globals.DAT_005e8f17 = true;
    g.res.DAT_005e8a28 = get_font(g, "FONT_BLAMBOTPRO15");
    if g.res.DAT_005e8a28 == NULL {
        return false;
    }
    g.res.DAT_005e8ea8 = get_font(g, "FONT_BLAMBOTPRO8");
    if g.res.DAT_005e8ea8 == NULL {
        return false;
    }
    g.res.DAT_005e8ce4 = get_font(g, "FONT_CONTINUUMBOLD12");
    if g.res.DAT_005e8ce4 == NULL {
        return false;
    }
    g.res.DAT_005e8cd0 = get_font(g, "FONT_CONTINUUMBOLD12OUTLINE");
    if g.res.DAT_005e8cd0 == NULL {
        return false;
    }
    g.res.DAT_005e8b04 = get_font(g, "FONT_CONTINUUMBOLD14");
    if g.res.DAT_005e8b04 == NULL {
        return false;
    }
    g.res.DAT_005e8d1c = get_font(g, "FONT_CONTINUUMBOLD14OUTLINE");
    if g.res.DAT_005e8d1c == NULL {
        return false;
    }
    g.res.DAT_005e8a5c = get_font(g, "FONT_JUNGLEFEVER12OUTLINE");
    if g.res.DAT_005e8a5c == NULL {
        return false;
    }
    g.res.DAT_005e8e18 = get_font(g, "FONT_JUNGLEFEVER15OUTLINE");
    if g.res.DAT_005e8e18 == NULL {
        return false;
    }
    g.res.DAT_005e8dac = get_font(g, "FONT_LIDDIE12");
    if g.res.DAT_005e8dac == NULL {
        return false;
    }
    g.res.DAT_005e8bbc = get_font(g, "FONT_LIDDIE15");
    if g.res.DAT_005e8bbc == NULL {
        return false;
    }
    g.res.DAT_005e8a9c = get_font(g, "FONT_LIDDIE18");
    if g.res.DAT_005e8a9c == NULL {
        return false;
    }
    g.res.DAT_005e8c20 = get_font(g, "FONT_TINY");
    if g.res.DAT_005e8c20 == NULL {
        return false;
    }
    g.res.DAT_005e8aa4 = get_font(g, "FONT_TINYBOLD");
    if g.res.DAT_005e8aa4 == NULL {
        return false;
    }
    g.res.DAT_005e8cc0 = get_image(g, "IMAGE_DIALOG");
    if g.res.DAT_005e8cc0 == NULL {
        return false;
    }
    g.res.DAT_005e8c54 = get_image(g, "IMAGE_DIALOGBUTTON");
    if g.res.DAT_005e8c54 == NULL {
        return false;
    }
    g.res.DAT_005e8dbc = get_image(g, "IMAGE_EDITBOX");
    if g.res.DAT_005e8dbc == NULL {
        return false;
    }
    true
}

