// @generated by tools/gen_res.py from the Extract*Resources functions in winfish.sqlite.
// Do not edit by hand.

use crate::sexy::types::Ptr;

/// Resource globals of the original, one field per `DAT_` address. Images and fonts
/// hold object pointers; sounds hold sound ids.
#[derive(Debug, Default, Clone)]
pub struct Res {
    /// `SOUND_ROAR3` (sound, set in the function at 005073e0)
    pub DAT_005e89fc: i32,
    /// `IMAGE_SIMTURN2` (image, set in the function at 005073e0)
    pub DAT_005e8a00: Ptr,
    /// `IMAGE_BONUSBUTTONOVERLAY` (image, set in the function at 005073e0)
    pub DAT_005e8a04: Ptr,
    /// `IMAGE_NIMBUS` (image, set in the function at 005073e0)
    pub DAT_005e8a08: Ptr,
    /// `IMAGE_SCL_WADSWORTH` (image, set in the function at 005073e0)
    pub DAT_005e8a0c: Ptr,
    /// `IMAGE_LASERUPGRADES` (image, set in the function at 005073e0)
    pub DAT_005e8a10: Ptr,
    /// `IMAGE_BLIP` (image, set in the function at 005073e0)
    pub DAT_005e8a14: Ptr,
    /// `SOUND_SONAR` (sound, set in the function at 005073e0)
    pub DAT_005e8a18: i32,
    /// `IMAGE_HELPSCREENSAVER` (image, set in the function at 005073e0)
    pub DAT_005e8a1c: Ptr,
    /// `IMAGE_OPTIONSBUTTOND` (image, set in the function at 005073e0)
    pub DAT_005e8a20: Ptr,
    /// `IMAGE_EGGSHARDS` (image, set in the function at 005073e0)
    pub DAT_005e8a24: Ptr,
    /// `FONT_BLAMBOTPRO15` (font, set in the function at 0050e190)
    pub DAT_005e8a28: Ptr,
    /// `IMAGE_MISSILE` (image, set in the function at 005073e0)
    pub DAT_005e8a2c: Ptr,
    /// `IMAGE_TANKMASK3` (image, set in the function at 005073e0)
    pub DAT_005e8a30: Ptr,
    /// `IMAGE_CHOMP` (image, set in the function at 005073e0)
    pub DAT_005e8a34: Ptr,
    /// `IMAGE_PETBUTTONREFLECT` (image, set in the function at 005073e0)
    pub DAT_005e8a38: Ptr,
    /// `SOUND_TONELO` (sound, set in the function at 005073e0)
    pub DAT_005e8a3c: i32,
    /// `IMAGE_MERYLTAIL` (image, set in the function at 005073e0)
    pub DAT_005e8a40: Ptr,
    /// `IMAGE_ENERGYBALL` (image, set in the function at 005073e0)
    pub DAT_005e8a44: Ptr,
    /// `IMAGE_PETBTNO` (image, set in the function at 005073e0)
    pub DAT_005e8a48: Ptr,
    /// `IMAGE_CURSOR_POINTER` (image, set in the function at 00506ea0)
    pub DAT_005e8a4c: Ptr,
    /// `IMAGE_WAVESIDE` (image, set in the function at 005073e0)
    pub DAT_005e8a50: Ptr,
    /// `IMAGE_SCL_WALTER` (image, set in the function at 005073e0)
    pub DAT_005e8a54: Ptr,
    /// `IMAGE_HORZCREASE` (image, set in the function at 005073e0)
    pub DAT_005e8a58: Ptr,
    /// `FONT_JUNGLEFEVER12OUTLINE` (font, set in the function at 0050e190)
    pub DAT_005e8a5c: Ptr,
    /// `IMAGE_STOREBACKDROPS` (image, set in the function at 005073e0)
    pub DAT_005e8a60: Ptr,
    /// `IMAGE_AA_BEAM` (image, set in the function at 005073e0)
    pub DAT_005e8a64: Ptr,
    /// `SOUND_TONEHI` (sound, set in the function at 005073e0)
    pub DAT_005e8a68: i32,
    /// `IMAGE_HELPARROW` (image, set in the function at 005073e0)
    pub DAT_005e8a6c: Ptr,
    /// `SOUND_DIE` (sound, set in the function at 005073e0)
    pub DAT_005e8a70: i32,
    /// `IMAGE_TANKMASK6` (image, set in the function at 005073e0)
    pub DAT_005e8a74: Ptr,
    /// `IMAGE_HATCHANIMATION` (image, set in the function at 005073e0)
    pub DAT_005e8a78: Ptr,
    /// `SOUND_TONESUPERHI` (sound, set in the function at 005073e0)
    pub DAT_005e8a7c: i32,
    /// `IMAGE_CURSOR_DRAGGING` (image, set in the function at 00506ea0)
    pub DAT_005e8a80: Ptr,
    /// `IMAGE_SCL_STINKY` (image, set in the function at 005073e0)
    pub DAT_005e8a84: Ptr,
    /// `IMAGE_PETBUTTONRING` (image, set in the function at 005073e0)
    pub DAT_005e8a88: Ptr,
    /// `IMAGE_TANKBACKDROP4` (image, set in the function at 005073e0)
    pub DAT_005e8a8c: Ptr,
    /// `IMAGE_SMOKETINY` (image, set in the function at 005073e0)
    pub DAT_005e8a90: Ptr,
    /// `SOUND_UNLEASH` (sound, set in the function at 005073e0)
    pub DAT_005e8a94: i32,
    /// `IMAGE_RHUBARB` (image, set in the function at 005073e0)
    pub DAT_005e8a98: Ptr,
    /// `FONT_LIDDIE18` (font, set in the function at 0050e190)
    pub DAT_005e8a9c: Ptr,
    /// `IMAGE_FOOD` (image, set in the function at 005073e0)
    pub DAT_005e8aa0: Ptr,
    /// `FONT_TINYBOLD` (font, set in the function at 0050e190)
    pub DAT_005e8aa4: Ptr,
    /// `IMAGE_SMALLDIE` (image, set in the function at 005073e0)
    pub DAT_005e8aa8: Ptr,
    /// `IMAGE_NIKOTOWER` (image, set in the function at 005073e0)
    pub DAT_005e8aac: Ptr,
    /// `IMAGE_BONUS2` (image, set in the function at 005073e0)
    pub DAT_005e8ab0: Ptr,
    /// `IMAGE_HATCHSCREEN` (image, set in the function at 005073e0)
    pub DAT_005e8ab4: Ptr,
    /// `IMAGE_SMALLSWIM` (image, set in the function at 005073e0)
    pub DAT_005e8ab8: Ptr,
    /// `IMAGE_SCL_STANLEY` (image, set in the function at 005073e0)
    pub DAT_005e8abc: Ptr,
    /// `IMAGE_SCL_STARCATCHER` (image, set in the function at 005073e0)
    pub DAT_005e8ac0: Ptr,
    /// `SOUND_EEL2` (sound, set in the function at 005073e0)
    pub DAT_005e8ac4: i32,
    /// `IMAGE_SCL_VERT` (image, set in the function at 005073e0)
    pub DAT_005e8ac8: Ptr,
    /// `SOUND_PRIMALSCREAM` (sound, set in the function at 005073e0)
    pub DAT_005e8acc: i32,
    /// `IMAGE_TANKMASK4` (image, set in the function at 005073e0)
    pub DAT_005e8ad0: Ptr,
    /// `IMAGE_MERYLBLINK` (image, set in the function at 005073e0)
    pub DAT_005e8ad4: Ptr,
    /// `IMAGE_LEFTBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8ad8: Ptr,
    /// `IMAGE_AQUARIUM4` (image, set in the function at 005073e0)
    pub DAT_005e8adc: Ptr,
    /// `IMAGE_SCL_BRINKLEY` (image, set in the function at 005073e0)
    pub DAT_005e8ae0: Ptr,
    /// `IMAGE_GUS` (image, set in the function at 005073e0)
    pub DAT_005e8ae4: Ptr,
    /// `IMAGE_TANKLIGHTING` (image, set in the function at 005073e0)
    pub DAT_005e8ae8: Ptr,
    /// `IMAGE_ITCHY` (image, set in the function at 005073e0)
    pub DAT_005e8aec: Ptr,
    /// `SOUND_GROW` (sound, set in the function at 005073e0)
    pub DAT_005e8af0: i32,
    /// `IMAGE_WAVE` (image, set in the function at 005073e0)
    pub DAT_005e8af4: Ptr,
    /// `IMAGE_TANKMASK5` (image, set in the function at 005073e0)
    pub DAT_005e8af8: Ptr,
    /// `IMAGE_SCL_NOSTRADAMUS` (image, set in the function at 005073e0)
    pub DAT_005e8afc: Ptr,
    /// `IMAGE_LOADERBAR` (image, set in the function at 00506ea0)
    pub DAT_005e8b00: Ptr,
    /// `FONT_CONTINUUMBOLD14` (font, set in the function at 0050e190)
    pub DAT_005e8b04: Ptr,
    /// `IMAGE_MERYL` (image, set in the function at 005073e0)
    pub DAT_005e8b08: Ptr,
    /// `IMAGE_SEYMOUR` (image, set in the function at 005073e0)
    pub DAT_005e8b0c: Ptr,
    /// `IMAGE_MENUBAR` (image, set in the function at 005073e0)
    pub DAT_005e8b10: Ptr,
    /// `IMAGE_SIMEAT2` (image, set in the function at 005073e0)
    pub DAT_005e8b14: Ptr,
    /// `IMAGE_BOLT` (image, set in the function at 005073e0)
    pub DAT_005e8b18: Ptr,
    /// `SOUND_POINTS4` (sound, set in the function at 005073e0)
    pub DAT_005e8b1c: i32,
    /// `SOUND_NIKOOPEN` (sound, set in the function at 005073e0)
    pub DAT_005e8b20: i32,
    /// `SOUND_POINTS2` (sound, set in the function at 005073e0)
    pub DAT_005e8b24: i32,
    /// `SOUND_EXPLOSION1` (sound, set in the function at 005073e0)
    pub DAT_005e8b28: i32,
    /// `IMAGE_SCL_CLYDE` (image, set in the function at 005073e0)
    pub DAT_005e8b2c: Ptr,
    /// `IMAGE_WADSWORTH` (image, set in the function at 005073e0)
    pub DAT_005e8b30: Ptr,
    /// `IMAGE_HELPPETCHOOSE` (image, set in the function at 005073e0)
    pub DAT_005e8b34: Ptr,
    /// `IMAGE_STORERIGHTHILIGHT` (image, set in the function at 005073e0)
    pub DAT_005e8b38: Ptr,
    /// `IMAGE_STORERIGHTBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8b3c: Ptr,
    /// `SOUND_RICOCHET` (sound, set in the function at 005073e0)
    pub DAT_005e8b40: i32,
    /// `IMAGE_ZZZ` (image, set in the function at 005073e0)
    pub DAT_005e8b44: Ptr,
    /// `IMAGE_SIMCARNIVORE` (image, set in the function at 005073e0)
    pub DAT_005e8b48: Ptr,
    /// `IMAGE_BRINKLEY` (image, set in the function at 005073e0)
    pub DAT_005e8b4c: Ptr,
    /// `IMAGE_CURSOR_TEXT` (image, set in the function at 00506ea0)
    pub DAT_005e8b50: Ptr,
    /// `IMAGE_SIMTURN3` (image, set in the function at 005073e0)
    pub DAT_005e8b54: Ptr,
    /// `IMAGE_WAIT_BAR` (image, set in the function at 005073e0)
    pub DAT_005e8b58: Ptr,
    /// `SOUND_ZZAM` (sound, set in the function at 005073e0)
    pub DAT_005e8b5c: i32,
    /// `IMAGE_RUFUS` (image, set in the function at 005073e0)
    pub DAT_005e8b60: Ptr,
    /// `IMAGE_CHICKEN` (image, set in the function at 005073e0)
    pub DAT_005e8b64: Ptr,
    /// `SOUND_TAPGLASS` (sound, set in the function at 005073e0)
    pub DAT_005e8b68: i32,
    /// `SOUND_ROAR2` (sound, set in the function at 005073e0)
    pub DAT_005e8b6c: i32,
    /// `IMAGE_AQUARIUM1` (image, set in the function at 005073e0)
    pub DAT_005e8b70: Ptr,
    /// `IMAGE_HELPSHELL` (image, set in the function at 005073e0)
    pub DAT_005e8b74: Ptr,
    /// `IMAGE_SIMSWIM1` (image, set in the function at 005073e0)
    pub DAT_005e8b78: Ptr,
    /// `IMAGE_SCL_GASH` (image, set in the function at 005073e0)
    pub DAT_005e8b7c: Ptr,
    /// `IMAGE_SCL_OSCAR` (image, set in the function at 005073e0)
    pub DAT_005e8b80: Ptr,
    /// `IMAGE_PETBTNU` (image, set in the function at 005073e0)
    pub DAT_005e8b84: Ptr,
    /// `IMAGE_MIDDLEBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8b88: Ptr,
    /// `IMAGE_AA_TOP2` (image, set in the function at 005073e0)
    pub DAT_005e8b8c: Ptr,
    /// `IMAGE_AA_BOTTOM` (image, set in the function at 005073e0)
    pub DAT_005e8b90: Ptr,
    /// `IMAGE_SCL_GUMBO` (image, set in the function at 005073e0)
    pub DAT_005e8b94: Ptr,
    /// `SOUND_BUBBLES` (sound, set in the function at 005073e0)
    pub DAT_005e8b98: i32,
    /// `SOUND_EEL3` (sound, set in the function at 005073e0)
    pub DAT_005e8b9c: i32,
    /// `SOUND_CHOMP` (sound, set in the function at 005073e0)
    pub DAT_005e8ba0: i32,
    /// `IMAGE_TANKCHOOSER` (image, set in the function at 005073e0)
    pub DAT_005e8ba4: Ptr,
    /// `IMAGE_SELECTORSCREEN` (image, set in the function at 005073e0)
    pub DAT_005e8ba8: Ptr,
    /// `IMAGE_SCL_GRUBBER` (image, set in the function at 005073e0)
    pub DAT_005e8bac: Ptr,
    /// `IMAGE_SMOKESMALL` (image, set in the function at 005073e0)
    pub DAT_005e8bb0: Ptr,
    /// `IMAGE_SPARKLE` (image, set in the function at 005073e0)
    pub DAT_005e8bb4: Ptr,
    /// `IMAGE_BONUS1` (image, set in the function at 005073e0)
    pub DAT_005e8bb8: Ptr,
    /// `FONT_LIDDIE15` (font, set in the function at 0050e190)
    pub DAT_005e8bbc: Ptr,
    /// `IMAGE_TANKMASK1` (image, set in the function at 005073e0)
    pub DAT_005e8bc0: Ptr,
    /// `IMAGE_MISCITEMS` (image, set in the function at 005073e0)
    pub DAT_005e8bc4: Ptr,
    /// `SOUND_INTERFER` (sound, set in the function at 005073e0)
    pub DAT_005e8bc8: i32,
    /// `IMAGE_GUMBOLIGHT` (image, set in the function at 005073e0)
    pub DAT_005e8bcc: Ptr,
    /// `IMAGE_CLYDE` (image, set in the function at 005073e0)
    pub DAT_005e8bd0: Ptr,
    /// `IMAGE_SIMEAT3` (image, set in the function at 005073e0)
    pub DAT_005e8bd4: Ptr,
    /// `IMAGE_PEARL` (image, set in the function at 005073e0)
    pub DAT_005e8bd8: Ptr,
    /// `SOUND_SLURP2` (sound, set in the function at 005073e0)
    pub DAT_005e8bdc: i32,
    /// `IMAGE_STINKY` (image, set in the function at 005073e0)
    pub DAT_005e8be0: Ptr,
    /// `IMAGE_SLIDERTHUMB` (image, set in the function at 005073e0)
    pub DAT_005e8be4: Ptr,
    /// `IMAGE_AQUARIUM5` (image, set in the function at 005073e0)
    pub DAT_005e8be8: Ptr,
    /// `IMAGE_TITLEPAGE` (image, set in the function at 00506ea0)
    pub DAT_005e8bec: Ptr,
    /// `IMAGE_SCL_MERYL` (image, set in the function at 005073e0)
    pub DAT_005e8bf0: Ptr,
    /// `IMAGE_HATCHREFLECTION` (image, set in the function at 005073e0)
    pub DAT_005e8bf4: Ptr,
    /// `SOUND_HEAL` (sound, set in the function at 005073e0)
    pub DAT_005e8bf8: i32,
    /// `IMAGE_GASH` (image, set in the function at 005073e0)
    pub DAT_005e8bfc: Ptr,
    /// `IMAGE_EGGPIECES` (image, set in the function at 005073e0)
    pub DAT_005e8c00: Ptr,
    /// `IMAGE_AQUARIUM2` (image, set in the function at 005073e0)
    pub DAT_005e8c04: Ptr,
    /// `IMAGE_WARPGLOW` (image, set in the function at 005073e0)
    pub DAT_005e8c08: Ptr,
    /// `IMAGE_MINISYLV` (image, set in the function at 005073e0)
    pub DAT_005e8c0c: Ptr,
    /// `SOUND_SING` (sound, set in the function at 005073e0)
    pub DAT_005e8c10: i32,
    /// `IMAGE_TANKBACKDROP1` (image, set in the function at 005073e0)
    pub DAT_005e8c14: Ptr,
    /// `IMAGE_SPEECHBUBBLE` (image, set in the function at 005073e0)
    pub DAT_005e8c18: Ptr,
    /// `IMAGE_MAINBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8c1c: Ptr,
    /// `FONT_TINY` (font, set in the function at 0050e190)
    pub DAT_005e8c20: Ptr,
    /// `IMAGE_SIMEAT1` (image, set in the function at 005073e0)
    pub DAT_005e8c24: Ptr,
    /// `SOUND_AWOOGA` (sound, set in the function at 005073e0)
    pub DAT_005e8c28: i32,
    /// `IMAGE_SHRAPNEL` (image, set in the function at 005073e0)
    pub DAT_005e8c2c: Ptr,
    /// `IMAGE_LOADERBAROVER` (image, set in the function at 00506ea0)
    pub DAT_005e8c30: Ptr,
    /// `SOUND_NIKOCLOSE` (sound, set in the function at 005073e0)
    pub DAT_005e8c34: i32,
    /// `SOUND_APPLAUSE` (sound, set in the function at 005073e0)
    pub DAT_005e8c38: i32,
    /// `IMAGE_STORESHELL` (image, set in the function at 005073e0)
    pub DAT_005e8c3c: Ptr,
    /// `SOUND_BUTTONCLICK` (sound, set in the function at 00506ea0)
    pub DAT_005e8c40: i32,
    /// `IMAGE_STORETOPHILIGHT` (image, set in the function at 005073e0)
    pub DAT_005e8c44: Ptr,
    /// `SOUND_SFX` (sound, set in the function at 005073e0)
    pub DAT_005e8c48: i32,
    /// `IMAGE_PSYCHOSQUID` (image, set in the function at 005073e0)
    pub DAT_005e8c4c: Ptr,
    /// `IMAGE_PEANUT` (image, set in the function at 005073e0)
    pub DAT_005e8c50: Ptr,
    /// `IMAGE_DIALOGBUTTON` (image, set in the function at 0050e190)
    pub DAT_005e8c54: Ptr,
    /// `IMAGE_FISHBOX` (image, set in the function at 005073e0)
    pub DAT_005e8c58: Ptr,
    /// `IMAGE_STORELEFTBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8c5c: Ptr,
    /// `IMAGE_MENUBTNU` (image, set in the function at 005073e0)
    pub DAT_005e8c60: Ptr,
    /// `IMAGE_CHECKED` (image, set in the function at 005073e0)
    pub DAT_005e8c64: Ptr,
    /// `IMAGE_AA_STORE` (image, set in the function at 005073e0)
    pub DAT_005e8c68: Ptr,
    /// `SOUND_ROAR` (sound, set in the function at 005073e0)
    pub DAT_005e8c6c: i32,
    /// `IMAGE_SCREENBACK` (image, set in the function at 005073e0)
    pub DAT_005e8c70: Ptr,
    /// `IMAGE_EGGCRACK1` (image, set in the function at 005073e0)
    pub DAT_005e8c74: Ptr,
    /// `IMAGE_STORETOPBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8c78: Ptr,
    /// `IMAGE_HALO` (image, set in the function at 005073e0)
    pub DAT_005e8c7c: Ptr,
    /// `IMAGE_BUBBULATOR_STORE` (image, set in the function at 005073e0)
    pub DAT_005e8c80: Ptr,
    /// `IMAGE_BUBBLES` (image, set in the function at 005073e0)
    pub DAT_005e8c84: Ptr,
    /// `IMAGE_SCL_PRESTO` (image, set in the function at 005073e0)
    pub DAT_005e8c88: Ptr,
    /// `SOUND_CHOMP2` (sound, set in the function at 005073e0)
    pub DAT_005e8c8c: i32,
    /// `IMAGE_SCL_BREEDER` (image, set in the function at 005073e0)
    pub DAT_005e8c90: Ptr,
    /// `IMAGE_OPTIONSBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8c94: Ptr,
    /// `IMAGE_GRUBBER` (image, set in the function at 005073e0)
    pub DAT_005e8c98: Ptr,
    /// `SOUND_EVILLAFF` (sound, set in the function at 005073e0)
    pub DAT_005e8c9c: i32,
    /// `IMAGE_PREGO` (image, set in the function at 005073e0)
    pub DAT_005e8ca0: Ptr,
    /// `IMAGE_HELPALIEN` (image, set in the function at 005073e0)
    pub DAT_005e8ca4: Ptr,
    /// `IMAGE_EGGCRACK2` (image, set in the function at 005073e0)
    pub DAT_005e8ca8: Ptr,
    /// `IMAGE_EGGBRINKLEY` (image, set in the function at 005073e0)
    pub DAT_005e8cac: Ptr,
    /// `IMAGE_SCL_ITCHY` (image, set in the function at 005073e0)
    pub DAT_005e8cb0: Ptr,
    /// `IMAGE_GUMBO` (image, set in the function at 005073e0)
    pub DAT_005e8cb4: Ptr,
    /// `IMAGE_BOSS` (image, set in the function at 005073e0)
    pub DAT_005e8cb8: Ptr,
    /// `IMAGE_VERTCREASE` (image, set in the function at 005073e0)
    pub DAT_005e8cbc: Ptr,
    /// `IMAGE_DIALOG` (image, set in the function at 0050e190)
    pub DAT_005e8cc0: Ptr,
    /// `IMAGE_BONUSBUCKET` (image, set in the function at 005073e0)
    pub DAT_005e8cc4: Ptr,
    /// `IMAGE_SLIDERTRACK` (image, set in the function at 005073e0)
    pub DAT_005e8cc8: Ptr,
    /// `IMAGE_SCL_BLIP` (image, set in the function at 005073e0)
    pub DAT_005e8ccc: Ptr,
    /// `FONT_CONTINUUMBOLD12OUTLINE` (font, set in the function at 0050e190)
    pub DAT_005e8cd0: Ptr,
    /// `SOUND_SPLASH3` (sound, set in the function at 005073e0)
    pub DAT_005e8cd4: i32,
    /// `IMAGE_STORESCREEN` (image, set in the function at 005073e0)
    pub DAT_005e8cd8: Ptr,
    /// `IMAGE_SCL_RHUBARB` (image, set in the function at 005073e0)
    pub DAT_005e8cdc: Ptr,
    /// `IMAGE_SCL_GEKKO` (image, set in the function at 005073e0)
    pub DAT_005e8ce0: Ptr,
    /// `FONT_CONTINUUMBOLD12` (font, set in the function at 0050e190)
    pub DAT_005e8ce4: Ptr,
    /// `IMAGE_AMPCHARGE` (image, set in the function at 005073e0)
    pub DAT_005e8ce8: Ptr,
    /// `IMAGE_BALROG` (image, set in the function at 005073e0)
    pub DAT_005e8cec: Ptr,
    /// `FONT_JUNGLEFEVER10OUTLINE` (font, set in the function at 00506ea0)
    pub DAT_005e8cf0: Ptr,
    /// `IMAGE_ULTRA` (image, set in the function at 005073e0)
    pub DAT_005e8cf4: Ptr,
    /// `IMAGE_BATTLETANKBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8cf8: Ptr,
    /// `IMAGE_AA_TOP1` (image, set in the function at 005073e0)
    pub DAT_005e8cfc: Ptr,
    /// `IMAGE_STANLEY` (image, set in the function at 005073e0)
    pub DAT_005e8d00: Ptr,
    /// `IMAGE_SPARKS` (image, set in the function at 005073e0)
    pub DAT_005e8d04: Ptr,
    /// `SOUND_DIAMOND` (sound, set in the function at 005073e0)
    pub DAT_005e8d08: i32,
    /// `IMAGE_PIZZA` (image, set in the function at 005073e0)
    pub DAT_005e8d0c: Ptr,
    /// `SOUND_CROWNED` (sound, set in the function at 005073e0)
    pub DAT_005e8d10: i32,
    /// `SOUND_BUY` (sound, set in the function at 005073e0)
    pub DAT_005e8d14: i32,
    /// `IMAGE_STORELEFTHILIGHT` (image, set in the function at 005073e0)
    pub DAT_005e8d18: Ptr,
    /// `FONT_CONTINUUMBOLD14OUTLINE` (font, set in the function at 0050e190)
    pub DAT_005e8d1c: Ptr,
    /// `IMAGE_SCL_ZORF` (image, set in the function at 005073e0)
    pub DAT_005e8d20: Ptr,
    /// `IMAGE_SCL_NIMBUS` (image, set in the function at 005073e0)
    pub DAT_005e8d24: Ptr,
    /// `IMAGE_CENTERBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8d28: Ptr,
    /// `SOUND_SPLASH2` (sound, set in the function at 005073e0)
    pub DAT_005e8d2c: i32,
    /// `IMAGE_SCL_ANGIE` (image, set in the function at 005073e0)
    pub DAT_005e8d30: Ptr,
    /// `SOUND_PUNCH` (sound, set in the function at 005073e0)
    pub DAT_005e8d34: i32,
    /// `IMAGE_VERT` (image, set in the function at 005073e0)
    pub DAT_005e8d38: Ptr,
    /// `IMAGE_SCREENTITLE` (image, set in the function at 005073e0)
    pub DAT_005e8d3c: Ptr,
    /// `IMAGE_EXPLOSION` (image, set in the function at 005073e0)
    pub DAT_005e8d40: Ptr,
    /// `SOUND_HATCH` (sound, set in the function at 005073e0)
    pub DAT_005e8d44: i32,
    /// `IMAGE_TANKBACKDROP2` (image, set in the function at 005073e0)
    pub DAT_005e8d48: Ptr,
    /// `IMAGE_BREEDER` (image, set in the function at 005073e0)
    pub DAT_005e8d4c: Ptr,
    /// `IMAGE_AQUARIUM3` (image, set in the function at 005073e0)
    pub DAT_005e8d50: Ptr,
    /// `SOUND_EXPLODE` (sound, set in the function at 005073e0)
    pub DAT_005e8d54: i32,
    /// `IMAGE_SMOKEMISSILE` (image, set in the function at 005073e0)
    pub DAT_005e8d58: Ptr,
    /// `IMAGE_UNCHECKED` (image, set in the function at 005073e0)
    pub DAT_005e8d5c: Ptr,
    /// `IMAGE_PRESTO` (image, set in the function at 005073e0)
    pub DAT_005e8d60: Ptr,
    /// `IMAGE_MENUBTND` (image, set in the function at 005073e0)
    pub DAT_005e8d64: Ptr,
    /// `IMAGE_EGGSTANLEY` (image, set in the function at 005073e0)
    pub DAT_005e8d68: Ptr,
    /// `IMAGE_LOADERPLAY` (image, set in the function at 00506ea0)
    pub DAT_005e8d6c: Ptr,
    /// `IMAGE_BUBBULATOR` (image, set in the function at 005073e0)
    pub DAT_005e8d70: Ptr,
    /// `SOUND_POINTS` (sound, set in the function at 005073e0)
    pub DAT_005e8d74: i32,
    /// `SOUND_EEL1` (sound, set in the function at 005073e0)
    pub DAT_005e8d78: i32,
    /// `IMAGE_SHELLS` (image, set in the function at 005073e0)
    pub DAT_005e8d7c: Ptr,
    /// `IMAGE_BLANK` (image, set in the function at 00506ea0)
    pub DAT_005e8d80: Ptr,
    /// `IMAGE_SMALLTURN` (image, set in the function at 005073e0)
    pub DAT_005e8d84: Ptr,
    /// `IMAGE_MONEYBAG` (image, set in the function at 005073e0)
    pub DAT_005e8d88: Ptr,
    /// `SOUND_SNEEZE` (sound, set in the function at 005073e0)
    pub DAT_005e8d8c: i32,
    /// `IMAGE_AA_GLOW` (image, set in the function at 005073e0)
    pub DAT_005e8d90: Ptr,
    /// `SOUND_MISSLE` (sound, set in the function at 005073e0)
    pub DAT_005e8d94: i32,
    /// `IMAGE_WELCOMEBACK` (image, set in the function at 005073e0)
    pub DAT_005e8d98: Ptr,
    /// `SOUND_ZAP` (sound, set in the function at 005073e0)
    pub DAT_005e8d9c: i32,
    /// `IMAGE_TANKBACKDROP3` (image, set in the function at 005073e0)
    pub DAT_005e8da0: Ptr,
    /// `IMAGE_SHADOW` (image, set in the function at 005073e0)
    pub DAT_005e8da4: Ptr,
    /// `IMAGE_GEKKO` (image, set in the function at 005073e0)
    pub DAT_005e8da8: Ptr,
    /// `FONT_LIDDIE12` (font, set in the function at 0050e190)
    pub DAT_005e8dac: Ptr,
    /// `IMAGE_EGGWALTER` (image, set in the function at 005073e0)
    pub DAT_005e8db0: Ptr,
    /// `IMAGE_SCL_SEYMOUR` (image, set in the function at 005073e0)
    pub DAT_005e8db4: Ptr,
    /// `IMAGE_AQUARIUM6` (image, set in the function at 005073e0)
    pub DAT_005e8db8: Ptr,
    /// `IMAGE_EDITBOX` (image, set in the function at 0050e190)
    pub DAT_005e8dbc: Ptr,
    /// `IMAGE_TROPHYBAR` (image, set in the function at 005073e0)
    pub DAT_005e8dc0: Ptr,
    /// `IMAGE_HUNGRYBREEDER` (image, set in the function at 005073e0)
    pub DAT_005e8dc4: Ptr,
    /// `IMAGE_SCL_ULTRA` (image, set in the function at 005073e0)
    pub DAT_005e8dc8: Ptr,
    /// `IMAGE_SCL_SHRAPNEL` (image, set in the function at 005073e0)
    pub DAT_005e8dcc: Ptr,
    /// `SOUND_BABY` (sound, set in the function at 005073e0)
    pub DAT_005e8dd0: i32,
    /// `IMAGE_BONUSAWARD2` (image, set in the function at 005073e0)
    pub DAT_005e8dd4: Ptr,
    /// `IMAGE_BONUS3` (image, set in the function at 005073e0)
    pub DAT_005e8dd8: Ptr,
    /// `IMAGE_MERYLLIPS` (image, set in the function at 005073e0)
    pub DAT_005e8ddc: Ptr,
    /// `SOUND_SLURP3` (sound, set in the function at 005073e0)
    pub DAT_005e8de0: i32,
    /// `SOUND_SLURP` (sound, set in the function at 005073e0)
    pub DAT_005e8de4: i32,
    /// `IMAGE_AMP` (image, set in the function at 005073e0)
    pub DAT_005e8de8: Ptr,
    /// `IMAGE_RIGHTBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8dec: Ptr,
    /// `SOUND_TREASURE` (sound, set in the function at 005073e0)
    pub DAT_005e8df0: i32,
    /// `IMAGE_EXPLOSIONTINY` (image, set in the function at 005073e0)
    pub DAT_005e8df4: Ptr,
    /// `IMAGE_TANKBACKDROP6` (image, set in the function at 005073e0)
    pub DAT_005e8df8: Ptr,
    /// `IMAGE_SCL_AMP` (image, set in the function at 005073e0)
    pub DAT_005e8dfc: Ptr,
    /// `IMAGE_BATTLETANKBUTTOND` (image, set in the function at 005073e0)
    pub DAT_005e8e00: Ptr,
    /// `IMAGE_STARCATCHER` (image, set in the function at 005073e0)
    pub DAT_005e8e04: Ptr,
    /// `IMAGE_SIMTURN1` (image, set in the function at 005073e0)
    pub DAT_005e8e08: Ptr,
    /// `IMAGE_ICECREAM` (image, set in the function at 005073e0)
    pub DAT_005e8e0c: Ptr,
    /// `SOUND_RATTLE` (sound, set in the function at 005073e0)
    pub DAT_005e8e10: i32,
    /// `SOUND_DROPFOOD` (sound, set in the function at 005073e0)
    pub DAT_005e8e14: i32,
    /// `FONT_JUNGLEFEVER15OUTLINE` (font, set in the function at 0050e190)
    pub DAT_005e8e18: Ptr,
    /// `IMAGE_CROSSHAIR` (image, set in the function at 005073e0)
    pub DAT_005e8e1c: Ptr,
    /// `IMAGE_CURSOR_HAND` (image, set in the function at 00506ea0)
    pub DAT_005e8e20: Ptr,
    /// `SOUND_BONUSCOLLECT` (sound, set in the function at 005073e0)
    pub DAT_005e8e24: i32,
    /// `IMAGE_TROPHYBUTTONS` (image, set in the function at 005073e0)
    pub DAT_005e8e28: Ptr,
    /// `IMAGE_MENUBUTTONREFLECTION` (image, set in the function at 005073e0)
    pub DAT_005e8e2c: Ptr,
    /// `IMAGE_ZORF` (image, set in the function at 005073e0)
    pub DAT_005e8e30: Ptr,
    /// `IMAGE_LASERS` (image, set in the function at 005073e0)
    pub DAT_005e8e34: Ptr,
    /// `IMAGE_PETLIMITEGG` (image, set in the function at 005073e0)
    pub DAT_005e8e38: Ptr,
    /// `IMAGE_HEALTHBAR` (image, set in the function at 005073e0)
    pub DAT_005e8e3c: Ptr,
    /// `FONT_JUNGLEFEVER17OUTLINE` (font, set in the function at 00506ea0)
    pub DAT_005e8e40: Ptr,
    /// `IMAGE_NIKO` (image, set in the function at 005073e0)
    pub DAT_005e8e44: Ptr,
    /// `IMAGE_HUNGRYSWIM` (image, set in the function at 005073e0)
    pub DAT_005e8e48: Ptr,
    /// `IMAGE_PETBUTTONHOLE` (image, set in the function at 005073e0)
    pub DAT_005e8e4c: Ptr,
    /// `IMAGE_WALTER` (image, set in the function at 005073e0)
    pub DAT_005e8e50: Ptr,
    /// `SOUND_PEARL` (sound, set in the function at 005073e0)
    pub DAT_005e8e54: i32,
    /// `IMAGE_ULYSSES` (image, set in the function at 005073e0)
    pub DAT_005e8e58: Ptr,
    /// `IMAGE_WARPHOLE` (image, set in the function at 005073e0)
    pub DAT_005e8e5c: Ptr,
    /// `IMAGE_MONEY` (image, set in the function at 005073e0)
    pub DAT_005e8e60: Ptr,
    /// `SOUND_SPLASH` (sound, set in the function at 005073e0)
    pub DAT_005e8e64: i32,
    /// `SOUND_HIT` (sound, set in the function at 005073e0)
    pub DAT_005e8e68: i32,
    /// `IMAGE_SCREENTITLEHOLE` (image, set in the function at 005073e0)
    pub DAT_005e8e6c: Ptr,
    /// `IMAGE_MONEYFLASH` (image, set in the function at 005073e0)
    pub DAT_005e8e70: Ptr,
    /// `IMAGE_MENUBTNO` (image, set in the function at 005073e0)
    pub DAT_005e8e74: Ptr,
    /// `IMAGE_PETBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8e78: Ptr,
    /// `IMAGE_FISHBOXBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8e7c: Ptr,
    /// `IMAGE_TITLEPAGEMASK` (image, set in the function at 00506ea0)
    pub DAT_005e8e80: Ptr,
    /// `SOUND_EXPLOSION4` (sound, set in the function at 005073e0)
    pub DAT_005e8e84: i32,
    /// `IMAGE_HUNGRYTURN` (image, set in the function at 005073e0)
    pub DAT_005e8e88: Ptr,
    /// `IMAGE_ANGIE` (image, set in the function at 005073e0)
    pub DAT_005e8e8c: Ptr,
    /// `SOUND_FART` (sound, set in the function at 005073e0)
    pub DAT_005e8e90: i32,
    /// `SOUND_POINTS3` (sound, set in the function at 005073e0)
    pub DAT_005e8e94: i32,
    /// `SOUND_GUFFAW` (sound, set in the function at 005073e0)
    pub DAT_005e8e98: i32,
    /// `IMAGE_MIDDLEBUTTOND` (image, set in the function at 005073e0)
    pub DAT_005e8e9c: Ptr,
    /// `IMAGE_BONUSAWARD` (image, set in the function at 005073e0)
    pub DAT_005e8ea0: Ptr,
    /// `SOUND_SPLASHBIG` (sound, set in the function at 005073e0)
    pub DAT_005e8ea4: i32,
    /// `FONT_BLAMBOTPRO8` (font, set in the function at 0050e190)
    pub DAT_005e8ea8: Ptr,
    /// `IMAGE_SELECTORSPEECHBUBBLE` (image, set in the function at 005073e0)
    pub DAT_005e8eac: Ptr,
    /// `IMAGE_SCL_RUFUS` (image, set in the function at 005073e0)
    pub DAT_005e8eb0: Ptr,
    /// `IMAGE_MENUBTND2` (image, set in the function at 005073e0)
    pub DAT_005e8eb4: Ptr,
    /// `IMAGE_HEALTHBARTUBE` (image, set in the function at 005073e0)
    pub DAT_005e8eb8: Ptr,
    /// `IMAGE_SYLV` (image, set in the function at 005073e0)
    pub DAT_005e8ebc: Ptr,
    /// `IMAGE_SMALLEAT` (image, set in the function at 005073e0)
    pub DAT_005e8ec0: Ptr,
    /// `SOUND_TONE` (sound, set in the function at 005073e0)
    pub DAT_005e8ec4: i32,
    /// `IMAGE_DESTRUCTOR` (image, set in the function at 005073e0)
    pub DAT_005e8ec8: Ptr,
    /// `IMAGE_HUNGRYEAT` (image, set in the function at 005073e0)
    pub DAT_005e8ecc: Ptr,
    /// `IMAGE_SCL_NIKO` (image, set in the function at 005073e0)
    pub DAT_005e8ed0: Ptr,
    /// `IMAGE_NOSTRADAMUS` (image, set in the function at 005073e0)
    pub DAT_005e8ed4: Ptr,
    /// `IMAGE_FATBUTTON` (image, set in the function at 005073e0)
    pub DAT_005e8ed8: Ptr,
    /// `SOUND_BONUSCOUNT` (sound, set in the function at 005073e0)
    pub DAT_005e8edc: i32,
    /// `IMAGE_SCL_PREGO` (image, set in the function at 005073e0)
    pub DAT_005e8ee0: Ptr,
    /// `IMAGE_EGGNOSTRADAMUS` (image, set in the function at 005073e0)
    pub DAT_005e8ee4: Ptr,
    /// `IMAGE_BALLS` (image, set in the function at 005073e0)
    pub DAT_005e8ee8: Ptr,
    /// `IMAGE_SIMSWIM2` (image, set in the function at 005073e0)
    pub DAT_005e8eec: Ptr,
    /// `IMAGE_EXPLOSIONSMALL` (image, set in the function at 005073e0)
    pub DAT_005e8ef0: Ptr,
    /// `SOUND_FART2` (sound, set in the function at 005073e0)
    pub DAT_005e8ef4: i32,
    /// `IMAGE_WELCOMETO` (image, set in the function at 005073e0)
    pub DAT_005e8ef8: Ptr,
    /// `IMAGE_SIMSWIM3` (image, set in the function at 005073e0)
    pub DAT_005e8efc: Ptr,
    /// `IMAGE_BILATERUS` (image, set in the function at 005073e0)
    pub DAT_005e8f00: Ptr,
    /// `IMAGE_TANKMASK2` (image, set in the function at 005073e0)
    pub DAT_005e8f04: Ptr,
    /// `IMAGE_TANKBACKDROP5` (image, set in the function at 005073e0)
    pub DAT_005e8f08: Ptr,
    /// `SOUND_BUZZER` (sound, set in the function at 005073e0)
    pub DAT_005e8f0c: i32,
    /// `IMAGE_LOADERBARLOADING` (image, set in the function at 00506ea0)
    pub DAT_005e8f10: Ptr,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ResKind { Image, Font, Sound }

/// (global address, resource id, kind) for every resource global.
pub const RES_GLOBALS: [(u32, &str, ResKind); 326] = [
    (0x005e89fc, "SOUND_ROAR3", ResKind::Sound),
    (0x005e8a00, "IMAGE_SIMTURN2", ResKind::Image),
    (0x005e8a04, "IMAGE_BONUSBUTTONOVERLAY", ResKind::Image),
    (0x005e8a08, "IMAGE_NIMBUS", ResKind::Image),
    (0x005e8a0c, "IMAGE_SCL_WADSWORTH", ResKind::Image),
    (0x005e8a10, "IMAGE_LASERUPGRADES", ResKind::Image),
    (0x005e8a14, "IMAGE_BLIP", ResKind::Image),
    (0x005e8a18, "SOUND_SONAR", ResKind::Sound),
    (0x005e8a1c, "IMAGE_HELPSCREENSAVER", ResKind::Image),
    (0x005e8a20, "IMAGE_OPTIONSBUTTOND", ResKind::Image),
    (0x005e8a24, "IMAGE_EGGSHARDS", ResKind::Image),
    (0x005e8a28, "FONT_BLAMBOTPRO15", ResKind::Font),
    (0x005e8a2c, "IMAGE_MISSILE", ResKind::Image),
    (0x005e8a30, "IMAGE_TANKMASK3", ResKind::Image),
    (0x005e8a34, "IMAGE_CHOMP", ResKind::Image),
    (0x005e8a38, "IMAGE_PETBUTTONREFLECT", ResKind::Image),
    (0x005e8a3c, "SOUND_TONELO", ResKind::Sound),
    (0x005e8a40, "IMAGE_MERYLTAIL", ResKind::Image),
    (0x005e8a44, "IMAGE_ENERGYBALL", ResKind::Image),
    (0x005e8a48, "IMAGE_PETBTNO", ResKind::Image),
    (0x005e8a4c, "IMAGE_CURSOR_POINTER", ResKind::Image),
    (0x005e8a50, "IMAGE_WAVESIDE", ResKind::Image),
    (0x005e8a54, "IMAGE_SCL_WALTER", ResKind::Image),
    (0x005e8a58, "IMAGE_HORZCREASE", ResKind::Image),
    (0x005e8a5c, "FONT_JUNGLEFEVER12OUTLINE", ResKind::Font),
    (0x005e8a60, "IMAGE_STOREBACKDROPS", ResKind::Image),
    (0x005e8a64, "IMAGE_AA_BEAM", ResKind::Image),
    (0x005e8a68, "SOUND_TONEHI", ResKind::Sound),
    (0x005e8a6c, "IMAGE_HELPARROW", ResKind::Image),
    (0x005e8a70, "SOUND_DIE", ResKind::Sound),
    (0x005e8a74, "IMAGE_TANKMASK6", ResKind::Image),
    (0x005e8a78, "IMAGE_HATCHANIMATION", ResKind::Image),
    (0x005e8a7c, "SOUND_TONESUPERHI", ResKind::Sound),
    (0x005e8a80, "IMAGE_CURSOR_DRAGGING", ResKind::Image),
    (0x005e8a84, "IMAGE_SCL_STINKY", ResKind::Image),
    (0x005e8a88, "IMAGE_PETBUTTONRING", ResKind::Image),
    (0x005e8a8c, "IMAGE_TANKBACKDROP4", ResKind::Image),
    (0x005e8a90, "IMAGE_SMOKETINY", ResKind::Image),
    (0x005e8a94, "SOUND_UNLEASH", ResKind::Sound),
    (0x005e8a98, "IMAGE_RHUBARB", ResKind::Image),
    (0x005e8a9c, "FONT_LIDDIE18", ResKind::Font),
    (0x005e8aa0, "IMAGE_FOOD", ResKind::Image),
    (0x005e8aa4, "FONT_TINYBOLD", ResKind::Font),
    (0x005e8aa8, "IMAGE_SMALLDIE", ResKind::Image),
    (0x005e8aac, "IMAGE_NIKOTOWER", ResKind::Image),
    (0x005e8ab0, "IMAGE_BONUS2", ResKind::Image),
    (0x005e8ab4, "IMAGE_HATCHSCREEN", ResKind::Image),
    (0x005e8ab8, "IMAGE_SMALLSWIM", ResKind::Image),
    (0x005e8abc, "IMAGE_SCL_STANLEY", ResKind::Image),
    (0x005e8ac0, "IMAGE_SCL_STARCATCHER", ResKind::Image),
    (0x005e8ac4, "SOUND_EEL2", ResKind::Sound),
    (0x005e8ac8, "IMAGE_SCL_VERT", ResKind::Image),
    (0x005e8acc, "SOUND_PRIMALSCREAM", ResKind::Sound),
    (0x005e8ad0, "IMAGE_TANKMASK4", ResKind::Image),
    (0x005e8ad4, "IMAGE_MERYLBLINK", ResKind::Image),
    (0x005e8ad8, "IMAGE_LEFTBUTTON", ResKind::Image),
    (0x005e8adc, "IMAGE_AQUARIUM4", ResKind::Image),
    (0x005e8ae0, "IMAGE_SCL_BRINKLEY", ResKind::Image),
    (0x005e8ae4, "IMAGE_GUS", ResKind::Image),
    (0x005e8ae8, "IMAGE_TANKLIGHTING", ResKind::Image),
    (0x005e8aec, "IMAGE_ITCHY", ResKind::Image),
    (0x005e8af0, "SOUND_GROW", ResKind::Sound),
    (0x005e8af4, "IMAGE_WAVE", ResKind::Image),
    (0x005e8af8, "IMAGE_TANKMASK5", ResKind::Image),
    (0x005e8afc, "IMAGE_SCL_NOSTRADAMUS", ResKind::Image),
    (0x005e8b00, "IMAGE_LOADERBAR", ResKind::Image),
    (0x005e8b04, "FONT_CONTINUUMBOLD14", ResKind::Font),
    (0x005e8b08, "IMAGE_MERYL", ResKind::Image),
    (0x005e8b0c, "IMAGE_SEYMOUR", ResKind::Image),
    (0x005e8b10, "IMAGE_MENUBAR", ResKind::Image),
    (0x005e8b14, "IMAGE_SIMEAT2", ResKind::Image),
    (0x005e8b18, "IMAGE_BOLT", ResKind::Image),
    (0x005e8b1c, "SOUND_POINTS4", ResKind::Sound),
    (0x005e8b20, "SOUND_NIKOOPEN", ResKind::Sound),
    (0x005e8b24, "SOUND_POINTS2", ResKind::Sound),
    (0x005e8b28, "SOUND_EXPLOSION1", ResKind::Sound),
    (0x005e8b2c, "IMAGE_SCL_CLYDE", ResKind::Image),
    (0x005e8b30, "IMAGE_WADSWORTH", ResKind::Image),
    (0x005e8b34, "IMAGE_HELPPETCHOOSE", ResKind::Image),
    (0x005e8b38, "IMAGE_STORERIGHTHILIGHT", ResKind::Image),
    (0x005e8b3c, "IMAGE_STORERIGHTBUTTON", ResKind::Image),
    (0x005e8b40, "SOUND_RICOCHET", ResKind::Sound),
    (0x005e8b44, "IMAGE_ZZZ", ResKind::Image),
    (0x005e8b48, "IMAGE_SIMCARNIVORE", ResKind::Image),
    (0x005e8b4c, "IMAGE_BRINKLEY", ResKind::Image),
    (0x005e8b50, "IMAGE_CURSOR_TEXT", ResKind::Image),
    (0x005e8b54, "IMAGE_SIMTURN3", ResKind::Image),
    (0x005e8b58, "IMAGE_WAIT_BAR", ResKind::Image),
    (0x005e8b5c, "SOUND_ZZAM", ResKind::Sound),
    (0x005e8b60, "IMAGE_RUFUS", ResKind::Image),
    (0x005e8b64, "IMAGE_CHICKEN", ResKind::Image),
    (0x005e8b68, "SOUND_TAPGLASS", ResKind::Sound),
    (0x005e8b6c, "SOUND_ROAR2", ResKind::Sound),
    (0x005e8b70, "IMAGE_AQUARIUM1", ResKind::Image),
    (0x005e8b74, "IMAGE_HELPSHELL", ResKind::Image),
    (0x005e8b78, "IMAGE_SIMSWIM1", ResKind::Image),
    (0x005e8b7c, "IMAGE_SCL_GASH", ResKind::Image),
    (0x005e8b80, "IMAGE_SCL_OSCAR", ResKind::Image),
    (0x005e8b84, "IMAGE_PETBTNU", ResKind::Image),
    (0x005e8b88, "IMAGE_MIDDLEBUTTON", ResKind::Image),
    (0x005e8b8c, "IMAGE_AA_TOP2", ResKind::Image),
    (0x005e8b90, "IMAGE_AA_BOTTOM", ResKind::Image),
    (0x005e8b94, "IMAGE_SCL_GUMBO", ResKind::Image),
    (0x005e8b98, "SOUND_BUBBLES", ResKind::Sound),
    (0x005e8b9c, "SOUND_EEL3", ResKind::Sound),
    (0x005e8ba0, "SOUND_CHOMP", ResKind::Sound),
    (0x005e8ba4, "IMAGE_TANKCHOOSER", ResKind::Image),
    (0x005e8ba8, "IMAGE_SELECTORSCREEN", ResKind::Image),
    (0x005e8bac, "IMAGE_SCL_GRUBBER", ResKind::Image),
    (0x005e8bb0, "IMAGE_SMOKESMALL", ResKind::Image),
    (0x005e8bb4, "IMAGE_SPARKLE", ResKind::Image),
    (0x005e8bb8, "IMAGE_BONUS1", ResKind::Image),
    (0x005e8bbc, "FONT_LIDDIE15", ResKind::Font),
    (0x005e8bc0, "IMAGE_TANKMASK1", ResKind::Image),
    (0x005e8bc4, "IMAGE_MISCITEMS", ResKind::Image),
    (0x005e8bc8, "SOUND_INTERFER", ResKind::Sound),
    (0x005e8bcc, "IMAGE_GUMBOLIGHT", ResKind::Image),
    (0x005e8bd0, "IMAGE_CLYDE", ResKind::Image),
    (0x005e8bd4, "IMAGE_SIMEAT3", ResKind::Image),
    (0x005e8bd8, "IMAGE_PEARL", ResKind::Image),
    (0x005e8bdc, "SOUND_SLURP2", ResKind::Sound),
    (0x005e8be0, "IMAGE_STINKY", ResKind::Image),
    (0x005e8be4, "IMAGE_SLIDERTHUMB", ResKind::Image),
    (0x005e8be8, "IMAGE_AQUARIUM5", ResKind::Image),
    (0x005e8bec, "IMAGE_TITLEPAGE", ResKind::Image),
    (0x005e8bf0, "IMAGE_SCL_MERYL", ResKind::Image),
    (0x005e8bf4, "IMAGE_HATCHREFLECTION", ResKind::Image),
    (0x005e8bf8, "SOUND_HEAL", ResKind::Sound),
    (0x005e8bfc, "IMAGE_GASH", ResKind::Image),
    (0x005e8c00, "IMAGE_EGGPIECES", ResKind::Image),
    (0x005e8c04, "IMAGE_AQUARIUM2", ResKind::Image),
    (0x005e8c08, "IMAGE_WARPGLOW", ResKind::Image),
    (0x005e8c0c, "IMAGE_MINISYLV", ResKind::Image),
    (0x005e8c10, "SOUND_SING", ResKind::Sound),
    (0x005e8c14, "IMAGE_TANKBACKDROP1", ResKind::Image),
    (0x005e8c18, "IMAGE_SPEECHBUBBLE", ResKind::Image),
    (0x005e8c1c, "IMAGE_MAINBUTTON", ResKind::Image),
    (0x005e8c20, "FONT_TINY", ResKind::Font),
    (0x005e8c24, "IMAGE_SIMEAT1", ResKind::Image),
    (0x005e8c28, "SOUND_AWOOGA", ResKind::Sound),
    (0x005e8c2c, "IMAGE_SHRAPNEL", ResKind::Image),
    (0x005e8c30, "IMAGE_LOADERBAROVER", ResKind::Image),
    (0x005e8c34, "SOUND_NIKOCLOSE", ResKind::Sound),
    (0x005e8c38, "SOUND_APPLAUSE", ResKind::Sound),
    (0x005e8c3c, "IMAGE_STORESHELL", ResKind::Image),
    (0x005e8c40, "SOUND_BUTTONCLICK", ResKind::Sound),
    (0x005e8c44, "IMAGE_STORETOPHILIGHT", ResKind::Image),
    (0x005e8c48, "SOUND_SFX", ResKind::Sound),
    (0x005e8c4c, "IMAGE_PSYCHOSQUID", ResKind::Image),
    (0x005e8c50, "IMAGE_PEANUT", ResKind::Image),
    (0x005e8c54, "IMAGE_DIALOGBUTTON", ResKind::Image),
    (0x005e8c58, "IMAGE_FISHBOX", ResKind::Image),
    (0x005e8c5c, "IMAGE_STORELEFTBUTTON", ResKind::Image),
    (0x005e8c60, "IMAGE_MENUBTNU", ResKind::Image),
    (0x005e8c64, "IMAGE_CHECKED", ResKind::Image),
    (0x005e8c68, "IMAGE_AA_STORE", ResKind::Image),
    (0x005e8c6c, "SOUND_ROAR", ResKind::Sound),
    (0x005e8c70, "IMAGE_SCREENBACK", ResKind::Image),
    (0x005e8c74, "IMAGE_EGGCRACK1", ResKind::Image),
    (0x005e8c78, "IMAGE_STORETOPBUTTON", ResKind::Image),
    (0x005e8c7c, "IMAGE_HALO", ResKind::Image),
    (0x005e8c80, "IMAGE_BUBBULATOR_STORE", ResKind::Image),
    (0x005e8c84, "IMAGE_BUBBLES", ResKind::Image),
    (0x005e8c88, "IMAGE_SCL_PRESTO", ResKind::Image),
    (0x005e8c8c, "SOUND_CHOMP2", ResKind::Sound),
    (0x005e8c90, "IMAGE_SCL_BREEDER", ResKind::Image),
    (0x005e8c94, "IMAGE_OPTIONSBUTTON", ResKind::Image),
    (0x005e8c98, "IMAGE_GRUBBER", ResKind::Image),
    (0x005e8c9c, "SOUND_EVILLAFF", ResKind::Sound),
    (0x005e8ca0, "IMAGE_PREGO", ResKind::Image),
    (0x005e8ca4, "IMAGE_HELPALIEN", ResKind::Image),
    (0x005e8ca8, "IMAGE_EGGCRACK2", ResKind::Image),
    (0x005e8cac, "IMAGE_EGGBRINKLEY", ResKind::Image),
    (0x005e8cb0, "IMAGE_SCL_ITCHY", ResKind::Image),
    (0x005e8cb4, "IMAGE_GUMBO", ResKind::Image),
    (0x005e8cb8, "IMAGE_BOSS", ResKind::Image),
    (0x005e8cbc, "IMAGE_VERTCREASE", ResKind::Image),
    (0x005e8cc0, "IMAGE_DIALOG", ResKind::Image),
    (0x005e8cc4, "IMAGE_BONUSBUCKET", ResKind::Image),
    (0x005e8cc8, "IMAGE_SLIDERTRACK", ResKind::Image),
    (0x005e8ccc, "IMAGE_SCL_BLIP", ResKind::Image),
    (0x005e8cd0, "FONT_CONTINUUMBOLD12OUTLINE", ResKind::Font),
    (0x005e8cd4, "SOUND_SPLASH3", ResKind::Sound),
    (0x005e8cd8, "IMAGE_STORESCREEN", ResKind::Image),
    (0x005e8cdc, "IMAGE_SCL_RHUBARB", ResKind::Image),
    (0x005e8ce0, "IMAGE_SCL_GEKKO", ResKind::Image),
    (0x005e8ce4, "FONT_CONTINUUMBOLD12", ResKind::Font),
    (0x005e8ce8, "IMAGE_AMPCHARGE", ResKind::Image),
    (0x005e8cec, "IMAGE_BALROG", ResKind::Image),
    (0x005e8cf0, "FONT_JUNGLEFEVER10OUTLINE", ResKind::Font),
    (0x005e8cf4, "IMAGE_ULTRA", ResKind::Image),
    (0x005e8cf8, "IMAGE_BATTLETANKBUTTON", ResKind::Image),
    (0x005e8cfc, "IMAGE_AA_TOP1", ResKind::Image),
    (0x005e8d00, "IMAGE_STANLEY", ResKind::Image),
    (0x005e8d04, "IMAGE_SPARKS", ResKind::Image),
    (0x005e8d08, "SOUND_DIAMOND", ResKind::Sound),
    (0x005e8d0c, "IMAGE_PIZZA", ResKind::Image),
    (0x005e8d10, "SOUND_CROWNED", ResKind::Sound),
    (0x005e8d14, "SOUND_BUY", ResKind::Sound),
    (0x005e8d18, "IMAGE_STORELEFTHILIGHT", ResKind::Image),
    (0x005e8d1c, "FONT_CONTINUUMBOLD14OUTLINE", ResKind::Font),
    (0x005e8d20, "IMAGE_SCL_ZORF", ResKind::Image),
    (0x005e8d24, "IMAGE_SCL_NIMBUS", ResKind::Image),
    (0x005e8d28, "IMAGE_CENTERBUTTON", ResKind::Image),
    (0x005e8d2c, "SOUND_SPLASH2", ResKind::Sound),
    (0x005e8d30, "IMAGE_SCL_ANGIE", ResKind::Image),
    (0x005e8d34, "SOUND_PUNCH", ResKind::Sound),
    (0x005e8d38, "IMAGE_VERT", ResKind::Image),
    (0x005e8d3c, "IMAGE_SCREENTITLE", ResKind::Image),
    (0x005e8d40, "IMAGE_EXPLOSION", ResKind::Image),
    (0x005e8d44, "SOUND_HATCH", ResKind::Sound),
    (0x005e8d48, "IMAGE_TANKBACKDROP2", ResKind::Image),
    (0x005e8d4c, "IMAGE_BREEDER", ResKind::Image),
    (0x005e8d50, "IMAGE_AQUARIUM3", ResKind::Image),
    (0x005e8d54, "SOUND_EXPLODE", ResKind::Sound),
    (0x005e8d58, "IMAGE_SMOKEMISSILE", ResKind::Image),
    (0x005e8d5c, "IMAGE_UNCHECKED", ResKind::Image),
    (0x005e8d60, "IMAGE_PRESTO", ResKind::Image),
    (0x005e8d64, "IMAGE_MENUBTND", ResKind::Image),
    (0x005e8d68, "IMAGE_EGGSTANLEY", ResKind::Image),
    (0x005e8d6c, "IMAGE_LOADERPLAY", ResKind::Image),
    (0x005e8d70, "IMAGE_BUBBULATOR", ResKind::Image),
    (0x005e8d74, "SOUND_POINTS", ResKind::Sound),
    (0x005e8d78, "SOUND_EEL1", ResKind::Sound),
    (0x005e8d7c, "IMAGE_SHELLS", ResKind::Image),
    (0x005e8d80, "IMAGE_BLANK", ResKind::Image),
    (0x005e8d84, "IMAGE_SMALLTURN", ResKind::Image),
    (0x005e8d88, "IMAGE_MONEYBAG", ResKind::Image),
    (0x005e8d8c, "SOUND_SNEEZE", ResKind::Sound),
    (0x005e8d90, "IMAGE_AA_GLOW", ResKind::Image),
    (0x005e8d94, "SOUND_MISSLE", ResKind::Sound),
    (0x005e8d98, "IMAGE_WELCOMEBACK", ResKind::Image),
    (0x005e8d9c, "SOUND_ZAP", ResKind::Sound),
    (0x005e8da0, "IMAGE_TANKBACKDROP3", ResKind::Image),
    (0x005e8da4, "IMAGE_SHADOW", ResKind::Image),
    (0x005e8da8, "IMAGE_GEKKO", ResKind::Image),
    (0x005e8dac, "FONT_LIDDIE12", ResKind::Font),
    (0x005e8db0, "IMAGE_EGGWALTER", ResKind::Image),
    (0x005e8db4, "IMAGE_SCL_SEYMOUR", ResKind::Image),
    (0x005e8db8, "IMAGE_AQUARIUM6", ResKind::Image),
    (0x005e8dbc, "IMAGE_EDITBOX", ResKind::Image),
    (0x005e8dc0, "IMAGE_TROPHYBAR", ResKind::Image),
    (0x005e8dc4, "IMAGE_HUNGRYBREEDER", ResKind::Image),
    (0x005e8dc8, "IMAGE_SCL_ULTRA", ResKind::Image),
    (0x005e8dcc, "IMAGE_SCL_SHRAPNEL", ResKind::Image),
    (0x005e8dd0, "SOUND_BABY", ResKind::Sound),
    (0x005e8dd4, "IMAGE_BONUSAWARD2", ResKind::Image),
    (0x005e8dd8, "IMAGE_BONUS3", ResKind::Image),
    (0x005e8ddc, "IMAGE_MERYLLIPS", ResKind::Image),
    (0x005e8de0, "SOUND_SLURP3", ResKind::Sound),
    (0x005e8de4, "SOUND_SLURP", ResKind::Sound),
    (0x005e8de8, "IMAGE_AMP", ResKind::Image),
    (0x005e8dec, "IMAGE_RIGHTBUTTON", ResKind::Image),
    (0x005e8df0, "SOUND_TREASURE", ResKind::Sound),
    (0x005e8df4, "IMAGE_EXPLOSIONTINY", ResKind::Image),
    (0x005e8df8, "IMAGE_TANKBACKDROP6", ResKind::Image),
    (0x005e8dfc, "IMAGE_SCL_AMP", ResKind::Image),
    (0x005e8e00, "IMAGE_BATTLETANKBUTTOND", ResKind::Image),
    (0x005e8e04, "IMAGE_STARCATCHER", ResKind::Image),
    (0x005e8e08, "IMAGE_SIMTURN1", ResKind::Image),
    (0x005e8e0c, "IMAGE_ICECREAM", ResKind::Image),
    (0x005e8e10, "SOUND_RATTLE", ResKind::Sound),
    (0x005e8e14, "SOUND_DROPFOOD", ResKind::Sound),
    (0x005e8e18, "FONT_JUNGLEFEVER15OUTLINE", ResKind::Font),
    (0x005e8e1c, "IMAGE_CROSSHAIR", ResKind::Image),
    (0x005e8e20, "IMAGE_CURSOR_HAND", ResKind::Image),
    (0x005e8e24, "SOUND_BONUSCOLLECT", ResKind::Sound),
    (0x005e8e28, "IMAGE_TROPHYBUTTONS", ResKind::Image),
    (0x005e8e2c, "IMAGE_MENUBUTTONREFLECTION", ResKind::Image),
    (0x005e8e30, "IMAGE_ZORF", ResKind::Image),
    (0x005e8e34, "IMAGE_LASERS", ResKind::Image),
    (0x005e8e38, "IMAGE_PETLIMITEGG", ResKind::Image),
    (0x005e8e3c, "IMAGE_HEALTHBAR", ResKind::Image),
    (0x005e8e40, "FONT_JUNGLEFEVER17OUTLINE", ResKind::Font),
    (0x005e8e44, "IMAGE_NIKO", ResKind::Image),
    (0x005e8e48, "IMAGE_HUNGRYSWIM", ResKind::Image),
    (0x005e8e4c, "IMAGE_PETBUTTONHOLE", ResKind::Image),
    (0x005e8e50, "IMAGE_WALTER", ResKind::Image),
    (0x005e8e54, "SOUND_PEARL", ResKind::Sound),
    (0x005e8e58, "IMAGE_ULYSSES", ResKind::Image),
    (0x005e8e5c, "IMAGE_WARPHOLE", ResKind::Image),
    (0x005e8e60, "IMAGE_MONEY", ResKind::Image),
    (0x005e8e64, "SOUND_SPLASH", ResKind::Sound),
    (0x005e8e68, "SOUND_HIT", ResKind::Sound),
    (0x005e8e6c, "IMAGE_SCREENTITLEHOLE", ResKind::Image),
    (0x005e8e70, "IMAGE_MONEYFLASH", ResKind::Image),
    (0x005e8e74, "IMAGE_MENUBTNO", ResKind::Image),
    (0x005e8e78, "IMAGE_PETBUTTON", ResKind::Image),
    (0x005e8e7c, "IMAGE_FISHBOXBUTTON", ResKind::Image),
    (0x005e8e80, "IMAGE_TITLEPAGEMASK", ResKind::Image),
    (0x005e8e84, "SOUND_EXPLOSION4", ResKind::Sound),
    (0x005e8e88, "IMAGE_HUNGRYTURN", ResKind::Image),
    (0x005e8e8c, "IMAGE_ANGIE", ResKind::Image),
    (0x005e8e90, "SOUND_FART", ResKind::Sound),
    (0x005e8e94, "SOUND_POINTS3", ResKind::Sound),
    (0x005e8e98, "SOUND_GUFFAW", ResKind::Sound),
    (0x005e8e9c, "IMAGE_MIDDLEBUTTOND", ResKind::Image),
    (0x005e8ea0, "IMAGE_BONUSAWARD", ResKind::Image),
    (0x005e8ea4, "SOUND_SPLASHBIG", ResKind::Sound),
    (0x005e8ea8, "FONT_BLAMBOTPRO8", ResKind::Font),
    (0x005e8eac, "IMAGE_SELECTORSPEECHBUBBLE", ResKind::Image),
    (0x005e8eb0, "IMAGE_SCL_RUFUS", ResKind::Image),
    (0x005e8eb4, "IMAGE_MENUBTND2", ResKind::Image),
    (0x005e8eb8, "IMAGE_HEALTHBARTUBE", ResKind::Image),
    (0x005e8ebc, "IMAGE_SYLV", ResKind::Image),
    (0x005e8ec0, "IMAGE_SMALLEAT", ResKind::Image),
    (0x005e8ec4, "SOUND_TONE", ResKind::Sound),
    (0x005e8ec8, "IMAGE_DESTRUCTOR", ResKind::Image),
    (0x005e8ecc, "IMAGE_HUNGRYEAT", ResKind::Image),
    (0x005e8ed0, "IMAGE_SCL_NIKO", ResKind::Image),
    (0x005e8ed4, "IMAGE_NOSTRADAMUS", ResKind::Image),
    (0x005e8ed8, "IMAGE_FATBUTTON", ResKind::Image),
    (0x005e8edc, "SOUND_BONUSCOUNT", ResKind::Sound),
    (0x005e8ee0, "IMAGE_SCL_PREGO", ResKind::Image),
    (0x005e8ee4, "IMAGE_EGGNOSTRADAMUS", ResKind::Image),
    (0x005e8ee8, "IMAGE_BALLS", ResKind::Image),
    (0x005e8eec, "IMAGE_SIMSWIM2", ResKind::Image),
    (0x005e8ef0, "IMAGE_EXPLOSIONSMALL", ResKind::Image),
    (0x005e8ef4, "SOUND_FART2", ResKind::Sound),
    (0x005e8ef8, "IMAGE_WELCOMETO", ResKind::Image),
    (0x005e8efc, "IMAGE_SIMSWIM3", ResKind::Image),
    (0x005e8f00, "IMAGE_BILATERUS", ResKind::Image),
    (0x005e8f04, "IMAGE_TANKMASK2", ResKind::Image),
    (0x005e8f08, "IMAGE_TANKBACKDROP5", ResKind::Image),
    (0x005e8f0c, "SOUND_BUZZER", ResKind::Sound),
    (0x005e8f10, "IMAGE_LOADERBARLOADING", ResKind::Image),
];

impl Res {
    /// Stores a resolved resource into the global at `addr`.
    pub fn set(&mut self, addr: u32, value: i32) {
        match addr {
            0x005e89fc => self.DAT_005e89fc = value,
            0x005e8a00 => self.DAT_005e8a00 = value as Ptr,
            0x005e8a04 => self.DAT_005e8a04 = value as Ptr,
            0x005e8a08 => self.DAT_005e8a08 = value as Ptr,
            0x005e8a0c => self.DAT_005e8a0c = value as Ptr,
            0x005e8a10 => self.DAT_005e8a10 = value as Ptr,
            0x005e8a14 => self.DAT_005e8a14 = value as Ptr,
            0x005e8a18 => self.DAT_005e8a18 = value,
            0x005e8a1c => self.DAT_005e8a1c = value as Ptr,
            0x005e8a20 => self.DAT_005e8a20 = value as Ptr,
            0x005e8a24 => self.DAT_005e8a24 = value as Ptr,
            0x005e8a28 => self.DAT_005e8a28 = value as Ptr,
            0x005e8a2c => self.DAT_005e8a2c = value as Ptr,
            0x005e8a30 => self.DAT_005e8a30 = value as Ptr,
            0x005e8a34 => self.DAT_005e8a34 = value as Ptr,
            0x005e8a38 => self.DAT_005e8a38 = value as Ptr,
            0x005e8a3c => self.DAT_005e8a3c = value,
            0x005e8a40 => self.DAT_005e8a40 = value as Ptr,
            0x005e8a44 => self.DAT_005e8a44 = value as Ptr,
            0x005e8a48 => self.DAT_005e8a48 = value as Ptr,
            0x005e8a4c => self.DAT_005e8a4c = value as Ptr,
            0x005e8a50 => self.DAT_005e8a50 = value as Ptr,
            0x005e8a54 => self.DAT_005e8a54 = value as Ptr,
            0x005e8a58 => self.DAT_005e8a58 = value as Ptr,
            0x005e8a5c => self.DAT_005e8a5c = value as Ptr,
            0x005e8a60 => self.DAT_005e8a60 = value as Ptr,
            0x005e8a64 => self.DAT_005e8a64 = value as Ptr,
            0x005e8a68 => self.DAT_005e8a68 = value,
            0x005e8a6c => self.DAT_005e8a6c = value as Ptr,
            0x005e8a70 => self.DAT_005e8a70 = value,
            0x005e8a74 => self.DAT_005e8a74 = value as Ptr,
            0x005e8a78 => self.DAT_005e8a78 = value as Ptr,
            0x005e8a7c => self.DAT_005e8a7c = value,
            0x005e8a80 => self.DAT_005e8a80 = value as Ptr,
            0x005e8a84 => self.DAT_005e8a84 = value as Ptr,
            0x005e8a88 => self.DAT_005e8a88 = value as Ptr,
            0x005e8a8c => self.DAT_005e8a8c = value as Ptr,
            0x005e8a90 => self.DAT_005e8a90 = value as Ptr,
            0x005e8a94 => self.DAT_005e8a94 = value,
            0x005e8a98 => self.DAT_005e8a98 = value as Ptr,
            0x005e8a9c => self.DAT_005e8a9c = value as Ptr,
            0x005e8aa0 => self.DAT_005e8aa0 = value as Ptr,
            0x005e8aa4 => self.DAT_005e8aa4 = value as Ptr,
            0x005e8aa8 => self.DAT_005e8aa8 = value as Ptr,
            0x005e8aac => self.DAT_005e8aac = value as Ptr,
            0x005e8ab0 => self.DAT_005e8ab0 = value as Ptr,
            0x005e8ab4 => self.DAT_005e8ab4 = value as Ptr,
            0x005e8ab8 => self.DAT_005e8ab8 = value as Ptr,
            0x005e8abc => self.DAT_005e8abc = value as Ptr,
            0x005e8ac0 => self.DAT_005e8ac0 = value as Ptr,
            0x005e8ac4 => self.DAT_005e8ac4 = value,
            0x005e8ac8 => self.DAT_005e8ac8 = value as Ptr,
            0x005e8acc => self.DAT_005e8acc = value,
            0x005e8ad0 => self.DAT_005e8ad0 = value as Ptr,
            0x005e8ad4 => self.DAT_005e8ad4 = value as Ptr,
            0x005e8ad8 => self.DAT_005e8ad8 = value as Ptr,
            0x005e8adc => self.DAT_005e8adc = value as Ptr,
            0x005e8ae0 => self.DAT_005e8ae0 = value as Ptr,
            0x005e8ae4 => self.DAT_005e8ae4 = value as Ptr,
            0x005e8ae8 => self.DAT_005e8ae8 = value as Ptr,
            0x005e8aec => self.DAT_005e8aec = value as Ptr,
            0x005e8af0 => self.DAT_005e8af0 = value,
            0x005e8af4 => self.DAT_005e8af4 = value as Ptr,
            0x005e8af8 => self.DAT_005e8af8 = value as Ptr,
            0x005e8afc => self.DAT_005e8afc = value as Ptr,
            0x005e8b00 => self.DAT_005e8b00 = value as Ptr,
            0x005e8b04 => self.DAT_005e8b04 = value as Ptr,
            0x005e8b08 => self.DAT_005e8b08 = value as Ptr,
            0x005e8b0c => self.DAT_005e8b0c = value as Ptr,
            0x005e8b10 => self.DAT_005e8b10 = value as Ptr,
            0x005e8b14 => self.DAT_005e8b14 = value as Ptr,
            0x005e8b18 => self.DAT_005e8b18 = value as Ptr,
            0x005e8b1c => self.DAT_005e8b1c = value,
            0x005e8b20 => self.DAT_005e8b20 = value,
            0x005e8b24 => self.DAT_005e8b24 = value,
            0x005e8b28 => self.DAT_005e8b28 = value,
            0x005e8b2c => self.DAT_005e8b2c = value as Ptr,
            0x005e8b30 => self.DAT_005e8b30 = value as Ptr,
            0x005e8b34 => self.DAT_005e8b34 = value as Ptr,
            0x005e8b38 => self.DAT_005e8b38 = value as Ptr,
            0x005e8b3c => self.DAT_005e8b3c = value as Ptr,
            0x005e8b40 => self.DAT_005e8b40 = value,
            0x005e8b44 => self.DAT_005e8b44 = value as Ptr,
            0x005e8b48 => self.DAT_005e8b48 = value as Ptr,
            0x005e8b4c => self.DAT_005e8b4c = value as Ptr,
            0x005e8b50 => self.DAT_005e8b50 = value as Ptr,
            0x005e8b54 => self.DAT_005e8b54 = value as Ptr,
            0x005e8b58 => self.DAT_005e8b58 = value as Ptr,
            0x005e8b5c => self.DAT_005e8b5c = value,
            0x005e8b60 => self.DAT_005e8b60 = value as Ptr,
            0x005e8b64 => self.DAT_005e8b64 = value as Ptr,
            0x005e8b68 => self.DAT_005e8b68 = value,
            0x005e8b6c => self.DAT_005e8b6c = value,
            0x005e8b70 => self.DAT_005e8b70 = value as Ptr,
            0x005e8b74 => self.DAT_005e8b74 = value as Ptr,
            0x005e8b78 => self.DAT_005e8b78 = value as Ptr,
            0x005e8b7c => self.DAT_005e8b7c = value as Ptr,
            0x005e8b80 => self.DAT_005e8b80 = value as Ptr,
            0x005e8b84 => self.DAT_005e8b84 = value as Ptr,
            0x005e8b88 => self.DAT_005e8b88 = value as Ptr,
            0x005e8b8c => self.DAT_005e8b8c = value as Ptr,
            0x005e8b90 => self.DAT_005e8b90 = value as Ptr,
            0x005e8b94 => self.DAT_005e8b94 = value as Ptr,
            0x005e8b98 => self.DAT_005e8b98 = value,
            0x005e8b9c => self.DAT_005e8b9c = value,
            0x005e8ba0 => self.DAT_005e8ba0 = value,
            0x005e8ba4 => self.DAT_005e8ba4 = value as Ptr,
            0x005e8ba8 => self.DAT_005e8ba8 = value as Ptr,
            0x005e8bac => self.DAT_005e8bac = value as Ptr,
            0x005e8bb0 => self.DAT_005e8bb0 = value as Ptr,
            0x005e8bb4 => self.DAT_005e8bb4 = value as Ptr,
            0x005e8bb8 => self.DAT_005e8bb8 = value as Ptr,
            0x005e8bbc => self.DAT_005e8bbc = value as Ptr,
            0x005e8bc0 => self.DAT_005e8bc0 = value as Ptr,
            0x005e8bc4 => self.DAT_005e8bc4 = value as Ptr,
            0x005e8bc8 => self.DAT_005e8bc8 = value,
            0x005e8bcc => self.DAT_005e8bcc = value as Ptr,
            0x005e8bd0 => self.DAT_005e8bd0 = value as Ptr,
            0x005e8bd4 => self.DAT_005e8bd4 = value as Ptr,
            0x005e8bd8 => self.DAT_005e8bd8 = value as Ptr,
            0x005e8bdc => self.DAT_005e8bdc = value,
            0x005e8be0 => self.DAT_005e8be0 = value as Ptr,
            0x005e8be4 => self.DAT_005e8be4 = value as Ptr,
            0x005e8be8 => self.DAT_005e8be8 = value as Ptr,
            0x005e8bec => self.DAT_005e8bec = value as Ptr,
            0x005e8bf0 => self.DAT_005e8bf0 = value as Ptr,
            0x005e8bf4 => self.DAT_005e8bf4 = value as Ptr,
            0x005e8bf8 => self.DAT_005e8bf8 = value,
            0x005e8bfc => self.DAT_005e8bfc = value as Ptr,
            0x005e8c00 => self.DAT_005e8c00 = value as Ptr,
            0x005e8c04 => self.DAT_005e8c04 = value as Ptr,
            0x005e8c08 => self.DAT_005e8c08 = value as Ptr,
            0x005e8c0c => self.DAT_005e8c0c = value as Ptr,
            0x005e8c10 => self.DAT_005e8c10 = value,
            0x005e8c14 => self.DAT_005e8c14 = value as Ptr,
            0x005e8c18 => self.DAT_005e8c18 = value as Ptr,
            0x005e8c1c => self.DAT_005e8c1c = value as Ptr,
            0x005e8c20 => self.DAT_005e8c20 = value as Ptr,
            0x005e8c24 => self.DAT_005e8c24 = value as Ptr,
            0x005e8c28 => self.DAT_005e8c28 = value,
            0x005e8c2c => self.DAT_005e8c2c = value as Ptr,
            0x005e8c30 => self.DAT_005e8c30 = value as Ptr,
            0x005e8c34 => self.DAT_005e8c34 = value,
            0x005e8c38 => self.DAT_005e8c38 = value,
            0x005e8c3c => self.DAT_005e8c3c = value as Ptr,
            0x005e8c40 => self.DAT_005e8c40 = value,
            0x005e8c44 => self.DAT_005e8c44 = value as Ptr,
            0x005e8c48 => self.DAT_005e8c48 = value,
            0x005e8c4c => self.DAT_005e8c4c = value as Ptr,
            0x005e8c50 => self.DAT_005e8c50 = value as Ptr,
            0x005e8c54 => self.DAT_005e8c54 = value as Ptr,
            0x005e8c58 => self.DAT_005e8c58 = value as Ptr,
            0x005e8c5c => self.DAT_005e8c5c = value as Ptr,
            0x005e8c60 => self.DAT_005e8c60 = value as Ptr,
            0x005e8c64 => self.DAT_005e8c64 = value as Ptr,
            0x005e8c68 => self.DAT_005e8c68 = value as Ptr,
            0x005e8c6c => self.DAT_005e8c6c = value,
            0x005e8c70 => self.DAT_005e8c70 = value as Ptr,
            0x005e8c74 => self.DAT_005e8c74 = value as Ptr,
            0x005e8c78 => self.DAT_005e8c78 = value as Ptr,
            0x005e8c7c => self.DAT_005e8c7c = value as Ptr,
            0x005e8c80 => self.DAT_005e8c80 = value as Ptr,
            0x005e8c84 => self.DAT_005e8c84 = value as Ptr,
            0x005e8c88 => self.DAT_005e8c88 = value as Ptr,
            0x005e8c8c => self.DAT_005e8c8c = value,
            0x005e8c90 => self.DAT_005e8c90 = value as Ptr,
            0x005e8c94 => self.DAT_005e8c94 = value as Ptr,
            0x005e8c98 => self.DAT_005e8c98 = value as Ptr,
            0x005e8c9c => self.DAT_005e8c9c = value,
            0x005e8ca0 => self.DAT_005e8ca0 = value as Ptr,
            0x005e8ca4 => self.DAT_005e8ca4 = value as Ptr,
            0x005e8ca8 => self.DAT_005e8ca8 = value as Ptr,
            0x005e8cac => self.DAT_005e8cac = value as Ptr,
            0x005e8cb0 => self.DAT_005e8cb0 = value as Ptr,
            0x005e8cb4 => self.DAT_005e8cb4 = value as Ptr,
            0x005e8cb8 => self.DAT_005e8cb8 = value as Ptr,
            0x005e8cbc => self.DAT_005e8cbc = value as Ptr,
            0x005e8cc0 => self.DAT_005e8cc0 = value as Ptr,
            0x005e8cc4 => self.DAT_005e8cc4 = value as Ptr,
            0x005e8cc8 => self.DAT_005e8cc8 = value as Ptr,
            0x005e8ccc => self.DAT_005e8ccc = value as Ptr,
            0x005e8cd0 => self.DAT_005e8cd0 = value as Ptr,
            0x005e8cd4 => self.DAT_005e8cd4 = value,
            0x005e8cd8 => self.DAT_005e8cd8 = value as Ptr,
            0x005e8cdc => self.DAT_005e8cdc = value as Ptr,
            0x005e8ce0 => self.DAT_005e8ce0 = value as Ptr,
            0x005e8ce4 => self.DAT_005e8ce4 = value as Ptr,
            0x005e8ce8 => self.DAT_005e8ce8 = value as Ptr,
            0x005e8cec => self.DAT_005e8cec = value as Ptr,
            0x005e8cf0 => self.DAT_005e8cf0 = value as Ptr,
            0x005e8cf4 => self.DAT_005e8cf4 = value as Ptr,
            0x005e8cf8 => self.DAT_005e8cf8 = value as Ptr,
            0x005e8cfc => self.DAT_005e8cfc = value as Ptr,
            0x005e8d00 => self.DAT_005e8d00 = value as Ptr,
            0x005e8d04 => self.DAT_005e8d04 = value as Ptr,
            0x005e8d08 => self.DAT_005e8d08 = value,
            0x005e8d0c => self.DAT_005e8d0c = value as Ptr,
            0x005e8d10 => self.DAT_005e8d10 = value,
            0x005e8d14 => self.DAT_005e8d14 = value,
            0x005e8d18 => self.DAT_005e8d18 = value as Ptr,
            0x005e8d1c => self.DAT_005e8d1c = value as Ptr,
            0x005e8d20 => self.DAT_005e8d20 = value as Ptr,
            0x005e8d24 => self.DAT_005e8d24 = value as Ptr,
            0x005e8d28 => self.DAT_005e8d28 = value as Ptr,
            0x005e8d2c => self.DAT_005e8d2c = value,
            0x005e8d30 => self.DAT_005e8d30 = value as Ptr,
            0x005e8d34 => self.DAT_005e8d34 = value,
            0x005e8d38 => self.DAT_005e8d38 = value as Ptr,
            0x005e8d3c => self.DAT_005e8d3c = value as Ptr,
            0x005e8d40 => self.DAT_005e8d40 = value as Ptr,
            0x005e8d44 => self.DAT_005e8d44 = value,
            0x005e8d48 => self.DAT_005e8d48 = value as Ptr,
            0x005e8d4c => self.DAT_005e8d4c = value as Ptr,
            0x005e8d50 => self.DAT_005e8d50 = value as Ptr,
            0x005e8d54 => self.DAT_005e8d54 = value,
            0x005e8d58 => self.DAT_005e8d58 = value as Ptr,
            0x005e8d5c => self.DAT_005e8d5c = value as Ptr,
            0x005e8d60 => self.DAT_005e8d60 = value as Ptr,
            0x005e8d64 => self.DAT_005e8d64 = value as Ptr,
            0x005e8d68 => self.DAT_005e8d68 = value as Ptr,
            0x005e8d6c => self.DAT_005e8d6c = value as Ptr,
            0x005e8d70 => self.DAT_005e8d70 = value as Ptr,
            0x005e8d74 => self.DAT_005e8d74 = value,
            0x005e8d78 => self.DAT_005e8d78 = value,
            0x005e8d7c => self.DAT_005e8d7c = value as Ptr,
            0x005e8d80 => self.DAT_005e8d80 = value as Ptr,
            0x005e8d84 => self.DAT_005e8d84 = value as Ptr,
            0x005e8d88 => self.DAT_005e8d88 = value as Ptr,
            0x005e8d8c => self.DAT_005e8d8c = value,
            0x005e8d90 => self.DAT_005e8d90 = value as Ptr,
            0x005e8d94 => self.DAT_005e8d94 = value,
            0x005e8d98 => self.DAT_005e8d98 = value as Ptr,
            0x005e8d9c => self.DAT_005e8d9c = value,
            0x005e8da0 => self.DAT_005e8da0 = value as Ptr,
            0x005e8da4 => self.DAT_005e8da4 = value as Ptr,
            0x005e8da8 => self.DAT_005e8da8 = value as Ptr,
            0x005e8dac => self.DAT_005e8dac = value as Ptr,
            0x005e8db0 => self.DAT_005e8db0 = value as Ptr,
            0x005e8db4 => self.DAT_005e8db4 = value as Ptr,
            0x005e8db8 => self.DAT_005e8db8 = value as Ptr,
            0x005e8dbc => self.DAT_005e8dbc = value as Ptr,
            0x005e8dc0 => self.DAT_005e8dc0 = value as Ptr,
            0x005e8dc4 => self.DAT_005e8dc4 = value as Ptr,
            0x005e8dc8 => self.DAT_005e8dc8 = value as Ptr,
            0x005e8dcc => self.DAT_005e8dcc = value as Ptr,
            0x005e8dd0 => self.DAT_005e8dd0 = value,
            0x005e8dd4 => self.DAT_005e8dd4 = value as Ptr,
            0x005e8dd8 => self.DAT_005e8dd8 = value as Ptr,
            0x005e8ddc => self.DAT_005e8ddc = value as Ptr,
            0x005e8de0 => self.DAT_005e8de0 = value,
            0x005e8de4 => self.DAT_005e8de4 = value,
            0x005e8de8 => self.DAT_005e8de8 = value as Ptr,
            0x005e8dec => self.DAT_005e8dec = value as Ptr,
            0x005e8df0 => self.DAT_005e8df0 = value,
            0x005e8df4 => self.DAT_005e8df4 = value as Ptr,
            0x005e8df8 => self.DAT_005e8df8 = value as Ptr,
            0x005e8dfc => self.DAT_005e8dfc = value as Ptr,
            0x005e8e00 => self.DAT_005e8e00 = value as Ptr,
            0x005e8e04 => self.DAT_005e8e04 = value as Ptr,
            0x005e8e08 => self.DAT_005e8e08 = value as Ptr,
            0x005e8e0c => self.DAT_005e8e0c = value as Ptr,
            0x005e8e10 => self.DAT_005e8e10 = value,
            0x005e8e14 => self.DAT_005e8e14 = value,
            0x005e8e18 => self.DAT_005e8e18 = value as Ptr,
            0x005e8e1c => self.DAT_005e8e1c = value as Ptr,
            0x005e8e20 => self.DAT_005e8e20 = value as Ptr,
            0x005e8e24 => self.DAT_005e8e24 = value,
            0x005e8e28 => self.DAT_005e8e28 = value as Ptr,
            0x005e8e2c => self.DAT_005e8e2c = value as Ptr,
            0x005e8e30 => self.DAT_005e8e30 = value as Ptr,
            0x005e8e34 => self.DAT_005e8e34 = value as Ptr,
            0x005e8e38 => self.DAT_005e8e38 = value as Ptr,
            0x005e8e3c => self.DAT_005e8e3c = value as Ptr,
            0x005e8e40 => self.DAT_005e8e40 = value as Ptr,
            0x005e8e44 => self.DAT_005e8e44 = value as Ptr,
            0x005e8e48 => self.DAT_005e8e48 = value as Ptr,
            0x005e8e4c => self.DAT_005e8e4c = value as Ptr,
            0x005e8e50 => self.DAT_005e8e50 = value as Ptr,
            0x005e8e54 => self.DAT_005e8e54 = value,
            0x005e8e58 => self.DAT_005e8e58 = value as Ptr,
            0x005e8e5c => self.DAT_005e8e5c = value as Ptr,
            0x005e8e60 => self.DAT_005e8e60 = value as Ptr,
            0x005e8e64 => self.DAT_005e8e64 = value,
            0x005e8e68 => self.DAT_005e8e68 = value,
            0x005e8e6c => self.DAT_005e8e6c = value as Ptr,
            0x005e8e70 => self.DAT_005e8e70 = value as Ptr,
            0x005e8e74 => self.DAT_005e8e74 = value as Ptr,
            0x005e8e78 => self.DAT_005e8e78 = value as Ptr,
            0x005e8e7c => self.DAT_005e8e7c = value as Ptr,
            0x005e8e80 => self.DAT_005e8e80 = value as Ptr,
            0x005e8e84 => self.DAT_005e8e84 = value,
            0x005e8e88 => self.DAT_005e8e88 = value as Ptr,
            0x005e8e8c => self.DAT_005e8e8c = value as Ptr,
            0x005e8e90 => self.DAT_005e8e90 = value,
            0x005e8e94 => self.DAT_005e8e94 = value,
            0x005e8e98 => self.DAT_005e8e98 = value,
            0x005e8e9c => self.DAT_005e8e9c = value as Ptr,
            0x005e8ea0 => self.DAT_005e8ea0 = value as Ptr,
            0x005e8ea4 => self.DAT_005e8ea4 = value,
            0x005e8ea8 => self.DAT_005e8ea8 = value as Ptr,
            0x005e8eac => self.DAT_005e8eac = value as Ptr,
            0x005e8eb0 => self.DAT_005e8eb0 = value as Ptr,
            0x005e8eb4 => self.DAT_005e8eb4 = value as Ptr,
            0x005e8eb8 => self.DAT_005e8eb8 = value as Ptr,
            0x005e8ebc => self.DAT_005e8ebc = value as Ptr,
            0x005e8ec0 => self.DAT_005e8ec0 = value as Ptr,
            0x005e8ec4 => self.DAT_005e8ec4 = value,
            0x005e8ec8 => self.DAT_005e8ec8 = value as Ptr,
            0x005e8ecc => self.DAT_005e8ecc = value as Ptr,
            0x005e8ed0 => self.DAT_005e8ed0 = value as Ptr,
            0x005e8ed4 => self.DAT_005e8ed4 = value as Ptr,
            0x005e8ed8 => self.DAT_005e8ed8 = value as Ptr,
            0x005e8edc => self.DAT_005e8edc = value,
            0x005e8ee0 => self.DAT_005e8ee0 = value as Ptr,
            0x005e8ee4 => self.DAT_005e8ee4 = value as Ptr,
            0x005e8ee8 => self.DAT_005e8ee8 = value as Ptr,
            0x005e8eec => self.DAT_005e8eec = value as Ptr,
            0x005e8ef0 => self.DAT_005e8ef0 = value as Ptr,
            0x005e8ef4 => self.DAT_005e8ef4 = value,
            0x005e8ef8 => self.DAT_005e8ef8 = value as Ptr,
            0x005e8efc => self.DAT_005e8efc = value as Ptr,
            0x005e8f00 => self.DAT_005e8f00 = value as Ptr,
            0x005e8f04 => self.DAT_005e8f04 = value as Ptr,
            0x005e8f08 => self.DAT_005e8f08 = value as Ptr,
            0x005e8f0c => self.DAT_005e8f0c = value,
            0x005e8f10 => self.DAT_005e8f10 = value as Ptr,
            _ => panic!("no resource global at {addr:08x}"),
        }
    }

    /// Reads the global at `addr` (images/fonts as their pointer value).
    pub fn get(&self, addr: u32) -> i32 {
        match addr {
            0x005e89fc => self.DAT_005e89fc,
            0x005e8a00 => self.DAT_005e8a00 as i32,
            0x005e8a04 => self.DAT_005e8a04 as i32,
            0x005e8a08 => self.DAT_005e8a08 as i32,
            0x005e8a0c => self.DAT_005e8a0c as i32,
            0x005e8a10 => self.DAT_005e8a10 as i32,
            0x005e8a14 => self.DAT_005e8a14 as i32,
            0x005e8a18 => self.DAT_005e8a18,
            0x005e8a1c => self.DAT_005e8a1c as i32,
            0x005e8a20 => self.DAT_005e8a20 as i32,
            0x005e8a24 => self.DAT_005e8a24 as i32,
            0x005e8a28 => self.DAT_005e8a28 as i32,
            0x005e8a2c => self.DAT_005e8a2c as i32,
            0x005e8a30 => self.DAT_005e8a30 as i32,
            0x005e8a34 => self.DAT_005e8a34 as i32,
            0x005e8a38 => self.DAT_005e8a38 as i32,
            0x005e8a3c => self.DAT_005e8a3c,
            0x005e8a40 => self.DAT_005e8a40 as i32,
            0x005e8a44 => self.DAT_005e8a44 as i32,
            0x005e8a48 => self.DAT_005e8a48 as i32,
            0x005e8a4c => self.DAT_005e8a4c as i32,
            0x005e8a50 => self.DAT_005e8a50 as i32,
            0x005e8a54 => self.DAT_005e8a54 as i32,
            0x005e8a58 => self.DAT_005e8a58 as i32,
            0x005e8a5c => self.DAT_005e8a5c as i32,
            0x005e8a60 => self.DAT_005e8a60 as i32,
            0x005e8a64 => self.DAT_005e8a64 as i32,
            0x005e8a68 => self.DAT_005e8a68,
            0x005e8a6c => self.DAT_005e8a6c as i32,
            0x005e8a70 => self.DAT_005e8a70,
            0x005e8a74 => self.DAT_005e8a74 as i32,
            0x005e8a78 => self.DAT_005e8a78 as i32,
            0x005e8a7c => self.DAT_005e8a7c,
            0x005e8a80 => self.DAT_005e8a80 as i32,
            0x005e8a84 => self.DAT_005e8a84 as i32,
            0x005e8a88 => self.DAT_005e8a88 as i32,
            0x005e8a8c => self.DAT_005e8a8c as i32,
            0x005e8a90 => self.DAT_005e8a90 as i32,
            0x005e8a94 => self.DAT_005e8a94,
            0x005e8a98 => self.DAT_005e8a98 as i32,
            0x005e8a9c => self.DAT_005e8a9c as i32,
            0x005e8aa0 => self.DAT_005e8aa0 as i32,
            0x005e8aa4 => self.DAT_005e8aa4 as i32,
            0x005e8aa8 => self.DAT_005e8aa8 as i32,
            0x005e8aac => self.DAT_005e8aac as i32,
            0x005e8ab0 => self.DAT_005e8ab0 as i32,
            0x005e8ab4 => self.DAT_005e8ab4 as i32,
            0x005e8ab8 => self.DAT_005e8ab8 as i32,
            0x005e8abc => self.DAT_005e8abc as i32,
            0x005e8ac0 => self.DAT_005e8ac0 as i32,
            0x005e8ac4 => self.DAT_005e8ac4,
            0x005e8ac8 => self.DAT_005e8ac8 as i32,
            0x005e8acc => self.DAT_005e8acc,
            0x005e8ad0 => self.DAT_005e8ad0 as i32,
            0x005e8ad4 => self.DAT_005e8ad4 as i32,
            0x005e8ad8 => self.DAT_005e8ad8 as i32,
            0x005e8adc => self.DAT_005e8adc as i32,
            0x005e8ae0 => self.DAT_005e8ae0 as i32,
            0x005e8ae4 => self.DAT_005e8ae4 as i32,
            0x005e8ae8 => self.DAT_005e8ae8 as i32,
            0x005e8aec => self.DAT_005e8aec as i32,
            0x005e8af0 => self.DAT_005e8af0,
            0x005e8af4 => self.DAT_005e8af4 as i32,
            0x005e8af8 => self.DAT_005e8af8 as i32,
            0x005e8afc => self.DAT_005e8afc as i32,
            0x005e8b00 => self.DAT_005e8b00 as i32,
            0x005e8b04 => self.DAT_005e8b04 as i32,
            0x005e8b08 => self.DAT_005e8b08 as i32,
            0x005e8b0c => self.DAT_005e8b0c as i32,
            0x005e8b10 => self.DAT_005e8b10 as i32,
            0x005e8b14 => self.DAT_005e8b14 as i32,
            0x005e8b18 => self.DAT_005e8b18 as i32,
            0x005e8b1c => self.DAT_005e8b1c,
            0x005e8b20 => self.DAT_005e8b20,
            0x005e8b24 => self.DAT_005e8b24,
            0x005e8b28 => self.DAT_005e8b28,
            0x005e8b2c => self.DAT_005e8b2c as i32,
            0x005e8b30 => self.DAT_005e8b30 as i32,
            0x005e8b34 => self.DAT_005e8b34 as i32,
            0x005e8b38 => self.DAT_005e8b38 as i32,
            0x005e8b3c => self.DAT_005e8b3c as i32,
            0x005e8b40 => self.DAT_005e8b40,
            0x005e8b44 => self.DAT_005e8b44 as i32,
            0x005e8b48 => self.DAT_005e8b48 as i32,
            0x005e8b4c => self.DAT_005e8b4c as i32,
            0x005e8b50 => self.DAT_005e8b50 as i32,
            0x005e8b54 => self.DAT_005e8b54 as i32,
            0x005e8b58 => self.DAT_005e8b58 as i32,
            0x005e8b5c => self.DAT_005e8b5c,
            0x005e8b60 => self.DAT_005e8b60 as i32,
            0x005e8b64 => self.DAT_005e8b64 as i32,
            0x005e8b68 => self.DAT_005e8b68,
            0x005e8b6c => self.DAT_005e8b6c,
            0x005e8b70 => self.DAT_005e8b70 as i32,
            0x005e8b74 => self.DAT_005e8b74 as i32,
            0x005e8b78 => self.DAT_005e8b78 as i32,
            0x005e8b7c => self.DAT_005e8b7c as i32,
            0x005e8b80 => self.DAT_005e8b80 as i32,
            0x005e8b84 => self.DAT_005e8b84 as i32,
            0x005e8b88 => self.DAT_005e8b88 as i32,
            0x005e8b8c => self.DAT_005e8b8c as i32,
            0x005e8b90 => self.DAT_005e8b90 as i32,
            0x005e8b94 => self.DAT_005e8b94 as i32,
            0x005e8b98 => self.DAT_005e8b98,
            0x005e8b9c => self.DAT_005e8b9c,
            0x005e8ba0 => self.DAT_005e8ba0,
            0x005e8ba4 => self.DAT_005e8ba4 as i32,
            0x005e8ba8 => self.DAT_005e8ba8 as i32,
            0x005e8bac => self.DAT_005e8bac as i32,
            0x005e8bb0 => self.DAT_005e8bb0 as i32,
            0x005e8bb4 => self.DAT_005e8bb4 as i32,
            0x005e8bb8 => self.DAT_005e8bb8 as i32,
            0x005e8bbc => self.DAT_005e8bbc as i32,
            0x005e8bc0 => self.DAT_005e8bc0 as i32,
            0x005e8bc4 => self.DAT_005e8bc4 as i32,
            0x005e8bc8 => self.DAT_005e8bc8,
            0x005e8bcc => self.DAT_005e8bcc as i32,
            0x005e8bd0 => self.DAT_005e8bd0 as i32,
            0x005e8bd4 => self.DAT_005e8bd4 as i32,
            0x005e8bd8 => self.DAT_005e8bd8 as i32,
            0x005e8bdc => self.DAT_005e8bdc,
            0x005e8be0 => self.DAT_005e8be0 as i32,
            0x005e8be4 => self.DAT_005e8be4 as i32,
            0x005e8be8 => self.DAT_005e8be8 as i32,
            0x005e8bec => self.DAT_005e8bec as i32,
            0x005e8bf0 => self.DAT_005e8bf0 as i32,
            0x005e8bf4 => self.DAT_005e8bf4 as i32,
            0x005e8bf8 => self.DAT_005e8bf8,
            0x005e8bfc => self.DAT_005e8bfc as i32,
            0x005e8c00 => self.DAT_005e8c00 as i32,
            0x005e8c04 => self.DAT_005e8c04 as i32,
            0x005e8c08 => self.DAT_005e8c08 as i32,
            0x005e8c0c => self.DAT_005e8c0c as i32,
            0x005e8c10 => self.DAT_005e8c10,
            0x005e8c14 => self.DAT_005e8c14 as i32,
            0x005e8c18 => self.DAT_005e8c18 as i32,
            0x005e8c1c => self.DAT_005e8c1c as i32,
            0x005e8c20 => self.DAT_005e8c20 as i32,
            0x005e8c24 => self.DAT_005e8c24 as i32,
            0x005e8c28 => self.DAT_005e8c28,
            0x005e8c2c => self.DAT_005e8c2c as i32,
            0x005e8c30 => self.DAT_005e8c30 as i32,
            0x005e8c34 => self.DAT_005e8c34,
            0x005e8c38 => self.DAT_005e8c38,
            0x005e8c3c => self.DAT_005e8c3c as i32,
            0x005e8c40 => self.DAT_005e8c40,
            0x005e8c44 => self.DAT_005e8c44 as i32,
            0x005e8c48 => self.DAT_005e8c48,
            0x005e8c4c => self.DAT_005e8c4c as i32,
            0x005e8c50 => self.DAT_005e8c50 as i32,
            0x005e8c54 => self.DAT_005e8c54 as i32,
            0x005e8c58 => self.DAT_005e8c58 as i32,
            0x005e8c5c => self.DAT_005e8c5c as i32,
            0x005e8c60 => self.DAT_005e8c60 as i32,
            0x005e8c64 => self.DAT_005e8c64 as i32,
            0x005e8c68 => self.DAT_005e8c68 as i32,
            0x005e8c6c => self.DAT_005e8c6c,
            0x005e8c70 => self.DAT_005e8c70 as i32,
            0x005e8c74 => self.DAT_005e8c74 as i32,
            0x005e8c78 => self.DAT_005e8c78 as i32,
            0x005e8c7c => self.DAT_005e8c7c as i32,
            0x005e8c80 => self.DAT_005e8c80 as i32,
            0x005e8c84 => self.DAT_005e8c84 as i32,
            0x005e8c88 => self.DAT_005e8c88 as i32,
            0x005e8c8c => self.DAT_005e8c8c,
            0x005e8c90 => self.DAT_005e8c90 as i32,
            0x005e8c94 => self.DAT_005e8c94 as i32,
            0x005e8c98 => self.DAT_005e8c98 as i32,
            0x005e8c9c => self.DAT_005e8c9c,
            0x005e8ca0 => self.DAT_005e8ca0 as i32,
            0x005e8ca4 => self.DAT_005e8ca4 as i32,
            0x005e8ca8 => self.DAT_005e8ca8 as i32,
            0x005e8cac => self.DAT_005e8cac as i32,
            0x005e8cb0 => self.DAT_005e8cb0 as i32,
            0x005e8cb4 => self.DAT_005e8cb4 as i32,
            0x005e8cb8 => self.DAT_005e8cb8 as i32,
            0x005e8cbc => self.DAT_005e8cbc as i32,
            0x005e8cc0 => self.DAT_005e8cc0 as i32,
            0x005e8cc4 => self.DAT_005e8cc4 as i32,
            0x005e8cc8 => self.DAT_005e8cc8 as i32,
            0x005e8ccc => self.DAT_005e8ccc as i32,
            0x005e8cd0 => self.DAT_005e8cd0 as i32,
            0x005e8cd4 => self.DAT_005e8cd4,
            0x005e8cd8 => self.DAT_005e8cd8 as i32,
            0x005e8cdc => self.DAT_005e8cdc as i32,
            0x005e8ce0 => self.DAT_005e8ce0 as i32,
            0x005e8ce4 => self.DAT_005e8ce4 as i32,
            0x005e8ce8 => self.DAT_005e8ce8 as i32,
            0x005e8cec => self.DAT_005e8cec as i32,
            0x005e8cf0 => self.DAT_005e8cf0 as i32,
            0x005e8cf4 => self.DAT_005e8cf4 as i32,
            0x005e8cf8 => self.DAT_005e8cf8 as i32,
            0x005e8cfc => self.DAT_005e8cfc as i32,
            0x005e8d00 => self.DAT_005e8d00 as i32,
            0x005e8d04 => self.DAT_005e8d04 as i32,
            0x005e8d08 => self.DAT_005e8d08,
            0x005e8d0c => self.DAT_005e8d0c as i32,
            0x005e8d10 => self.DAT_005e8d10,
            0x005e8d14 => self.DAT_005e8d14,
            0x005e8d18 => self.DAT_005e8d18 as i32,
            0x005e8d1c => self.DAT_005e8d1c as i32,
            0x005e8d20 => self.DAT_005e8d20 as i32,
            0x005e8d24 => self.DAT_005e8d24 as i32,
            0x005e8d28 => self.DAT_005e8d28 as i32,
            0x005e8d2c => self.DAT_005e8d2c,
            0x005e8d30 => self.DAT_005e8d30 as i32,
            0x005e8d34 => self.DAT_005e8d34,
            0x005e8d38 => self.DAT_005e8d38 as i32,
            0x005e8d3c => self.DAT_005e8d3c as i32,
            0x005e8d40 => self.DAT_005e8d40 as i32,
            0x005e8d44 => self.DAT_005e8d44,
            0x005e8d48 => self.DAT_005e8d48 as i32,
            0x005e8d4c => self.DAT_005e8d4c as i32,
            0x005e8d50 => self.DAT_005e8d50 as i32,
            0x005e8d54 => self.DAT_005e8d54,
            0x005e8d58 => self.DAT_005e8d58 as i32,
            0x005e8d5c => self.DAT_005e8d5c as i32,
            0x005e8d60 => self.DAT_005e8d60 as i32,
            0x005e8d64 => self.DAT_005e8d64 as i32,
            0x005e8d68 => self.DAT_005e8d68 as i32,
            0x005e8d6c => self.DAT_005e8d6c as i32,
            0x005e8d70 => self.DAT_005e8d70 as i32,
            0x005e8d74 => self.DAT_005e8d74,
            0x005e8d78 => self.DAT_005e8d78,
            0x005e8d7c => self.DAT_005e8d7c as i32,
            0x005e8d80 => self.DAT_005e8d80 as i32,
            0x005e8d84 => self.DAT_005e8d84 as i32,
            0x005e8d88 => self.DAT_005e8d88 as i32,
            0x005e8d8c => self.DAT_005e8d8c,
            0x005e8d90 => self.DAT_005e8d90 as i32,
            0x005e8d94 => self.DAT_005e8d94,
            0x005e8d98 => self.DAT_005e8d98 as i32,
            0x005e8d9c => self.DAT_005e8d9c,
            0x005e8da0 => self.DAT_005e8da0 as i32,
            0x005e8da4 => self.DAT_005e8da4 as i32,
            0x005e8da8 => self.DAT_005e8da8 as i32,
            0x005e8dac => self.DAT_005e8dac as i32,
            0x005e8db0 => self.DAT_005e8db0 as i32,
            0x005e8db4 => self.DAT_005e8db4 as i32,
            0x005e8db8 => self.DAT_005e8db8 as i32,
            0x005e8dbc => self.DAT_005e8dbc as i32,
            0x005e8dc0 => self.DAT_005e8dc0 as i32,
            0x005e8dc4 => self.DAT_005e8dc4 as i32,
            0x005e8dc8 => self.DAT_005e8dc8 as i32,
            0x005e8dcc => self.DAT_005e8dcc as i32,
            0x005e8dd0 => self.DAT_005e8dd0,
            0x005e8dd4 => self.DAT_005e8dd4 as i32,
            0x005e8dd8 => self.DAT_005e8dd8 as i32,
            0x005e8ddc => self.DAT_005e8ddc as i32,
            0x005e8de0 => self.DAT_005e8de0,
            0x005e8de4 => self.DAT_005e8de4,
            0x005e8de8 => self.DAT_005e8de8 as i32,
            0x005e8dec => self.DAT_005e8dec as i32,
            0x005e8df0 => self.DAT_005e8df0,
            0x005e8df4 => self.DAT_005e8df4 as i32,
            0x005e8df8 => self.DAT_005e8df8 as i32,
            0x005e8dfc => self.DAT_005e8dfc as i32,
            0x005e8e00 => self.DAT_005e8e00 as i32,
            0x005e8e04 => self.DAT_005e8e04 as i32,
            0x005e8e08 => self.DAT_005e8e08 as i32,
            0x005e8e0c => self.DAT_005e8e0c as i32,
            0x005e8e10 => self.DAT_005e8e10,
            0x005e8e14 => self.DAT_005e8e14,
            0x005e8e18 => self.DAT_005e8e18 as i32,
            0x005e8e1c => self.DAT_005e8e1c as i32,
            0x005e8e20 => self.DAT_005e8e20 as i32,
            0x005e8e24 => self.DAT_005e8e24,
            0x005e8e28 => self.DAT_005e8e28 as i32,
            0x005e8e2c => self.DAT_005e8e2c as i32,
            0x005e8e30 => self.DAT_005e8e30 as i32,
            0x005e8e34 => self.DAT_005e8e34 as i32,
            0x005e8e38 => self.DAT_005e8e38 as i32,
            0x005e8e3c => self.DAT_005e8e3c as i32,
            0x005e8e40 => self.DAT_005e8e40 as i32,
            0x005e8e44 => self.DAT_005e8e44 as i32,
            0x005e8e48 => self.DAT_005e8e48 as i32,
            0x005e8e4c => self.DAT_005e8e4c as i32,
            0x005e8e50 => self.DAT_005e8e50 as i32,
            0x005e8e54 => self.DAT_005e8e54,
            0x005e8e58 => self.DAT_005e8e58 as i32,
            0x005e8e5c => self.DAT_005e8e5c as i32,
            0x005e8e60 => self.DAT_005e8e60 as i32,
            0x005e8e64 => self.DAT_005e8e64,
            0x005e8e68 => self.DAT_005e8e68,
            0x005e8e6c => self.DAT_005e8e6c as i32,
            0x005e8e70 => self.DAT_005e8e70 as i32,
            0x005e8e74 => self.DAT_005e8e74 as i32,
            0x005e8e78 => self.DAT_005e8e78 as i32,
            0x005e8e7c => self.DAT_005e8e7c as i32,
            0x005e8e80 => self.DAT_005e8e80 as i32,
            0x005e8e84 => self.DAT_005e8e84,
            0x005e8e88 => self.DAT_005e8e88 as i32,
            0x005e8e8c => self.DAT_005e8e8c as i32,
            0x005e8e90 => self.DAT_005e8e90,
            0x005e8e94 => self.DAT_005e8e94,
            0x005e8e98 => self.DAT_005e8e98,
            0x005e8e9c => self.DAT_005e8e9c as i32,
            0x005e8ea0 => self.DAT_005e8ea0 as i32,
            0x005e8ea4 => self.DAT_005e8ea4,
            0x005e8ea8 => self.DAT_005e8ea8 as i32,
            0x005e8eac => self.DAT_005e8eac as i32,
            0x005e8eb0 => self.DAT_005e8eb0 as i32,
            0x005e8eb4 => self.DAT_005e8eb4 as i32,
            0x005e8eb8 => self.DAT_005e8eb8 as i32,
            0x005e8ebc => self.DAT_005e8ebc as i32,
            0x005e8ec0 => self.DAT_005e8ec0 as i32,
            0x005e8ec4 => self.DAT_005e8ec4,
            0x005e8ec8 => self.DAT_005e8ec8 as i32,
            0x005e8ecc => self.DAT_005e8ecc as i32,
            0x005e8ed0 => self.DAT_005e8ed0 as i32,
            0x005e8ed4 => self.DAT_005e8ed4 as i32,
            0x005e8ed8 => self.DAT_005e8ed8 as i32,
            0x005e8edc => self.DAT_005e8edc,
            0x005e8ee0 => self.DAT_005e8ee0 as i32,
            0x005e8ee4 => self.DAT_005e8ee4 as i32,
            0x005e8ee8 => self.DAT_005e8ee8 as i32,
            0x005e8eec => self.DAT_005e8eec as i32,
            0x005e8ef0 => self.DAT_005e8ef0 as i32,
            0x005e8ef4 => self.DAT_005e8ef4,
            0x005e8ef8 => self.DAT_005e8ef8 as i32,
            0x005e8efc => self.DAT_005e8efc as i32,
            0x005e8f00 => self.DAT_005e8f00 as i32,
            0x005e8f04 => self.DAT_005e8f04 as i32,
            0x005e8f08 => self.DAT_005e8f08 as i32,
            0x005e8f0c => self.DAT_005e8f0c,
            0x005e8f10 => self.DAT_005e8f10 as i32,
            _ => panic!("no resource global at {addr:08x}"),
        }
    }
}

/// `PTR_DAT_005e0a10`: the address of the global of each numeric resource id
/// (what `GetIntById` / `GetImageById`, e.g. `FUN_005016a0`, index).
pub const RES_BY_ID: [u32; 326] = [
    0x005e8a4c, // 0: IMAGE_CURSOR_POINTER
    0x005e8e20, // 1: IMAGE_CURSOR_HAND
    0x005e8a80, // 2: IMAGE_CURSOR_DRAGGING
    0x005e8b50, // 3: IMAGE_CURSOR_TEXT
    0x005e8d80, // 4: IMAGE_BLANK
    0x005e8bec, // 5: IMAGE_TITLEPAGE
    0x005e8e80, // 6: IMAGE_TITLEPAGEMASK
    0x005e8b00, // 7: IMAGE_LOADERBAR
    0x005e8c30, // 8: IMAGE_LOADERBAROVER
    0x005e8f10, // 9: IMAGE_LOADERBARLOADING
    0x005e8d6c, // 10: IMAGE_LOADERPLAY
    0x005e8cf0, // 11: FONT_JUNGLEFEVER10OUTLINE
    0x005e8e40, // 12: FONT_JUNGLEFEVER17OUTLINE
    0x005e8c40, // 13: SOUND_BUTTONCLICK
    0x005e8dac, // 14: FONT_LIDDIE12
    0x005e8bbc, // 15: FONT_LIDDIE15
    0x005e8a9c, // 16: FONT_LIDDIE18
    0x005e8a5c, // 17: FONT_JUNGLEFEVER12OUTLINE
    0x005e8e18, // 18: FONT_JUNGLEFEVER15OUTLINE
    0x005e8ea8, // 19: FONT_BLAMBOTPRO8
    0x005e8a28, // 20: FONT_BLAMBOTPRO15
    0x005e8c20, // 21: FONT_TINY
    0x005e8aa4, // 22: FONT_TINYBOLD
    0x005e8ce4, // 23: FONT_CONTINUUMBOLD12
    0x005e8cd0, // 24: FONT_CONTINUUMBOLD12OUTLINE
    0x005e8b04, // 25: FONT_CONTINUUMBOLD14
    0x005e8d1c, // 26: FONT_CONTINUUMBOLD14OUTLINE
    0x005e8cc0, // 27: IMAGE_DIALOG
    0x005e8c54, // 28: IMAGE_DIALOGBUTTON
    0x005e8dbc, // 29: IMAGE_EDITBOX
    0x005e8ba8, // 30: IMAGE_SELECTORSCREEN
    0x005e8cd8, // 31: IMAGE_STORESCREEN
    0x005e8ab4, // 32: IMAGE_HATCHSCREEN
    0x005e8c1c, // 33: IMAGE_MAINBUTTON
    0x005e8ad8, // 34: IMAGE_LEFTBUTTON
    0x005e8dec, // 35: IMAGE_RIGHTBUTTON
    0x005e8d28, // 36: IMAGE_CENTERBUTTON
    0x005e8c70, // 37: IMAGE_SCREENBACK
    0x005e8d3c, // 38: IMAGE_SCREENTITLE
    0x005e8e6c, // 39: IMAGE_SCREENTITLEHOLE
    0x005e8c58, // 40: IMAGE_FISHBOX
    0x005e8e7c, // 41: IMAGE_FISHBOXBUTTON
    0x005e8e78, // 42: IMAGE_PETBUTTON
    0x005e8a88, // 43: IMAGE_PETBUTTONRING
    0x005e8a38, // 44: IMAGE_PETBUTTONREFLECT
    0x005e8e4c, // 45: IMAGE_PETBUTTONHOLE
    0x005e8c5c, // 46: IMAGE_STORELEFTBUTTON
    0x005e8c78, // 47: IMAGE_STORETOPBUTTON
    0x005e8b3c, // 48: IMAGE_STORERIGHTBUTTON
    0x005e8d18, // 49: IMAGE_STORELEFTHILIGHT
    0x005e8c44, // 50: IMAGE_STORETOPHILIGHT
    0x005e8b38, // 51: IMAGE_STORERIGHTHILIGHT
    0x005e8cf8, // 52: IMAGE_BATTLETANKBUTTON
    0x005e8e00, // 53: IMAGE_BATTLETANKBUTTOND
    0x005e8b88, // 54: IMAGE_MIDDLEBUTTON
    0x005e8e9c, // 55: IMAGE_MIDDLEBUTTOND
    0x005e8c94, // 56: IMAGE_OPTIONSBUTTON
    0x005e8a20, // 57: IMAGE_OPTIONSBUTTOND
    0x005e8d64, // 58: IMAGE_MENUBTND
    0x005e8eb4, // 59: IMAGE_MENUBTND2
    0x005e8c60, // 60: IMAGE_MENUBTNU
    0x005e8e74, // 61: IMAGE_MENUBTNO
    0x005e8b84, // 62: IMAGE_PETBTNU
    0x005e8a48, // 63: IMAGE_PETBTNO
    0x005e8d5c, // 64: IMAGE_UNCHECKED
    0x005e8c64, // 65: IMAGE_CHECKED
    0x005e8cc8, // 66: IMAGE_SLIDERTRACK
    0x005e8be4, // 67: IMAGE_SLIDERTHUMB
    0x005e8b58, // 68: IMAGE_WAIT_BAR
    0x005e8b10, // 69: IMAGE_MENUBAR
    0x005e8e70, // 70: IMAGE_MONEYFLASH
    0x005e8e2c, // 71: IMAGE_MENUBUTTONREFLECTION
    0x005e8dc0, // 72: IMAGE_TROPHYBAR
    0x005e8c18, // 73: IMAGE_SPEECHBUBBLE
    0x005e8da4, // 74: IMAGE_SHADOW
    0x005e8bf4, // 75: IMAGE_HATCHREFLECTION
    0x005e8eac, // 76: IMAGE_SELECTORSPEECHBUBBLE
    0x005e8a6c, // 77: IMAGE_HELPARROW
    0x005e8ba4, // 78: IMAGE_TANKCHOOSER
    0x005e8b18, // 79: IMAGE_BOLT
    0x005e8a58, // 80: IMAGE_HORZCREASE
    0x005e8cbc, // 81: IMAGE_VERTCREASE
    0x005e8c80, // 82: IMAGE_BUBBULATOR_STORE
    0x005e8c68, // 83: IMAGE_AA_STORE
    0x005e8b44, // 84: IMAGE_ZZZ
    0x005e8cc4, // 85: IMAGE_BONUSBUCKET
    0x005e8ca4, // 86: IMAGE_HELPALIEN
    0x005e8b34, // 87: IMAGE_HELPPETCHOOSE
    0x005e8a1c, // 88: IMAGE_HELPSCREENSAVER
    0x005e8bb8, // 89: IMAGE_BONUS1
    0x005e8ab0, // 90: IMAGE_BONUS2
    0x005e8dd8, // 91: IMAGE_BONUS3
    0x005e8ef8, // 92: IMAGE_WELCOMETO
    0x005e8d98, // 93: IMAGE_WELCOMEBACK
    0x005e8d0c, // 94: IMAGE_PIZZA
    0x005e8e0c, // 95: IMAGE_ICECREAM
    0x005e8b64, // 96: IMAGE_CHICKEN
    0x005e8bb4, // 97: IMAGE_SPARKLE
    0x005e8c14, // 98: IMAGE_TANKBACKDROP1
    0x005e8d48, // 99: IMAGE_TANKBACKDROP2
    0x005e8da0, // 100: IMAGE_TANKBACKDROP3
    0x005e8a8c, // 101: IMAGE_TANKBACKDROP4
    0x005e8f08, // 102: IMAGE_TANKBACKDROP5
    0x005e8df8, // 103: IMAGE_TANKBACKDROP6
    0x005e8e3c, // 104: IMAGE_HEALTHBAR
    0x005e8eb8, // 105: IMAGE_HEALTHBARTUBE
    0x005e8b74, // 106: IMAGE_HELPSHELL
    0x005e8c3c, // 107: IMAGE_STORESHELL
    0x005e8a04, // 108: IMAGE_BONUSBUTTONOVERLAY
    0x005e8ed8, // 109: IMAGE_FATBUTTON
    0x005e8cac, // 110: IMAGE_EGGBRINKLEY
    0x005e8ee4, // 111: IMAGE_EGGNOSTRADAMUS
    0x005e8d68, // 112: IMAGE_EGGSTANLEY
    0x005e8db0, // 113: IMAGE_EGGWALTER
    0x005e8e38, // 114: IMAGE_PETLIMITEGG
    0x005e8ea0, // 115: IMAGE_BONUSAWARD
    0x005e8dd4, // 116: IMAGE_BONUSAWARD2
    0x005e8a64, // 117: IMAGE_AA_BEAM
    0x005e8d90, // 118: IMAGE_AA_GLOW
    0x005e8cfc, // 119: IMAGE_AA_TOP1
    0x005e8b8c, // 120: IMAGE_AA_TOP2
    0x005e8b90, // 121: IMAGE_AA_BOTTOM
    0x005e8d04, // 122: IMAGE_SPARKS
    0x005e8a44, // 123: IMAGE_ENERGYBALL
    0x005e8a34, // 124: IMAGE_CHOMP
    0x005e8e34, // 125: IMAGE_LASERS
    0x005e8c84, // 126: IMAGE_BUBBLES
    0x005e8e60, // 127: IMAGE_MONEY
    0x005e8bd8, // 128: IMAGE_PEARL
    0x005e8c50, // 129: IMAGE_PEANUT
    0x005e8bc4, // 130: IMAGE_MISCITEMS
    0x005e8d7c, // 131: IMAGE_SHELLS
    0x005e8d88, // 132: IMAGE_MONEYBAG
    0x005e8aa0, // 133: IMAGE_FOOD
    0x005e8ee8, // 134: IMAGE_BALLS
    0x005e8ddc, // 135: IMAGE_MERYLLIPS
    0x005e8ad4, // 136: IMAGE_MERYLBLINK
    0x005e8a40, // 137: IMAGE_MERYLTAIL
    0x005e8e1c, // 138: IMAGE_CROSSHAIR
    0x005e8a78, // 139: IMAGE_HATCHANIMATION
    0x005e8e28, // 140: IMAGE_TROPHYBUTTONS
    0x005e8d40, // 141: IMAGE_EXPLOSION
    0x005e8ef0, // 142: IMAGE_EXPLOSIONSMALL
    0x005e8df4, // 143: IMAGE_EXPLOSIONTINY
    0x005e8a90, // 144: IMAGE_SMOKETINY
    0x005e8bb0, // 145: IMAGE_SMOKESMALL
    0x005e8d58, // 146: IMAGE_SMOKEMISSILE
    0x005e8e5c, // 147: IMAGE_WARPHOLE
    0x005e8c08, // 148: IMAGE_WARPGLOW
    0x005e8c00, // 149: IMAGE_EGGPIECES
    0x005e8a24, // 150: IMAGE_EGGSHARDS
    0x005e8c74, // 151: IMAGE_EGGCRACK1
    0x005e8ca8, // 152: IMAGE_EGGCRACK2
    0x005e8d70, // 153: IMAGE_BUBBULATOR
    0x005e8a60, // 154: IMAGE_STOREBACKDROPS
    0x005e8a50, // 155: IMAGE_WAVESIDE
    0x005e8af4, // 156: IMAGE_WAVE
    0x005e8a10, // 157: IMAGE_LASERUPGRADES
    0x005e8a2c, // 158: IMAGE_MISSILE
    0x005e8b70, // 159: IMAGE_AQUARIUM1
    0x005e8c04, // 160: IMAGE_AQUARIUM2
    0x005e8d50, // 161: IMAGE_AQUARIUM3
    0x005e8adc, // 162: IMAGE_AQUARIUM4
    0x005e8be8, // 163: IMAGE_AQUARIUM5
    0x005e8db8, // 164: IMAGE_AQUARIUM6
    0x005e8bc0, // 165: IMAGE_TANKMASK1
    0x005e8f04, // 166: IMAGE_TANKMASK2
    0x005e8a30, // 167: IMAGE_TANKMASK3
    0x005e8ad0, // 168: IMAGE_TANKMASK4
    0x005e8af8, // 169: IMAGE_TANKMASK5
    0x005e8a74, // 170: IMAGE_TANKMASK6
    0x005e8d84, // 171: IMAGE_SMALLTURN
    0x005e8e88, // 172: IMAGE_HUNGRYTURN
    0x005e8ecc, // 173: IMAGE_HUNGRYEAT
    0x005e8e08, // 174: IMAGE_SIMTURN1
    0x005e8a00, // 175: IMAGE_SIMTURN2
    0x005e8b54, // 176: IMAGE_SIMTURN3
    0x005e8ec0, // 177: IMAGE_SMALLEAT
    0x005e8aa8, // 178: IMAGE_SMALLDIE
    0x005e8e48, // 179: IMAGE_HUNGRYSWIM
    0x005e8dc4, // 180: IMAGE_HUNGRYBREEDER
    0x005e8c24, // 181: IMAGE_SIMEAT1
    0x005e8b14, // 182: IMAGE_SIMEAT2
    0x005e8bd4, // 183: IMAGE_SIMEAT3
    0x005e8b78, // 184: IMAGE_SIMSWIM1
    0x005e8eec, // 185: IMAGE_SIMSWIM2
    0x005e8efc, // 186: IMAGE_SIMSWIM3
    0x005e8b48, // 187: IMAGE_SIMCARNIVORE
    0x005e8ae8, // 188: IMAGE_TANKLIGHTING
    0x005e8ebc, // 189: IMAGE_SYLV
    0x005e8cec, // 190: IMAGE_BALROG
    0x005e8ae4, // 191: IMAGE_GUS
    0x005e8ec8, // 192: IMAGE_DESTRUCTOR
    0x005e8e58, // 193: IMAGE_ULYSSES
    0x005e8c4c, // 194: IMAGE_PSYCHOSQUID
    0x005e8f00, // 195: IMAGE_BILATERUS
    0x005e8c0c, // 196: IMAGE_MINISYLV
    0x005e8cb8, // 197: IMAGE_BOSS
    0x005e8c7c, // 198: IMAGE_HALO
    0x005e8bcc, // 199: IMAGE_GUMBOLIGHT
    0x005e8ce8, // 200: IMAGE_AMPCHARGE
    0x005e8aac, // 201: IMAGE_NIKOTOWER
    0x005e8be0, // 202: IMAGE_STINKY
    0x005e8e44, // 203: IMAGE_NIKO
    0x005e8aec, // 204: IMAGE_ITCHY
    0x005e8ca0, // 205: IMAGE_PREGO
    0x005e8e30, // 206: IMAGE_ZORF
    0x005e8bd0, // 207: IMAGE_CLYDE
    0x005e8d38, // 208: IMAGE_VERT
    0x005e8b60, // 209: IMAGE_RUFUS
    0x005e8b08, // 210: IMAGE_MERYL
    0x005e8b30, // 211: IMAGE_WADSWORTH
    0x005e8b0c, // 212: IMAGE_SEYMOUR
    0x005e8c2c, // 213: IMAGE_SHRAPNEL
    0x005e8cb4, // 214: IMAGE_GUMBO
    0x005e8a14, // 215: IMAGE_BLIP
    0x005e8a98, // 216: IMAGE_RHUBARB
    0x005e8a08, // 217: IMAGE_NIMBUS
    0x005e8de8, // 218: IMAGE_AMP
    0x005e8bfc, // 219: IMAGE_GASH
    0x005e8e8c, // 220: IMAGE_ANGIE
    0x005e8d60, // 221: IMAGE_PRESTO
    0x005e8b4c, // 222: IMAGE_BRINKLEY
    0x005e8ed4, // 223: IMAGE_NOSTRADAMUS
    0x005e8d00, // 224: IMAGE_STANLEY
    0x005e8e50, // 225: IMAGE_WALTER
    0x005e8ab8, // 226: IMAGE_SMALLSWIM
    0x005e8c98, // 227: IMAGE_GRUBBER
    0x005e8e04, // 228: IMAGE_STARCATCHER
    0x005e8da8, // 229: IMAGE_GEKKO
    0x005e8d4c, // 230: IMAGE_BREEDER
    0x005e8cf4, // 231: IMAGE_ULTRA
    0x005e8a84, // 232: IMAGE_SCL_STINKY
    0x005e8ed0, // 233: IMAGE_SCL_NIKO
    0x005e8cb0, // 234: IMAGE_SCL_ITCHY
    0x005e8ee0, // 235: IMAGE_SCL_PREGO
    0x005e8d20, // 236: IMAGE_SCL_ZORF
    0x005e8b2c, // 237: IMAGE_SCL_CLYDE
    0x005e8ac8, // 238: IMAGE_SCL_VERT
    0x005e8eb0, // 239: IMAGE_SCL_RUFUS
    0x005e8bf0, // 240: IMAGE_SCL_MERYL
    0x005e8a0c, // 241: IMAGE_SCL_WADSWORTH
    0x005e8db4, // 242: IMAGE_SCL_SEYMOUR
    0x005e8dcc, // 243: IMAGE_SCL_SHRAPNEL
    0x005e8b94, // 244: IMAGE_SCL_GUMBO
    0x005e8ccc, // 245: IMAGE_SCL_BLIP
    0x005e8cdc, // 246: IMAGE_SCL_RHUBARB
    0x005e8d24, // 247: IMAGE_SCL_NIMBUS
    0x005e8dfc, // 248: IMAGE_SCL_AMP
    0x005e8b7c, // 249: IMAGE_SCL_GASH
    0x005e8d30, // 250: IMAGE_SCL_ANGIE
    0x005e8c88, // 251: IMAGE_SCL_PRESTO
    0x005e8ae0, // 252: IMAGE_SCL_BRINKLEY
    0x005e8afc, // 253: IMAGE_SCL_NOSTRADAMUS
    0x005e8abc, // 254: IMAGE_SCL_STANLEY
    0x005e8a54, // 255: IMAGE_SCL_WALTER
    0x005e8b80, // 256: IMAGE_SCL_OSCAR
    0x005e8bac, // 257: IMAGE_SCL_GRUBBER
    0x005e8ac0, // 258: IMAGE_SCL_STARCATCHER
    0x005e8ce0, // 259: IMAGE_SCL_GEKKO
    0x005e8c90, // 260: IMAGE_SCL_BREEDER
    0x005e8dc8, // 261: IMAGE_SCL_ULTRA
    0x005e8c28, // 262: SOUND_AWOOGA
    0x005e8c38, // 263: SOUND_APPLAUSE
    0x005e8dd0, // 264: SOUND_BABY
    0x005e8edc, // 265: SOUND_BONUSCOUNT
    0x005e8ec4, // 266: SOUND_TONE
    0x005e8a3c, // 267: SOUND_TONELO
    0x005e8a68, // 268: SOUND_TONEHI
    0x005e8a7c, // 269: SOUND_TONESUPERHI
    0x005e8acc, // 270: SOUND_PRIMALSCREAM
    0x005e8e24, // 271: SOUND_BONUSCOLLECT
    0x005e8b98, // 272: SOUND_BUBBLES
    0x005e8d14, // 273: SOUND_BUY
    0x005e8f0c, // 274: SOUND_BUZZER
    0x005e8ba0, // 275: SOUND_CHOMP
    0x005e8c8c, // 276: SOUND_CHOMP2
    0x005e8d10, // 277: SOUND_CROWNED
    0x005e8d08, // 278: SOUND_DIAMOND
    0x005e8a70, // 279: SOUND_DIE
    0x005e8e14, // 280: SOUND_DROPFOOD
    0x005e8d78, // 281: SOUND_EEL1
    0x005e8ac4, // 282: SOUND_EEL2
    0x005e8b9c, // 283: SOUND_EEL3
    0x005e8c9c, // 284: SOUND_EVILLAFF
    0x005e8d54, // 285: SOUND_EXPLODE
    0x005e8b28, // 286: SOUND_EXPLOSION1
    0x005e8e84, // 287: SOUND_EXPLOSION4
    0x005e8e90, // 288: SOUND_FART
    0x005e8ef4, // 289: SOUND_FART2
    0x005e8af0, // 290: SOUND_GROW
    0x005e8e98, // 291: SOUND_GUFFAW
    0x005e8d44, // 292: SOUND_HATCH
    0x005e8bf8, // 293: SOUND_HEAL
    0x005e8e68, // 294: SOUND_HIT
    0x005e8bc8, // 295: SOUND_INTERFER
    0x005e8d94, // 296: SOUND_MISSLE
    0x005e8b20, // 297: SOUND_NIKOOPEN
    0x005e8c34, // 298: SOUND_NIKOCLOSE
    0x005e8e54, // 299: SOUND_PEARL
    0x005e8d74, // 300: SOUND_POINTS
    0x005e8b24, // 301: SOUND_POINTS2
    0x005e8e94, // 302: SOUND_POINTS3
    0x005e8b1c, // 303: SOUND_POINTS4
    0x005e8d34, // 304: SOUND_PUNCH
    0x005e8e10, // 305: SOUND_RATTLE
    0x005e8b40, // 306: SOUND_RICOCHET
    0x005e8c6c, // 307: SOUND_ROAR
    0x005e8b6c, // 308: SOUND_ROAR2
    0x005e89fc, // 309: SOUND_ROAR3
    0x005e8c48, // 310: SOUND_SFX
    0x005e8c10, // 311: SOUND_SING
    0x005e8de4, // 312: SOUND_SLURP
    0x005e8bdc, // 313: SOUND_SLURP2
    0x005e8de0, // 314: SOUND_SLURP3
    0x005e8d8c, // 315: SOUND_SNEEZE
    0x005e8a18, // 316: SOUND_SONAR
    0x005e8e64, // 317: SOUND_SPLASH
    0x005e8d2c, // 318: SOUND_SPLASH2
    0x005e8cd4, // 319: SOUND_SPLASH3
    0x005e8ea4, // 320: SOUND_SPLASHBIG
    0x005e8b68, // 321: SOUND_TAPGLASS
    0x005e8df0, // 322: SOUND_TREASURE
    0x005e8a94, // 323: SOUND_UNLEASH
    0x005e8d9c, // 324: SOUND_ZAP
    0x005e8b5c, // 325: SOUND_ZZAM
];
