"""Generate src/sexy/res_gen.rs: the resource globals the generated `Res.cpp` code fills in.

The original's `Extract<Group>Resources()` functions look up each resource by its string id
and store the handle in a global (`DAT_005e8aa0 = GetImage("IMAGE_FOOD")` ...). The game
code reads those globals directly, so the port keeps one field per global, named by its
address, plus the table that ties each global to its resource id. Parsed from the function
text in the database (images use `thunk_FUN_004682b0`, fonts vtable +0x48, sounds +0x44).
"""
import os, re, sqlite3, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pe_read import read, EXE  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(HERE)
DB = os.path.join(CRATE, '..', 'gamedb_index', 'winfish.sqlite')
OUT = os.path.join(CRATE, 'src', 'sexy', 'res_gen.rs')

PAT = re.compile(r'FUN_00(?:426be0|41d8b0)\("((?:IMAGE|FONT|SOUND|MUSIC)_[A-Z0-9_]+)"[^;]*;(.{0,400}?)\b_?(DAT_[0-9a-f]{8})\s*=\s*([^;]+);', re.S)


def main():
    con = sqlite3.connect('file:' + os.path.abspath(DB).replace('\\', '/') + '?mode=ro', uri=True)
    found = {}
    sources = []
    per_fn = {}
    for addr, text, rtext in con.execute("SELECT address, text, recovered_text FROM port_functions WHERE coalesce(recovered_text, text) LIKE '%IMAGE%' OR text LIKE '%FONT%' OR text LIKE '%SOUND%'"):
        src = rtext or text
        for m in PAT.finditer(src):
            rid, between, glob, rhs = m.groups()
            if 'FUN_00426be0("' in between or 'FUN_0041d8b0("' in between:
                continue  # the store belongs to a later id
            kind = 'image' if '004682b0' in rhs else 'font' if '+ 0x48' in rhs else 'sound' if '+ 0x44' in rhs else None
            if kind is None:
                continue
            g = int(glob[4:], 16)
            if g in found and found[g][0] != rid:
                raise SystemExit(f'{glob} bound to both {found[g][0]} and {rid}')
            found[g] = (rid, kind, addr)
            sources.append(addr)
            per_fn.setdefault(addr, []).append((rid, g, kind))
    rows = sorted(found.items())
    out = ['// @generated by tools/gen_res.py from the Extract*Resources functions in winfish.sqlite.\n',
           '// Do not edit by hand.\n\n',
           'use crate::sexy::types::Ptr;\n\n',
           '/// Resource globals of the original, one field per `DAT_` address. Images and fonts\n',
           '/// hold object pointers; sounds hold sound ids.\n',
           '#[derive(Debug, Default, Clone)]\npub struct Res {\n']
    for g, (rid, kind, src) in rows:
        out.append(f'    /// `{rid}` ({kind}, set in the function at {src:08x})\n    pub DAT_{g:08x}: {"i32" if kind == "sound" else "Ptr"},\n')
    out.append('}\n\n')
    out.append('#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum ResKind { Image, Font, Sound }\n\n')
    out.append('/// (global address, resource id, kind) for every resource global.\n')
    out.append(f'pub const RES_GLOBALS: [(u32, &str, ResKind); {len(rows)}] = [\n')
    for g, (rid, kind, src) in rows:
        out.append(f'    (0x{g:08x}, "{rid}", ResKind::{kind.capitalize()}),\n')
    out.append('];\n\n')
    out.append('impl Res {\n    /// Stores a resolved resource into the global at `addr`.\n'
               '    pub fn set(&mut self, addr: u32, value: i32) {\n        match addr {\n')
    for g, (rid, kind, src) in rows:
        cast = 'value' if kind == 'sound' else 'value as Ptr'
        out.append(f'            0x{g:08x} => self.DAT_{g:08x} = {cast},\n')
    out.append('            _ => panic!("no resource global at {addr:08x}"),\n        }\n    }\n\n')
    out.append('    /// Reads the global at `addr` (images/fonts as their pointer value).\n'
               '    pub fn get(&self, addr: u32) -> i32 {\n        match addr {\n')
    for g, (rid, kind, src) in rows:
        cast = '' if kind == 'sound' else ' as i32'
        out.append(f'            0x{g:08x} => self.DAT_{g:08x}{cast},\n')
    out.append('            _ => panic!("no resource global at {addr:08x}"),\n        }\n    }\n}\n\n')
    # gResources[] at 005e0a10: numeric resource id (generated ResourceId enum) -> its global.
    data = open(EXE, 'rb').read()
    table = []
    while True:
        a = struct.unpack('<I', read(data, 0x005E0A10 + 4 * len(table), 4))[0]
        if a not in found:
            break
        table.append(a)
    out.append('/// `PTR_DAT_005e0a10`: the address of the global of each numeric resource id\n'
               '/// (what `GetIntById` / `GetImageById`, e.g. `FUN_005016a0`, index).\n')
    out.append(f'pub const RES_BY_ID: [u32; {len(table)}] = [\n')
    for i, a in enumerate(table):
        out.append(f'    0x{a:08x}, // {i}: {found[a][0]}\n')
    out.append('];\n')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(out))
    # The Extract<Group>Resources functions themselves, in their original order.
    names = dict(con.execute('SELECT address, name FROM port_functions'))
    ex = ['// @generated by tools/gen_res.py from the Extract*Resources functions in winfish.sqlite.\n',
          '// Do not edit by hand.\n\n',
          'use crate::sexy::prelude::*;\nuse crate::sexy::resource_manager::{get_font, get_image, get_sound};\n\n']
    for addr in sorted(per_fn):
        items = per_fn[addr]
        ex.append(f'/// port: {addr:08x} {names[addr]}\n')
        ex.append(f'/// `Extract...Resources(ResourceManager*)`: binds {len(items)} resource globals. A missing\n'
                  '/// resource makes the original throw `ResourceManagerException`, which it catches and\n'
                  '/// returns false; here the lookup returns false the same way.\n')
        ex.append(f'pub fn {names[addr]}(g: &mut G) -> bool {{\n    g.globals.DAT_005e8f17 = true;\n')
        for rid, gaddr, kind in items:
            if kind == 'image':
                ex.append(f'    g.res.DAT_{gaddr:08x} = get_image(g, "{rid}");\n    if g.res.DAT_{gaddr:08x} == NULL {{\n        return false;\n    }}\n')
            elif kind == 'font':
                ex.append(f'    g.res.DAT_{gaddr:08x} = get_font(g, "{rid}");\n    if g.res.DAT_{gaddr:08x} == NULL {{\n        return false;\n    }}\n')
            else:
                ex.append(f'    g.res.DAT_{gaddr:08x} = get_sound(g, "{rid}");\n    if g.res.DAT_{gaddr:08x} == -1 {{\n        return false;\n    }}\n')
        ex.append('    true\n}\n\n')
    with open(os.path.join(CRATE, 'src', 'game', 'res_extract_gen.rs'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(ex))
    kinds = {}
    for _, (rid, kind, _) in rows:
        kinds[kind] = kinds.get(kind, 0) + 1
    print(f'wrote {OUT}: {len(rows)} globals {kinds} from {len(set(sources))} functions')


if __name__ == '__main__':
    main()
